### ISSUE TITLE
Автоматическое заполнение реализации

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#10]
При ручном создании реализации и выбора покупателя програма заполняет табличную часть всеми предыдущими заказами даже если они были выполнены.
![image](https://user-images.githubusercontent.com/82500510/114879145-9b294700-9e09-11eb-80c7-21ab5f915471.png)
![image](https://user-images.githubusercontent.com/82500510/114879275-b5fbbb80-9e09-11eb-9984-3f70212edea4.png)
![image](https://user-images.githubusercontent.com/82500510/114879618-0a06a000-9e0a-11eb-8725-782330a22822.png)
Красный - заказ 00009
Жёлтый - заказ 00013
Синий - заказ 00006

**Comment by Nullarity** [comment]
Подскажите пожалуйста, эти выполненные заказы, они были со скидками внутри, верно?

**Comment by Nullarity** [comment]
Проблему удалось локализовать. После обновления, перепроведите пожалуйста расходные накладные, тогда они закроют заказы корректно и при следующем заполнении, они уже не будут "вылезать" как незакрытые.

p.s. если проблема решается, нажимайте здесь кнопочку Close или Close with comment, чтобы мы знали, что у вас все получилось. Спасибо!

**Comment by TeodorUn** [comment]
> Подскажите пожалуйста, эти выполненные заказы, они были со скидками внутри, верно?
Желтый со скидками, Синий - без

**Comment by TeodorUn** [comment]
После перепроведение реализаций с обновлением, проблема исчезла.
