### ISSUE TITLE
Дополнение в настройки Приложение

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#101]
Если можно, добавьте в папку Закрытие полученных авансов на закладке Настройки Приложения дополнительно НДС с авансов 8%. Очень часто сталкивалась с ситуацией, когда приходилось вручную, выуживая информацию по документам, закрывать суммы под 8% НДС.
![image](https://user-images.githubusercontent.com/84187165/120641967-f7f5c500-c47c-11eb-8b4a-50f0b02554cd.png)

**Comment by Nullarity** [comment]
А эти значения работают как значения по умолчанию при вводе данных. Например, при создании договора, у вас есть возможность там указать, по какой ставке по нему зачитывать авансы, но по умолчанию, в договор придет ставка из настроек программы. Также, вы ставку можете изменить на уровне документов, например при оплате, если это аванс, на вкладке Дополнительно, можно указать ставку, по какой начислять НДС, и ставка также меняется в документе зачет выданных авансов.

**Comment by Linda4ka** [comment]
Т.е необходимости добавлять нет?

**Comment by Linda4ka** [comment]
Ну ладно! Вы мне про закрытие года расскажите, я чуть раньше об этом спрашивала

**Comment by Nullarity** [comment]
> Ну ладно! Вы мне про закрытие года расскажите, я чуть раньше об этом спрашивала

У меня складывается такое впечатление, что для вас дискуссии о функциональности программы, выглядят как какое-то состязание интеллектуалов, а каждый мой ответ испытывается на прочность по непонятной мне методике. "Ну ладно!" читается как какое-то одолжение. Если остались неясности, давайте обсуждать, мы вообще-то  в одной лодке. В противном случае, а теряюсь, непонятно, мне в следующий раз тратить свое время на развернутый ответ или не стоит (поверьте, как и у вас, у меня также есть масса дел, которые стоят того, чтобы ими заняться)

**Comment by Linda4ka** [comment]
Все нормально. Если я написала ну ладно, это значит мне все понятно и нет необходимости развивать дальше. Вы же знаете, если мне не понятно я с удовольствием вынесу мозг, но добью интересующий меня вопрос!
