### ISSUE TITLE
Изменение в Настройках Приложения

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#102]
Поменяйте, пожалуйста в описании к 158 коду застрахованного лица, вместо с 3 до 6 лет  должно сейчас быть с 3 до 4 лет.
![image](https://user-images.githubusercontent.com/84187165/120642308-66d31e00-c47d-11eb-9afe-87899512c173.png)

**Comment by Linda4ka** [comment]
В описании необходимо добавить Выплаченное из БГСС
![image](https://user-images.githubusercontent.com/84187165/120642760-f7116300-c47d-11eb-9e6f-ff295d1cbb08.png)

**Comment by Linda4ka** [comment]
Необходимо добавить  До 3-х лет
![image](https://user-images.githubusercontent.com/84187165/120643036-51122880-c47e-11eb-83eb-d8df044a6dff.png)

**Comment by Linda4ka** [comment]
Описание звучит так: Лицо, получившее пособие по временной нетрудоспособности в связи с несчастным случаем на производстве или профессиональным заболеванием, выплаченное из средств БГСС
![image](https://user-images.githubusercontent.com/84187165/120644040-8e2aea80-c47f-11eb-9a22-2c576b1dde5d.png)

**Comment by Linda4ka** [comment]
Описание звучит так:Лицо, получившее пособие по временной нетрудоспособности в связи с несчастным случаем на производстве или профессиональным заболеванием, выплаченное из средств работодателя
![image](https://user-images.githubusercontent.com/84187165/120644418-f8dc2600-c47f-11eb-9e0e-4b2859afc588.png)

**Comment by Linda4ka** [comment]
Это не срочно, но поменять необходимо для соответствия.Извините за дотошность)))

**Comment by Nullarity** [comment]
спасибо за замечания!

**Comment by Linda4ka** [comment]
Это не замечания, это подсказки)))

**Comment by Nullarity** [comment]
@Linda4ka, продублируйте пожалуйста в удобном для вас виде все изменения на рум. языке, этот класс данных у нас идет на двух языках:
![image](https://user-images.githubusercontent.com/28710693/122657662-a7948d80-d133-11eb-87bd-2928e1f8909e.png)

Спасибо!

**Comment by Linda4ka** [comment]
[Застрахованные лица.xlsx](https://github.com/Contabilizare/c5/files/6684945/default.xlsx)
