### ISSUE TITLE
Настройка приложений. Закладка опции

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#103]
![image](https://user-images.githubusercontent.com/84187165/120645966-b61b4d80-c481-11eb-9019-bb18d1b7a4d8.png)
Что должно быть отмечено по умолчанию или что необходимо отметить при начале работы предприятия. Что означает и необходимость, имеющейся на закладке информации?!

**Comment by Nullarity** [comment]
боюсь ответ на этот вопрос в общем случае может получиться очень большим. Может есть какие-то более специфичные вопросы по этим галочкам?

**Comment by Linda4ka** [comment]
Ну тогда 1 часть вопроса: что должно быть по умолчанию?

**Comment by Nullarity** [comment]
я думаю что ничего, или только использовать упаковки

**Comment by Linda4ka** [comment]
короче говоря, роли особой на работу предприятия это не влияет?

**Comment by Nullarity** [comment]
можно сказать и так. Эти опции служат для того, чтобы включить/отключить функциональность, которую предприятие не использует, таким образом, разгружается интерфейс приложения, пропадают ненужные поля/кнопки.

**Comment by Linda4ka** [comment]
Хорошо, оставим как есть.
