### ISSUE TITLE
Расширить начальную базу типовым набором услуг поставщика

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#109]
Просьба все желающих добавить в комментариях список услуг (интернет, телефон и т.д.) поставщиков, которые вы бы хотели видеть в начальной базе (при создании новой организации). Язык элемента видимо должен быть румынский?
Спасибо!

**Comment by Linda4ka** [comment]
День добрый! Почему румынский? Я думаю, это не обязательно. Если в программе практически все на русском, то пускай все остается на русском. Надо подумать что можно и нужно добавить. Сообщим позже!

**Comment by Linda4ka** [comment]
После обсуждения  решили следующее:Электроэнергия, вода, аренда, отопление, телефон, интернет, охрана, вывоз мусора, услуги по доставке ( вода, товары и т.д), подписка, почтовые услуги.

**Comment by Nullarity** [comment]
отлично! Но вот забыл попросить это все со счетами затрат и статьей, дополните пожалуйста )) Спасибо!

**Comment by Linda4ka** [comment]
Ну тогда ситуация следующая: Электроэнергия, вода, аренда, отопление, телефон, вывоз мусора, интернет,охрана - могут распределяться по следующим счетам: 712,1 Расходы на коммерческий персонал
                                                                713,1 Расходы на административный персонал
                                                                811 Прямые материальные затраты на основную деятельность
                                                                812 Косвенные материальные затраты на вспомогательную деятельность 
Услуги по доставке: 713,8 Прочие административные расходы
Почтовые услуги                     - 712,1 Расходы на коммерческий персонал
                                                  713,1 Расходы на административный персонал (но некоторые могут отражать на 713,8)
Подписка и страховка - 261 Текущие расходы будущих периодов
