### ISSUE TITLE
Несоответствие единиц измерения и цены

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#11]
При заполнении коммерческого предложения используя "упаковки" отображаемая цена является за упаковку. Дальнейшее расчёты исходят из умножения единица упаковки и цены. В печатной форме не соблюдается та же логика: отображается количество единицы ( не упаковок) и цена за упвковку. Нужно поменять так чтобы цена соответствовала единицам (либо указать "упаковку" и количество "упаковок" либо цену за штуку).
Как предложения по улучшению читабельности Комерческого предложения : размер скиди заменить на процент скидки а сумму скидки показати ниже вместе с итогом до и после скидки. Идеально было  бы включить в таблицу колонку "скидка" только в случае когда она <>0 да бы не испортить настроение клиенту цифрой 0.
![image](https://user-images.githubusercontent.com/82500510/114895741-6b357000-9e18-11eb-8b36-4e7046105a42.png)
![image](https://user-images.githubusercontent.com/82500510/114895897-886a3e80-9e18-11eb-9a66-df1537bca7e9.png)

**Comment by Nullarity** [comment]
Спасибо за замечание и предложение. Принимается, но ошибку исправим вот прям сейчас, а предложение - через релиз

**Comment by Nullarity** [comment]
@TeodorUn как вы считаете:

> Как предложения по улучшению читабельности Комерческого предложения : размер скиди заменить на процент скидки а сумму скидки показати ниже вместе с итогом до и после скидки

Эту сумму лучше показывать с минусом или плюсом? Например:
![image](https://user-images.githubusercontent.com/28710693/118400791-211af680-b631-11eb-9a9c-f1aa81be5cc8.png)
