### ISSUE TITLE
Внесение изменений в утвержденный заказ покупателя.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#117]
Добрый день! У меня вопрос следующего характера: От покупателя был получен заказ на определенные услуги. Мы заказ оформили, отправили на утверждение и утвердили его. По условиям договоренности, клиент произвел 100% предоплату.
Спустя некоторое время клиент попросил нас добавить некоторые изменения в заказ из расчета уже имеющихся у нас денег. Скажем, перераспределить средства на несколько услуг вместо одной. Вопрос: Как мы можем в программе произвести изменения, утвержденного заказа так, чтобы они корректно отразились и зафиксировались?

**Comment by Nullarity** [comment]
Есть два способа:
1. Открыть заказ и нажать в нем кнопку Изменить
2. Аннулировать заказ, создать новый и перезаполнить оплату

**Comment by SvetlanaRes** [comment]
> 
> 1. Открыть заказ и нажать в нем кнопку Изменить
> 
По каким причинам в форме заказа нет кнопки Изменить?
В демоверсии - есть, в рабочей базе - нет.
Где необходимо указать возможность изменения заказа покупателя?

**Comment by Nullarity** [comment]
в справочник Пользователи / Дополнительно / Имеет право изменять утвержденные заказы покупателей

**Comment by SvetlanaRes** [comment]
> в справочник Пользователи / Дополнительно / Имеет право изменять утвержденные заказы покупателей

спасибо

**Comment by Linda4ka** [comment]
Добрый день! В Демо версии создала документ Заказ покупателя, на основании него сделала Реализацию - все прошло успешно. После внесла Изменения в Заказ, сохранила. После этого решила произвести реализацию, согласно внесенным изменениям, и  при попытке сохранить выдало следующее: Строка не согласована с документом Заказ покупателя
![image](https://user-images.githubusercontent.com/84187165/121848130-43686880-ccf2-11eb-9fb6-e01b95a5fd07.png)
![image](https://user-images.githubusercontent.com/84187165/121848319-8e827b80-ccf2-11eb-8104-6e63488b2263.png)
![image](https://user-images.githubusercontent.com/84187165/121848428-ac4fe080-ccf2-11eb-8094-3de03eb25755.png)
Я подумала что возможно после внесения изменений в заказ необходимо было внести изменения в табличную часть на закладку Услуги, но кнопка Добавить не активна. 
Что сделано не так, где с моей стороны допущена неточность, чтобы понимать как правильно необходимо заполнять документ. Спасибо

**Comment by SvetlanaRes** [comment]
@Linda4ka , а покажите закладку Услуги после изменений

**Comment by Linda4ka** [comment]
Скрин 2

**Comment by Linda4ka** [comment]
После внесения изменений на закладке Услуги ничего не меняется. Новая услуга не добавляется. 2 вопроса: 1) должна ли и 2) Или изменения напрямую должны влиять на реализацию?

**Comment by Linda4ka** [comment]
Данный вопрос снимается с рассмотрения, т.к. было упущение при оформлении изменений. Не соблюдена очередность заполнения документа.

**Comment by SvetlanaRes** [comment]
> Скрин 2

не тот. не видно "Услуги"
