### ISSUE TITLE
Контроль отгруженных позиций по заказу

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#122]
В ходе работы над заказом покупателя и внесениями изменений, столкнулись со следующей ситуацией: Программа не контролирует отгруженные(реализованные) позиции по заказу. Рассмотрим: у нас заказ с первоначальной услугой на 4 ед с последующей реализацией 2-х ед. Здесь все понятно. Далее было внесено изменение,при котором была уменьшена первоначальная услуга с 4 ед до 3 ед и  увеличина вторичная услуга на 1 ед. Здесь тоже все понятно. Но вот когда мы во второй раз внесли изменения, уменьшив первоначальную услугу до 1 ед, увеличив третью услугу до 10 единиц, программа с легкостью провела все изменения. Если учесть, что раннее на первичную услугу была произведена реализация на 2 ед, программа должна была запретить нам проведение документа при внесении второго изменения. Необходим четкий контроль по отгруженным(реализованным) позициям по заказу
![image](https://user-images.githubusercontent.com/84187165/121855993-a7902a00-ccfc-11eb-9002-2008f8f31a6c.png)
![image](https://user-images.githubusercontent.com/84187165/121856131-d27a7e00-ccfc-11eb-94ed-28ab00a35d48.png)
В скрине 1, попытка перепровести, раннее уже совершенную реализацию. 
Т.е. ситуация следующая: программа должна была нас затормозить при уменьшении, в заказе покупателя, перваначальной услуги меньше 2-х, реализованных раннее единиц.

**Comment by Nullarity** [comment]
Заказ в данном случае первичен, и его изменение, после того, как пользователь подтвердил осознанность своих действий (ведь заказ уже утвержден), не блокируются. Тут примерно такая же логика, как мы не блокируем изменение документа Поступление ТМЦ, если товар уже был реализован.

**Comment by SvetlanaRes** [comment]
@Nullarity, извините, но не совсем понятно. Получается в данном случае система ссылается на "осознанность" действий пользователя? Никакой проверки по остатку заказа? Никакого предупреждения, что позиция такая-то уже реализовано? ничего?

**Comment by Linda4ka** [comment]
В итоге у нас получится непонятно что.

**Comment by Nullarity** [comment]
Чтобы лучше понять суть претензий, мне нужно задать встречные вопросы. Я правильно понимаю, что в программу также нужно добавить запрет на изменение документа Поступление ТМЦ, если товар уже был продан? Если нет, тогда в чем принципиальное отличие описываемых ситуаций?

**Comment by Nullarity** [comment]
Еще хотелось бы напомнить, что изменение утвержденного заказа, является исключением и ненормальной ситуацией (еще и потому, что изменения не проходят процесс утверждения). Кроме этого, изменение заказа, по которому уже была проведена реализация, кажется еще более ненормальной ситуацией. Может я заблуждаюсь, поэтому приведите пожалуйста пример из жизни, когда у вас была бы возможность заказать товар, получить его, а потом попросить внести изменения в заказ.

**Comment by SvetlanaRes** [comment]
> Чтобы лучше понять суть претензий, мне нужно задать встречные вопросы. Я правильно понимаю, что в программу также нужно добавить запрет на изменение документа Поступление ТМЦ, если товар уже был продан? Если нет, тогда в чем принципиальное отличие описываемых ситуаций?

@Nullarity , не совсем та ситуация. Мы говорим о контроле заказа покупателя/поставщику и реализация/поступление ТМЦ.

**Comment by Nullarity** [comment]
> не совсем та ситуация

так вот я и пытаюсь понять, чем она отличается. Вы хотите запретить менять заказ, если остаток по нему уйдет в минус согласно уже введенных реализаций. Почему тогда мы должны позволять менять поступление, которое может приводит ровно к такой же проблеме?

**Comment by SvetlanaRes** [comment]
> Еще хотелось бы напомнить, что изменение утвержденного заказа, является исключением и ненормальной ситуацией (еще и потому, что изменения не проходят процесс утверждения). Кроме этого, изменение заказа, по которому уже была проведена реализация, кажется еще более ненормальной ситуацией. Может я заблуждаюсь, поэтому приведите пожалуйста пример из жизни, когда у вас была бы возможность заказать товар, получить его, а потом попросить внести изменения в заказ.

Из взаимоотношений с покупателями:
1)  заказали 4 рулона этикеток для принтера разных размеров. Получили 2 на тестирование. Принято решение поменять на другой размер и пользователь указывает 3 вместо 2-х. Ну и все, ошибка гарантирована.
2) счет на 10 часов авансом. оказано было 6 часов, остальное на оказание другой услуги. Человеческий фактор - корректируется вместо 6 и остаток 4 на 1, а 5....

**Comment by SvetlanaRes** [comment]
> > не совсем та ситуация
> 
> так вот я и пытаюсь понять, чем она отличается. Вы хотите запретить менять заказ, если остаток по нему уйдет в минус согласно уже введенных реализаций. Почему тогда мы должны позволять менять поступление, которое может приводит ровно к такой же проблеме (минусу на складе)?

Причем здесь поступление, абсолютно не зеркальная ситуация. 
В данном контексте говорим об аналоге регистра Заказ покупателя/Заказ поставщику, по которому контролировалась цепочка заказ покупателя/корректировка/рн и заказ поставщику/корректировка/поступление тмц.

**Comment by Nullarity** [comment]
> Причем здесь поступление, абсолютно не зеркальная ситуация.

А речь не о зеркальной ситуации, почему она должна быть зеркально? Речь о контроле на основе первичности операций. Заказ, как и Поступление - первичен, я спрашиваю, почему заказ контролировать нужно, а поступление нет.

**Comment by Linda4ka** [comment]
Пардон, а причем здесь Поступление ТМЦ. Естественно, что после того как был внесен приход, его менять никто не станет, т.к. данное действие происходит по документам и под роспись принимающего. Это вообще не пример.
Здесь немного другое, с приходом  ТМЦ не имеющее ничего общего.
Вот смотрите: Фирма Х сделала заказ фирме Ъ заказ на поклейку обоев в кол-ве 50 штук по цене за 1 ед - 90 лей. Соответственно сумма заказа составила 4500 лей. Аванс 100 %. В течении недели было наклеено 15 рулонов, произведена реализация на сумму 1350 лей. Т.е сумма из аванса в 1350 лей была закрыта. Осталось 3150 лей. Вдруг фирма Ъ попросила поменять заказ и вместо поклейки 90 обоев наклеить только 14, а остальную сумму перераспределить на покраску стен и установку плинтуса. Программа должна вести контроль уже реализованных услуг и информировать пользователя о том, что что -то уже было реализовано и не может быть меньше реализуемого количества.

**Comment by Nullarity** [comment]
> заказали 4 рулона этикеток для принтера разных размеров. Получили 2 на тестирование. Принято решение поменять на другой размер и пользователь указывает 3 вместо 2-х. Ну и все, ошибка гарантирована.

а где ошибка? Я видимо не понял пример, поменять на другой размер какое кол-во? Кажется, что заказ просто не закроется.

> счет на 10 часов авансом. оказано было 6 часов, остальное на оказание другой услуги. Человеческий фактор - корректируется вместо 6 и остаток 4 на 1, а 5....

Да, но также может быть вместо 6 и остаток 4, 7 и остаток 3, или 6 и остаток 40 (случайно ноль нажали на цифровой клавиатуре). Программа ведь не знает, как должно быть правильно. Может быть мы еще один час (7-6=1) выставим, а три на другую услугу, ведь ошибиться можно не только в меньшую, но и большую сторону.

На мой взгляд тут идет неверное (с т.з. заложенной в программе логики) использование заказа. В к5 для такой ситуации нужно закрыть заказ уменьшив кол-во часов и создать новый заказ с корректировкой аванса.

В к4 заказ это некий внутренний документ, с которым можно делать все что угодно, в к5 - это внешний документ (например, я делаю заказ через веб-сайт, как клиент) призванный планировать и упорядочивать работу и поступления. Если с услугами ситуация еще более-менее оправдана. то с товарами. которые могут уже сидеть в заказах поставщикам, такая свобода модификации заказов приводит с сложным ошибкам.

**Comment by Nullarity** [comment]
(в любом случае, ошибки будут видны или в журнале заказов или в отчете по заказам)

**Comment by Nullarity** [comment]
> Пардон, а причем здесь Поступление ТМЦ. Естественно, что после того как был внесен приход, его менять никто не станет, т.к. данное действие происходит по документам и под роспись принимающего. Это вообще не пример.
Здесь немного другое, с приходом ТМЦ не имеющее ничего общего.

Я с этим не согласен. Мы говорим про ошибки пользователя, они могут быть допущены в любом контексте, и ошибка может быть как в накладной, так и при ее вводе. Еще раз: 1) ввели заказ 2) продали 3) уменьшили заказ - нужен контроль. Другой: 1) Ввели приход 2) продали 3) уменьшили приход (ошибка в первичке или базе, не важно) - не нужен контроль. Для меня ситуации по сути равнозначны, отличаться может частотность проблемы.

**Comment by Linda4ka** [comment]
Ну здесь уже я совсем не согласна. 1) Товар принимается по накладной. Четко сверяются кол-во в накладной и принимаемое кол-во, если допущена ошибка, такую накладную вернут, а товар не примут-это я вам как бухгалтер говорю. Описываемая вами ситуация в природе быть не может. Изменение остатков после их ввода, а уж тем более если они уже были проданы- подсудное дело. Тут вы мне не рассказывайте. А вот заказ это другое.

**Comment by Nullarity** [comment]
> Вот смотрите: Фирма Х сделала заказ фирме Ъ на поклейку обоев в кол-ве 50 штук по цене за 1 ед - 90 лей. Соответственно сумма заказа составила 4500 лей. Аванс 100 %. В течении недели было наклеено 15 рулонов, произведена реализация на сумму 1350 лей. Т.е сумма из аванса в 1350 лей была закрыта. Осталось 3150 лей. Вдруг фирма Ъ попросила поменять заказ и вместо поклейки 90 обоев наклеить только 14, а остальную сумму перераспределить на покраску стен и установку плинтуса. Программа должна вести контроль уже реализованных услуг и информировать пользователя о том, что что -то уже было реализовано и не может быть меньше реализуемого количества.

В данном случае, нужно или полностью аннулировать заказ или закрыть предыдущий и ввести новый. Таким образом, соблюдается причинно следственная связь. У вас может не быть краски и плинтуса, и вам нужно будет их приобрести, прежде чем продолжать ремонт. А это соответственно заказ поставщику и дальнейшая цепочка. И если это будет каждый раз один и тот же скорректированный заказ, собрать потом всю историю будет сложно, ровно как и отдельные документы "Корректировка заказа", которые очень чувствительны к последовательности документов.

**Comment by Linda4ka** [comment]
Я сама работала на фирме, где клиенты регулярно просили заменить одну позицию другой в счет суммы. Это всегда делалось в пределах одного заказа. Почему сделать контроль реализуемых остатков это такая проблема. Просто может сложится ситуация, при которой нам придется это все дорабатывать, но это будет сделано со скандалами и нервотрепкой от клиента. Давайте делать сейчас, а не когда петух клюнет. Потом времени не будет и проблем куча. У нас большое множество клиентов, работающих с заказами и это надо учитывать

**Comment by Nullarity** [comment]
> Четко сверяются кол-во в накладной и принимаемое кол-во, если допущена ошибка, такую накладную вернут, а товар не примут-это я вам как бухгалтер говорю

Вы упускаете всю картину, либо вы не сталкивались с другими учетными ситуациями. Во-первых вы можете оприходовать ошибочно на другую номенклатуру или характеристику, также вы можете ошибиться в кол-ве в обе стороны, что в сумме сойдется, можете допустить ошибку в единице измерения. Кроме этого, нет никакого регулирования по способу ввода накладной в базу данных. К вам приходит корабль с буравой установкой, в накладной будет одна позиция, а в договоре - приложение со спецификацией в несколько сотен позиций, и приходуются именно они. Ошибок в таких документах возникает много.

**Comment by Linda4ka** [comment]
Обычно корабль с буровой установкой приходит по инвойсу, а там расписывается все что есть, вплоть до дополнительных болтов.

**Comment by Nullarity** [comment]
> Почему сделать контроль реализуемых остатков это такая проблема.

потому что это идет вразрез с текущей логикой подсистемы, где любое изменение заказа считается исключением, нежели правилом. Для чего нам заказы - для планирования и контроля. Именно для этого в них реализован базовый бизнес-процесс, и если система будет позволять делать с заказом любые манипуляции, это скажется на другом месте системы. Особенно четко это видно в онлайн торговле, вы даже свет товара изменить не сможете, если ваш заказ ушел в обработку (допустим хотите не черный самокат, а желтый). Максимум, можете позвонить менеджеру и отменить заказ, потом создать новый. Или взять уже ставшие стандартом де-факто процессы продаж амазона или алиэкспрес. Вся современная торговля построена по принципу - можем менять заказ, пока он не ушел в обработку.

**Comment by Nullarity** [comment]
> Обычно корабль с буровой установкой приходит по инвойсу, а там расписывается все что есть, вплоть до дополнительных болтов.

Ну тут нет предмета для спора, я вам описывал практический опыт, у вас он может быть другой. Но тема, почему контроль в одном месте нужен, а в другом нет - не раскрыта. Ваш пример "1) Товар принимается по накладной. Четко сверяются кол-во в накладной и принимаемое кол-во, если допущена ошибка, такую накладную вернут, а товар не примут-это я вам как бухгалтер говорю." я вообще не понял. При чем тут кладовщик с накладной в руках сверяющий выгружаемый товар? У него вообще может не быть компьютера. Я вам говорю про ошибки ввода данных в базу, и про логику их контроля.

**Comment by Nullarity** [comment]
> Давайте делать сейчас, а не когда петух клюнет. Потом времени не будет и проблем куча. У нас большое множество клиентов, работающих с заказами и это надо учитывать

В сухом остатке, какую проблему в этой теме мы обсуждаем, что программа не запрещает уменьшить заказ по которому была проведена реализация, правильно? При этом красным полезут отчеты и сам журнал заказов, что точно будет заметно.

Это не такая вроде бы и проблема, как возникнет ситуация - будем решать.

**Comment by Linda4ka** [comment]
Ну да, у нас уже столько проблем, которые мы будем решать когда нас клюнет, что я уже боюсь. Когда клиенты не примут данную программу, решать будет поздно!

**Comment by Nullarity** [comment]
> Дмитрий, вот давайте так, если вы не бухгалтер, то не пытайтесь мне рассказать как принимается и вводится товар

Предлагаю не бряцать медалями, а делиться опытом. Я вам не рассказываю как принимается товар, я вам описал минимум три варианта, при котором могут быть допущены ошибки ввода, и они не выдуманные, а происходят каждый день. Я добавлю еще два: разбиение строки прихода на счета учета, приход в подсобные помещения (склад в табличной части). И то, в какой строгости принимается товар не имеет к этому никакого отношения.

**Comment by Nullarity** [comment]
> Ну да, у нас уже столько проблем, которые мы будем решать когда нас клюнет, что я уже боюсь

Напомните пожалуйста, каких проблем, которые не приняты в работу, а отложены, как вот эта?

**Comment by Nullarity** [comment]
> На этом фоне и при ежемесячном формировании книги покупок, ошибки ввода практически сведены к 0.

Почитайте пожалуйста здесь https://buh.ru/articles/documents/65453/, насколько ошибки сведены к нулю.

**Comment by Nullarity** [comment]
@SvetlanaRes  и @Linda4ka вы утверждаете, что отсутствие каких-либо сообщений в случае уменьшения реализованного товара является проблемой, в тоже самое время, в к4 изменение заказа вообще не контролируется и никак не блокируется, пользователь может уменьшить кол-во в заказе и ничего система об этом не сообщит. Прокомментируйте пожалуйста описанную ситуацию. Или вы клиентам говорите "не меняйте заказ", "используйте корректировку"? Если это так, то думаю дискуссия зашла в тупик и лучше отложить ее до выявления проблем на уровне сценариев реальных пользователей.

**Comment by SvetlanaRes** [comment]
> А речь не о зеркальной ситуации, почему она должна быть зеркально? Речь о контроле на основе первичности операций. Заказ, как и Поступление - первичен, я спрашиваю, почему заказ контролировать нужно, а поступление нет.

@Nullarity , согласна...раз "пошла такая пьянка", тогда нужен и этот контроль!!! И тогда вы больше не будете спрашивать, "почему заказ контролировать нужно, а поступление нет"....)

**Comment by SvetlanaRes** [comment]
> @SvetlanaRes и @Linda4ka вы утверждаете, что отсутствие каких-либо сообщений в случае уменьшения реализованного товара является проблемой, в тоже самое время, в к4 изменение заказа вообще не контролируется и никак не блокируется, пользователь может уменьшить кол-во в заказе и ничего система об этом не сообщит. Прокомментируйте пожалуйста описанную ситуацию. Или вы клиентам говорите "не меняйте заказ", "используйте корректировку"? Если это так, то думаю дискуссия зашла в тупик и лучше отложить ее до выявления проблем на уровне сценариев реальных пользователей.

@Nullarity, вы правы! Сценарий работы наш и наших клиентов таков: Заказ покупателя (который не рекомендуется изменять и даже закрыт для редактирования) - Корректировка заказа (при необходимости что-либо изменить, причем с КОНТРОЛЕМ остатка заказанных товаров - остатки по регистру Заказ покупателя)....

На сколько я поняла, механизм "ИЗМЕНИТЬ" заказ покупателя, предлагается как аналог/замена вышеуказанного блока. Но это не совсем так, т.к. остатки по заказу не контролируются.

И получается, что все свелось к осознанности/ответственности пользователя. И если заказали 10 штук, отгрузили 5, а пользователь изменил в заказе 10 на 4, то в результате выявится это при перепроведении реализации (система сообщит, что "не соответствует заказу") и по отчетам неясно, что пойдет.

У нас есть ряд клиентов и производители, и торговцы, у которых на контроле заказов завязаны и взаимоотношения с клиентами, а на корректировках заказа завязан анализ "неудовлетворенного спроса потребителя", что приводит к корректировкам плана производства для покрытия спроса.
В данном контексте имеющаяся логика к5 - не подходит.

**Comment by Nullarity** [comment]
> И тогда вы больше не будете спрашивать, "почему заказ контролировать нужно, а поступление нет

я задаю вопросы чтобы разобраться, а "не больше не спрашивать"

> На сколько я поняла, механизм "ИЗМЕНИТЬ" заказ покупателя, предлагается как аналог/замена вышеуказанного блока. Но это не совсем так, т.к. остатки по заказу не контролируются.

Или можно прочитать так: это ровно тоже самое, за исключением на данный момент контроля остатка.

> У нас есть ряд клиентов и производители, и торговцы, у которых на контроле заказов завязаны и взаимоотношения с клиентами, а на корректировках заказа завязан анализ "неудовлетворенного спроса потребителя", что приводит к корректировкам плана производства для покрытия спроса.
В данном контексте имеющаяся логика к5 - не подходит.

Возможно так и есть, но изменять текущую модель в сторону корректировок пока не планируется, потому что именно от этой модели и хотелось уйти.

**Comment by Linda4ka** [comment]
Очень жаль, Эта модель практична, понятна и удобна. Если в программе есть простые и удобоваримые вещи, от них нельзя отказываться, их надо усовершенствовать!

**Comment by Nullarity** [comment]
> Эта модель практична, понятна и удобна

У меня ровно противоположная статистика.

**Comment by Linda4ka** [comment]
Я бы могла согласиться с вами если бы вы работали здесь, на месте с нашими клиентами напрямую. А так....... Лучше нас эту статистику вряд ли кто знает.

**Comment by Nullarity** [comment]
Механизм о котором вы говорите разрабатывался мной, я очень хорошо отдаю себе отчет в том, почему данный механизм требует пересмотра. Я не утверждаю, что в к4 корректировки это плохо, как и любая фунциональность, у нее есть свои плюсы и минуты. Но для составления сравнительной таблицы, у меня сейчас уйдет масса времени. Вы оперируете клиентами, кому эта схема удобна, но меня не устраивает кол-во таких клиентов, их должно быть на порядок больше. В качестве небольшой поддержки моего решения. посмотрите флагманский ERP2 от 1С, там тоже ушли от такого способа корректировок.

**Comment by SvetlanaRes** [comment]
> Возможно так и есть, но изменять текущую модель в сторону корректировок пока не планируется, потому что именно от этой модели и хотелось уйти.

Ясно. Тогда можно было бы сразу  об этом сказать, чтоб не тратить время на дебаты.
