### ISSUE TITLE
Сообщение об обновлениях 

### ISSUE THREAD

**Issue by SvetlanaRes** [Contabilizare/c5#123]
![image](https://user-images.githubusercontent.com/82224240/121867003-2a6ab200-cd08-11eb-9202-966c3dd7fdaa.png)

![image](https://user-images.githubusercontent.com/82224240/121867291-7b7aa600-cd08-11eb-8b8d-124d761ae19e.png)

1) При нажатии на "Доступны новые обновления" выдает сообщение, которое после закрытия периодически выскакивает, до тех пор пока не перезайдешь в приложение.

2) на самом деле обновлений нет, но ![image](https://user-images.githubusercontent.com/82224240/121867597-c85e7c80-cd08-11eb-8c23-e8c65a407d7a.png) активна.

**Comment by Nullarity** [comment]
а обновление было выполнено штатно?

**Comment by SvetlanaRes** [comment]
"штатно" - это как?
т.к. не получалось через "Доступны новые обновления", что обновила через конфигуратор/поддержка...

**Comment by Nullarity** [comment]
ясно, а точно вся цепочка обновлений выполнена? Попробуй войти еще раз в конфигуратор и выполнить обновление, оно выдаст, что обновлений больше нет?

**Comment by SvetlanaRes** [comment]
![image](https://user-images.githubusercontent.com/82224240/121892074-f2259c80-cd24-11eb-9cf6-85a2f3288374.png)

**Comment by Nullarity** [comment]
ясно, а что написано в поле Настройки / Система / Версия ?

**Comment by SvetlanaRes** [comment]
5.0.14.6

**Comment by Nullarity** [comment]
Проблемку нашел, она возникает именно при ручном обновлении. Буду думать как отключить это сообщение без перезахода в программу
