### ISSUE TITLE
Кассовое перемещение.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#126]
Для чего необходим документ кассовое перемещение? В чем его польза и целесообразность?

**Comment by Nullarity** [comment]
@SvetlanaRes ответь пожалуйста на этот вопрос.

**Comment by Linda4ka** [comment]
А вы сами не можете или не знаете?

**Comment by Nullarity** [comment]
Я считаю не очень правильно требовать от меня ответы на все вопросы. Как и у вас, у меня есть основная работа, и думаю @SvetlanaRes в состоянии ответить на такой вопрос.

**Comment by Linda4ka** [comment]
Если я захочу у нее спросить я это сделаю. Но мне был интересен ваш ответ как разработчика!

**Comment by Nullarity** [comment]
Наши с ней ответы совпадут, я не могу здесь ответить на этот вопрос.

**Comment by SvetlanaRes** [comment]
> А вы сами не можете или не знаете?

@Linda4ka, прошу контролировать свои вопросы и ремарки
