### ISSUE TITLE
Целесообразность документов на закладке Сотрудники

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#127]
Хочу понять и не могу, для чего необходимы следующие документы: Документы об образовании, Виды образования, Учебные заведения и Профессии. Для чего необходимо тратить время для заполнения, на что это влияет, а если и на что не влияет, то зачем эта информация если в личном деле сотрудника есть все необходимые документы и об образовании и учебном заведении, где он учился и т.д

**Comment by Nullarity** [comment]
Это для информации и не обязательны для заполнения.

**Comment by Linda4ka** [comment]
Если не обязательно для заполнение, то нет смысла засорять этими документами пространство. Сбивает с толку.

**Comment by Linda4ka** [comment]
Чем меньше будет отвлекающей информации, не требующей заполнения, тем привлекательнее будет программа

**Comment by Linda4ka** [comment]
Спасибо за понимание!

**Comment by SvetlanaRes** [comment]
Наверняка, данные поля каким-то образом собираются/фильтруются/группируются в какой-то кадровой отчетности? Возможно необязательны для заполнения, но вероятно где-то отображаются. @Nullarity, верно?

**Comment by Nullarity** [comment]
> Документы об образовании, Виды образования, Учебные заведения и Профессии.

По моему в каких-то регламентированных отчетах используются профессии. В целом, данный набор сведений реализован потому что в моей практике он был часто востребован, начиная от элементарной задачи ведения картотеки (просто чтобы в бамажках не искать, а пользоваться (полнотекстовым) поиском) и заканчивая специфичной отчетностью, например формирование списка сотрудников, которым требуется продление лицензии (используются при этом документы об образовании). В данном случае, вопрос не принципиальный, и если вы считаете что эта информация сбивает с толку, можно в будущем предусмотреть возможность ее опциональности.

**Comment by SvetlanaRes** [comment]
> В данном случае, вопрос не принципиальный, и если вы считаете что эта информация сбивает с толку, можно в будущем предусмотреть возможность ее опциональности.

По поводу опциональности у меня спорное отношение. Зачастую, тем самым скрываются поля/блоки, которые пользователь по невнимательности их не находит (даже, если они ему нужны). 
Поэтому данный вопрос предлагаю отложить. На мой взгляд, пользователь тоже должен понимать, что если поле для его учета неактуально - не использует/не заполняет.
