### ISSUE TITLE
Неверный расчёт отгрузки заказа

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#13]
В продолжение #10 : 
После успешной отгрузки и реализации не выполненного заказа в полном количественном объёме, статус отгрузки всего 5%. 
![image](https://user-images.githubusercontent.com/82500510/114987961-7501b680-9e9e-11eb-9f0c-fccaea7b27d2.png)
![image](https://user-images.githubusercontent.com/82500510/114988016-8480ff80-9e9e-11eb-8eb6-085845f474fd.png)

Предполагаю что расчёт процента отгрузки реализуется на базе сравнение сумм заказа и отгрузки (реализации) а не количество единиц. Данное сравнение ведёт к ошибке из за разницы в валюте договора (Евро) и валюте данного заказа (МДЛ) и реализации. 
![image](https://user-images.githubusercontent.com/82500510/114989333-ff96e580-9e9f-11eb-8e60-cc4a202c4b48.png)
Даже при том что заказ записан в МДЛ и Реализация тоже в МДЛ алгоритм умножает "сумму заказа" на курс валюты договора (а не заказа) и сравнивает с суммой реализации умноженную на курс валюты реализации ( то есть МДЛ - 1). 
Считаю что сравнение количеств единиц по каждой позиции будет более корректное и не приведёт к путанице с курсами.

**Comment by Nullarity** [comment]
спасибо за замечание и описание ситуации, поправим. Однако, сам алгоритма расчета, признав дать понимание в деньгах, сколько оплачено и сколько отгружено (колоночки находятся специально рядом). В противном случае, если заказ содержит 1 единицу оборудования (90% от стоимости) и 10  сопутствующих материалов (10% от стоимости), расчет от кол-ва, при проведенной отгрузке только сопутствующего материала, может дать неверное представление. Детальный по-позиционную информацию можно получить в таблице ниже или через отчет https://cont.help/r/SalesOrderItems/

**Comment by TeodorUn** [comment]
> спасибо за замечание и описание ситуации, поправим. Однако, сам алгоритма расчета, призван дать понимание в деньгах, сколько оплачено и сколько отгружено (колоночки находятся специально рядом). В противном случае, если заказ содержит 1 единицу оборудования (90% от стоимости) и 10 сопутствующих материалов (10% от стоимости), расчет от кол-ва, при проведенной отгрузке только сопутствующего материала, может дать неверное представление. Детальную по-позиционную информацию можно получить в таблице ниже или через отчет https://cont.help/r/SalesOrderItems/

Согласен с вами в нужде денежного расчета для статуса Оплаты. Что касается статуса отгрузки, думаю что количественный подход будет уместней.

**Comment by SvetlanaRes** [comment]
> Что касается статуса отгрузки, думаю что количественный подход будет уместней.

Не совсем согласна. Я считаю, что для наглядности и визуального сравнения показатели должны быть одной природы. Тогда и понятен коэффициент соотношения оплаченного и отгруженного (по суммовому значению).
