### ISSUE TITLE
Обновление плана счетов, разыскивается помощь

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#131]
@Linda4ka @SvetlanaRes  мне бы очень сэкономило мне время анализ текущего плана счетов к5 и актуального, с целью выжимки от-туда только нужных нам изменений.

Спасибо!

**Comment by SvetlanaRes** [comment]
@Nullarity, хорошо. Посмотрим...

**Comment by Linda4ka** [comment]
[план счетов сравнение.xlsx](https://github.com/Contabilizare/c5/files/6675598/default.xlsx)

**Comment by Nullarity** [comment]
@Linda4ka спасибо!
Итак, что мы делаем, желтые - удаляем (те, кто будут переходить на к5, будут использовать другие счета вместо старых?), красные - меняем, зеленые - добавляем, все верно?
И еще очень важный момент - рум. язык, все красные и зеленые нужно продублировать нам рум.

**Comment by Linda4ka** [comment]
Пожалуйста. Да, согласно действующему плану счетов счета и субсчета, выделенные желтым, не используются и их можно удалить. Соответственно красные переименовываем, а зеленые добавляем. Здесь все правильно. А вот по поводу румынского варианта- я если успею начать сегодня будет хорошо, но рассчитывайте где-то на понедельник.Думаю до конца понедельника я сделаю и скину.

**Comment by Nullarity** [comment]
Принял. На счет сроков - не срочно, эта задача войдет в следующий релиз.

**Comment by Linda4ka** [comment]
Хорошо. Добавить в этот же документ или сделать новый, с указанием счета и варианта на румынском?

**Comment by Nullarity** [comment]
Лучше в тот же документ, вы удобно его сделали, как я и хотел. Чтобы оба языка рядом были, внутри в программе исходное название идет на рум, и уже потом мы в отдельном поле держим рус.

**Comment by Linda4ka** [comment]
Хорошо, на следующей неделе я все сделаю и прикреплю в этот же вопрос

**Comment by Linda4ka** [comment]
[план счетов сравнение.xlsx](https://github.com/Contabilizare/c5/files/6686781/default.xlsx)
 В данном документе сравнительная часть и вариант на румынском языке.

**Comment by Nullarity** [comment]
@SvetlanaRes  @Linda4ka  В документе отмечено, что счета 21721 (Товары в розничной торговле (количественный)) и 21722 (Товары в розничной торговле (общими суммами)) отмечены к удалению. Я правильно понимаю, что розница общими суммами теперь ведется как-то иначе?

**Comment by Nullarity** [comment]
Еще вопрос, такие счета как написано удалить счет 22611 Дебиторская задолженность подотчетных лиц (в леях) и 22612 Дебиторская задолженность подотчетных лиц (в валюте) точно удалять?

**Comment by Linda4ka** [comment]
Добрый день! Давайте определяться по данным вопросам. Значит по первому вопросу: я просмотрела план счетов в 4.0 и увидела что счет 21721 Товары в розничной торговле общими суммами присутствует, а 21722 нет вообще. Можно предположить, что 21721 требуется определенным клиентам. Предположительно, при большой необходимости, его можно оставить.
По второму вопросу: счета 22611 и 22612 в плане счетов в 4.0 отсутствуют. Могу предположить, что поскольку все расчеты на территории Молдовы, связанные с подотчетными лицами, производятся в национальной валюте, то в данных субсчетах нет смысла. Даже выдача командировочных, для поездки за границу производится в леях и валюта покупается непосредственно перед отъездом самим подотчетником. Так что, я думаю логично будет, если мы будем следовать действующему и утвержденному плану счетов. А если какому-то клиенту понадобится тот или иной субсчет, решать этот вопрос в личном порядке. Всего все равно не предусмотрим.

**Comment by Nullarity** [comment]
Понятно, спасибо, еще такой вопрос, у вас в файлике рум. символы нормально отображаются? У меня почему-то вот так:
![image](https://user-images.githubusercontent.com/28710693/123281224-7fac7d80-d4d7-11eb-9aff-2a65b7d12ef2.png)
Не знаю, это у меня локально что-то не так, или источник такой.

**Comment by Linda4ka** [comment]
Ой, это я наверное не досмотрела и не исправила. Я еще раз перепроверю и прикреплю файл исправленный. Извините, когда много символов, рябит в глазах.

**Comment by Linda4ka** [comment]
Вроде все проверила и исправила.
[план счетов сравнение.xlsx](https://github.com/Contabilizare/c5/files/6713819/default.xlsx)

**Comment by Nullarity** [comment]
В плане счетов помечены к удалению такие счета как Автопокрышки в эксплуатации, Аккумуляторы на складе и другое (в группе счетов 262). Я правильно понимаю, что учет шин и аккумуляторов планируется организовать не задействуя эти счета?

**Comment by Nullarity** [comment]
Все, @SvetlanaRes  помогла разобраться, вопрос больше не актуален.
