### ISSUE TITLE
Дата оплаты в документе "Оплата покупателя"

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#14]
При создании документа оплаты дата оплаты в табельной части заполняется неверно. В списке документов оплаты эта дата не отображается.
![image](https://user-images.githubusercontent.com/82500510/114996219-4c31ef00-9ea7-11eb-92b9-4e6b92e4a9d8.png)
Данная ошибка появляется при способе оплаты "банковский перевод"

**Comment by Nullarity** [comment]
Подскажите пожалуйста, какая дата оплаты у вас указана в самом заказе? Дело в том, что отмеченная на картинке дата, это не дата совершения оплаты, а крайний срок оплаты, дальше которого долг будет считаться просроченным. Если в заказе указано, что оплата по факту (а отгрузки еще не было, или в отгрузке не была указана дата оплаты), тогда и дата оплаты бессрочна, а значение 31.12.3999 такое ее представление.

**Comment by TeodorUn** [comment]
Спасибо, понял суть. Предложение переименовать колонку в Срок оплаты. Думаю будет понятней смысл содержимой даты.
