### ISSUE TITLE
Праздники 2021

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#144]
Коллеги, подмогните, ниже напишите пожалуйста календарь официальных праздников для начальной базы.
Спасибо!

**Comment by Linda4ka** [comment]
Добрый день! На 2021 год, согласно законодательству, установлен следующий список праздничных дней:
1 Января Новый год
7 и 8 января Празднование Рождества Христова
1 марта Мэрцишор
8 марта Международный женский день
1 мая Международный день солидарности трудящихся
9 мая День Победы
27 августа День Независимости
31 августа Лимба ноастрэ
25 декабря Празднование рождества по старому стилю(Католическое Рождество)
Переходящие праздники: Пасха (2021) - 2 мая (воскресенье) - 3 мая выходной
                                          Поминальный день 9 мая (воскресенье) - 10 мая выходной
День города для каждого населенного пункта свой. Кишинев 14 октября выходной.
