### ISSUE TITLE
Неверное описание услуг в реализации

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#15]
При создании документа реализации описание услуг заполняется неверно из заказа покупателя.
![image](https://user-images.githubusercontent.com/82500510/115013325-8c01d200-9eb9-11eb-8588-ad4901c31961.png)
![image](https://user-images.githubusercontent.com/82500510/115013384-a2a82900-9eb9-11eb-8abc-8b29cb00e106.png)

**Comment by Nullarity** [comment]
спасибо, поправим
