### ISSUE TITLE
Проблема после обновления!

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#155]
Добрый день. Скачала сегодня конфигурацию 5.0 с сайта и обновила уже существующую и после обновления выдало ошибку следующего характера.
![image](https://user-images.githubusercontent.com/84187165/123751304-4487c100-d8c0-11eb-920a-d6067bcda018.png)
Что с этим делать? Работать в программе нет возможности, т.к. после перезапуска выходит  то же самое.

**Comment by Linda4ka** [comment]
Позже попробовала зайти как системный администратор и запустила обновить. Смогла работать.

**Comment by Nullarity** [comment]
По идее, сообщение об этом и говорит.
