### ISSUE TITLE
Пожелания по заполнению Календаря.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#156]
По возможности, рассмотрите вариант  того, чтобы после внесения праздничных дней и записи графика, в календаре не проставлялись праздничные дни 8-ми. Очень неудобно корректировать вручную. А еще лучше, чтобы и предпраздничные дни проставлялись 7-ми, при 8-ми часовом рабочем графике. Спасибо!

**Comment by Nullarity** [comment]
> Очень неудобно корректировать вручную

Подскажите пожалуйста, зачем вам приходится корректировать график?

**Comment by Linda4ka** [comment]
Ну, по логике, табель заполняется на основании календаря. Если в календаре на выходных днях проставлены 8, то и считать он будет неправильно. Или я чего-то недопонимаю?

**Comment by Nullarity** [comment]
Видимо, я что-то не понимаю. В проблеме #46 я написал, цитирую:

> Да, вы совершенно правы с т.з. графика как основы для начисления ЗП. Но в к5 сделано чуть иначе. Графики работ и праздники теперь не завязаны друг на друге и могут заполняться раздельно. В графике задается только норма рабочего времени, а непосредственно определение кол-ва отработанных дней/часов выполняется в момент начисления зарплаты.
Так сделано по ряду причин:

> Не нужно помнить последовательность ввода Праздники / потом Графики
Если графиков много, не нужно их перезаполнять в случае сдвига или объединения праздников
То есть хотелось достичь такого, чтобы пользователь в "два клика" создавал нужные ему графики, вел праздники по мере поступления информации, а все остальное делала программа.

Мой ответ был неполным или описанное поведение не соответствует работе программы?

**Comment by Linda4ka** [comment]
@Nullarity , дело в том, что я пытаюсь предусмотреть возникновение локальных проблем с клиентами. Если учесть тот факт, что я работаю в этой программе с самого начала, как будут работать новые клиенты, или те, кто захочет перейти на эту программу из нынешних, я прохожу ее пошагово, как это будут делать все, то и возникает ряд вот таких вопросов. Это мы имеем возможность тет-а-тет, без нервов и особого стресса вести дискуссию о целесообразности использования того или иного блока, документа или отчета, а с клиентами это совершенно другое. Есть очень умные и уверенные в себе клиенты, которым можно что-то доказать, а есть не очень умные и очень самоуверенные, которым не докажешь ничего, даже осознавая что он ничего не понимает. Я имею в виду следующий факт: При пошаговом заполнении программы под себя, назовем это так, клиент залезит везде. Естественно, при заполнении графиков работ, заход будет на все закладки, существующие в программе. И естественно, привыкшие работать в 4.0, они естественным образом будут заполнять этот злосчастный, как вы говорите, не имеющий отношения к табелю, календарь. Сразу же возникнет ряд вопросов, которые будут превращены в звонки, недопонимание, крики и лишний стресс, для нас. Объяснить специфику работы получится не всем,, в связи с вышеуказанными факторами. Почти все пользователи, и я не исключение, понимают, что если что-то есть и с этим мы уже плотно работали и это хорошо знаем, значит оно должно быть заполнено и работать как часы. Пользователь не может и не должен знать что имел в виду разработчик, чем мотивировался и о чем думал. Он знает, если есть, значит надо. А когда пользователь видит неправильно заполненное что-либо. ступор, звонок и истерика, о неправильности работы программы. Поэтому, с моей стороны и поступают иногда глупые, иногда дотошные, а иногда раздражающие вопросы. Я выворачиваю эту программу таким образом, чтобы понять все мелочи. Мои определенные просьбы, касаемо работы какого-либо документа это не моя прихоть, это попытка облегчить работу всем, кто в этой программе будет работать и кому потом выслушивать все недовольства и истерики клиентов. Поэтому, если этот календарь не участвует ф формировании табеля и не влияет на работу всей программы, возможно его стоит сделать неактивным, без возможности заполнения и ручной корректировки. Или же сделать его заполнение правильным. Я пытаюсь быть рациональной и логичной. Если в программе что-то есть оно должно работать и заполняться правильно, а если оно есть, но нигде не работает и не участвует - нет смысла  в его существовании. Спасибо за понимание.

**Comment by Nullarity** [comment]
Спасибо что поделились трудностями бытия! Но у меня очень большая просьба ответить на мой предыдущий вопрос. К сожалению, то, что вы написали, не помогает мне понять, вы нашли ошибку в программе, или мой ответ (который я давал ранее на похожий вопрос), для вас был непонятен. В любом из вариантов, я мог бы предпринять меры.

**Comment by Linda4ka** [comment]
Хорошо! Я не поняла наличие календаря, его заполнение и возможность ручной корректировки если он не имеет никакого влияния на документы.

**Comment by Nullarity** [comment]
В свое время, в к4 в плане графиков работ и праздников, мной была допущена методологическая ошибка, в к5 она исправлена. Одну из причин я описал выше, есть еще одна, касающаяся предпраздничных дней.

**Comment by Nullarity** [comment]
> возможность ручной корректировки если он не имеет никакого влияния на документы.

Имеет существенное влияние. Если вы в графике, вручную, в праздничный день поставите 0, это будет означать, что сотрудник, по данному графику, в этот день работать не должен. Акцентирую внимание - **по графику** он не должен работать, а не потому что в этот день праздник. Таким образом, если в этот день выпадает праздник, то предыдущий день его работы не является предпраздничным и ему не положено уменьшение рабочего дня на 1 час (сама функциональность еще в разработке, но она опирается на правильную архитектуру данных.

**Comment by Linda4ka** [comment]
Я вот все пытаюсь переварить и это мне удается все меньше и меньше. Ладно,давайте вопрос поставим следующим образом, чтоб я понимала правильный ли ход моей мысли. У сотрудника 8-ми часовой график работы, В начале года мы записали все праздники. Получается, что в календарь лезть не надо и заполнять его тоже, а если мы заполнили,  то ничего корректировать там не надо? Если календарь не заполнен, табель будет в любом случае заполнятся правильно, автоматически проставляя 7 часов(предпраздничный день), т.к мы должны выйти на кол-во рабочих часов, согласно Производственного календаря  и исключать праздничные дни. Правильно?

**Comment by Linda4ka** [comment]
Или уже в табеле необходимо корректировать вручную часы?

**Comment by Nullarity** [comment]
> Получается, что в календарь лезть не надо и заполнять его тоже, а если мы заполнили, то ничего корректировать там не надо?

Да, не нужно. Корректировать график нужно в редких случаях, когда график формируется на месяц например, или на вахту, т.е. когда мы на целый год не знаем в точности, какие дни будут рабочими. И к праздникам это не имеет отношение. Праздники - они государственные, если день праздничный - он праздничный для всех, и если у вас на предприятии 5 графиков, то методологически неправильно заходить в каждый и пере-заполнять. Потому что во-первых это неудобно, во-вторых контр-интуитивно для пользователей, привыкших работать с более удобными программами.
В табеле тоже корректировать ничего корректировать не нужно.

**Comment by Linda4ka** [comment]
Т.е пользователь может быть спокоен по поводу правильности заполнения табеля как по дням, так и соответственно по часам?

**Comment by Nullarity** [comment]
Да, в этом и вся суть - купил программу, установил начальную базу, принял сотрудника, выбрал уже готовую пятидневку, начислил - выплатил, все! Табель - заполнился сам, праздники - учлись сами, предпраздничные тоже (в след.релизе). Перенести праздник в этом месяце? Зашел в справочник праздников, задал праздник, нажал ОК и все, больше ничего перезаполнять не нужно.

**Comment by Nullarity** [comment]
Так программа должна работать по дизайну. Если программа работает не так - пишите, будем исправлять.

**Comment by Linda4ka** [comment]
Аллилуйя, разобрались! Спасибо за конструктив и терпение!

**Comment by Linda4ka** [comment]
@Nullarity, добрый день! Сегодня заполнила табель на январь, согласно вчерашней оговоренной схеме заполнения( без календаря). Действительно, праздничные дни были пустыми, а вот 6 января вместо положеной 7 проставился 8. Общее кол-во рабочих часов вышло 144 (за январь), а согласно балансу рабочего времени на 2021 год, должно быть 143 часа.
![image](https://user-images.githubusercontent.com/84187165/124070151-07e5d200-da46-11eb-8be3-875d115c7428.png)
Это надо исправить. Предпраздничные должны проставляться 7, для 8-ми часового рабочего дня.Спасибо!

**Comment by Nullarity** [comment]
> Это надо исправить. Предпраздничные должны проставляться 7, для 8-ми часового рабочего дня

Эту задачу я уже регистрировал #65

**Comment by Linda4ka** [comment]
Было бы хорошо, если бы это исправление произошло чем пораньше. Все что касается зарплаты-важно! Спасибо!
