### ISSUE TITLE
Вопрос по ДОКУМЕНТАМ

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#157]
Подскажите, новая возможность работы с файлами и документами, она обязательна для ведения и заполнения или это исключительно по усмотрению пользователя?

**Comment by Nullarity** [comment]
В программе нет ни одного обязательного механизма. Программу можно использовать в режиме "Только просмотр" (например, менеджеры, руководители). Таким образом, ответ нет, не обязательно.

**Comment by Linda4ka** [comment]
Спасибо за ответ!
