### ISSUE TITLE
Печать счета на румынском и английском

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#158]
Решила просмотреть как выходить на печать счет покупателя на румынском и английском, немного недопоняла:
![image](https://user-images.githubusercontent.com/84187165/124090956-02948180-da5e-11eb-9c5a-ba62c20f2cb3.png)
![image](https://user-images.githubusercontent.com/84187165/124091290-57d09300-da5e-11eb-9970-f528d03d5524.png)
В моем понимании печатная форма на румынском и английском должна быть полностью на выбранном языке или я не права? Или может я что-то сделала не корректно?

**Comment by Nullarity** [comment]
К сожалению есть какая-то проблема я языками при сборке конфигурации для релиза, мне нужно время что бы разобраться почему так.

**Comment by Linda4ka** [comment]
Хорошо, будем ждать!
