### ISSUE TITLE
Внесение количества иждивенцев

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#159]
Большая просьба, если можно, необходимо внести изменения в Освобождения. Программа не дает возможность вносить больше одного иждивенца, если их несколько, и это проблема. Возможность рассчитать зарплату правильно падает до нуля.
![image](https://user-images.githubusercontent.com/84187165/124111687-38436580-da72-11eb-9c74-a0bcfc1e5623.png)
Спасибо!

**Comment by Nullarity** [comment]
Извините за задержку с ответом. Для того, чтобы задать сотруднику освобождения для двух и более иждивенцев, необходимо создать отдельный вид освобождения, и прямо в тексте, на скольких иждивенцев создается освобождение.

**Comment by Linda4ka** [comment]
Ок, я попробую и напишу что у меня получилось.

**Comment by Linda4ka** [comment]
Если я правильно поняла, то при создании вида освобождения мы указываем в коде количество и общую сумму освобождения, согласно количеству.

**Comment by Nullarity** [comment]
Да, совершенно верно.

**Comment by Linda4ka** [comment]
Хорошо, спасибо!
