### ISSUE TITLE
Номер документа оплаты не отображается верно

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#16]
Если оплата покупателя производится банковским переводом то номер документа оплаты "000001" заменяется наименованием "Справка/Чек".
При этом ссылка на документ оплаты работает нормально.
![image](https://user-images.githubusercontent.com/82500510/115014140-9b354f80-9eba-11eb-8e2e-3f661d781df8.png)
![image](https://user-images.githubusercontent.com/82500510/115014206-b0aa7980-9eba-11eb-93bc-c2418e4393eb.png)
![image](https://user-images.githubusercontent.com/82500510/115014484-0c750280-9ebb-11eb-9e44-7a4d06fa3c6b.png)

**Comment by Nullarity** [comment]
Да, это по дизайну, если указан внешний номер (предполагается что в то поле будет введен и способ оплаты, а его идентификационный номер, с каким-то префиксом), то как правило, пользователю удобней исходить из этого реально существующего номера, а не внутреннего. Также например и в отчетах. Информация, которая выводится в отчете, уже готова к тому, чтобы найти источник из папки бумаг (потому что номер показывается сразу, и входить в исходный документ в базе не требуется).

Если это у вас вызывает трудности, опишите пожалуйста ситуацию, когда это доставляет практическое неудобство.
Спасибо!
