### ISSUE TITLE
Первостепенные задачи по зарплате.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#161]
@Nullarity, большая просьба, рассмотрите возможность, в кротчайшие сроки, внести все исправления, касаемо блока Зарплата, кадры. Хотелось бы уже полностью пройти весь процесс, в полном объеме. Этот блок очень важен, а я никак не могу пройти его с самого начала, моделируя различные ситуации и варианты. Я понимаю вашу загруженность, но если есть возможность это ускорить, буду признательна. Спасибо за понимание.

**Comment by Nullarity** [comment]
Работаю над этим.
