### ISSUE TITLE
Как изменилась личная карточка после последних изменений в ЗП?

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#165]
Подскажите пожалуйста, как изменилась личная карточка, в частности колонки 8.8 и 8.9, в связи с объединением пенсионного и соц.фонда.
Спасибо!

**Comment by Linda4ka** [comment]
[anexa 8_642 ru (2) Личная карточка.docx](https://github.com/Contabilizare/c5/files/6762355/anexa.8_642.ru.2.docx)

**Comment by Linda4ka** [comment]
Данная карточка утверждена на основании следующего:
Республика Молдова
ПРАВИТЕЛЬСТВО
ПОСТАНОВЛЕНИЕ № 642
от 26-08-2020
о внесении изменений в некоторые
постановления Правительства
Опубликован : 28-08-2020 в Monitorul Oficial № 221-225 статья № 768
На основании части (3) статьи XXI Закона № 60/2020 об учреждении некоторых мер поддержки предпринимательской деятельности и о внесении изменений в некоторые нормативные акты (Официальный монитор Республики Молдова, 2020 г., № 108-109, ст. 186), с последующими изменениями, Правительство ПОСТАНОВЛЯЕТ:

1. В Положение об удержании подоходного налога с заработной платы и других выплат, осуществленных работодателем в пользу работника, а также выплат в пользу физических лиц, не осуществляющих предпринимательскую деятельность, предоставляющих услуги и/или выполняющих работы, утвержденное Постановлением Правительства № 697/2014 (Официальный монитор Республики Молдова, 2014 г., № 256-260, ст. 745), с последующими изменениями, внести следующие изменения:

1) из пункта 36 слова «и индивидуальных взносов обязательного государственного социального страхования» исключить;

2) в пункте 481 текст «– K₁» из формулы и текст «K1 – размер отчислений в пенсионный фонд, деленный на 100;» исключить;

3) приложение № 8 изложить в следующей редакции:  

 

​приложение № 8, которое я отправила раннее.

**Comment by Nullarity** [comment]
Спасибо! Если в кратце, в сравнении с прошлым годом, просто убрали две колонки касательно соцфонда, верно?

**Comment by Linda4ka** [comment]
Как-то так!
