### ISSUE TITLE
План счетов после обновления.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#168]
Добрый день! Обновила сегодня 5.0 и в план счетов сейчас выглядит следующим образом:
![image](https://user-images.githubusercontent.com/84187165/124600865-dc148300-de6f-11eb-8276-df76433f40c6.png)
Может это можно как-то скрыть? Подскажите как это исправить! Спасибо!

**Comment by Nullarity** [comment]
День добрый, это штатное поведение. При удалении в программе неиспользуемых счетов, в информационной базе такие счета помечаются на удаление. Вы можете запустить стандартную процедуру удаления помеченных объектов у удалить незадействованные счета.

**Comment by Linda4ka** [comment]
Ок, спасибо!
