### ISSUE TITLE
Несоответствие в личной карточке

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#169]
Получилось небольшое несоответствие в нумерации
![image](https://user-images.githubusercontent.com/84187165/124601692-ceabc880-de70-11eb-9165-c79717960e0a.png)

**Comment by Nullarity** [comment]
Да, действительно, спасибо! А подскажите, в том файлике, что вы мне #165 прикрепили, 8 пункт пропущен?

**Comment by Linda4ka** [comment]
Ну во всяком случае там пункта 8 нет. Да и в методологии заполнения тоже.

**Comment by Nullarity** [comment]
Прикрепите пожалуйста румынский вариант личной карточки, чтобы сделать все в согласии с образцами.
Спасибо!

**Comment by Linda4ka** [comment]
[anexa 8_697 на румынском языке.docx](https://github.com/Contabilizare/c5/files/6774518/anexa.8_697.docx)
Личная карточка на румынском языке.
