### ISSUE TITLE
После обновления не возможно создать заказ поставщику.

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#171]
После обновления не возможно создать заказ поставщику.
![image](https://user-images.githubusercontent.com/82500510/124869317-b3a09c00-dfc9-11eb-8727-f5f007396b3a.png)

**Comment by Linda4ka** [comment]
Не понятно, у нас все нормально. Создали,сохранили и провели?!

**Comment by TeodorUn** [comment]
Не могу провести, то есть сохранить ни одним пользователем.

**Comment by Linda4ka** [comment]
Странно, я сделала без проблем.

**Comment by Nullarity** [comment]
@TeodorUn приложите пожалуйста отчет об ошибке (вам нужно кликнуть на ссылку Сформировать отчет об ошибке, и программа сформирует zip-файл).
Спасибо!

**Comment by TeodorUn** [comment]
[Ошибка_20210708084743.zip](https://github.com/Contabilizare/c5/files/6784695/_20210708084743.zip)

**Comment by Nullarity** [comment]
Подскажите пожалуйста, у вас заказ без стоимости, в этом случае не получится оформить поступление на основании такого заказа. Конечно то, что программа выдает некрасивую ошибку плохо, будем исправлять, но какую практическую операцию вы выполняете, может мы сможем что-то подсказать или улучшить?

**Comment by Linda4ka** [comment]
А можно уточнить, если делать заказ с нулевой стоимостью, как тогда проводить оплату и приход?

**Comment by Linda4ka** [comment]
Мне кажется что это некорректно

**Comment by Nullarity** [comment]
Согласен, это с т.з. обычного учета, кажется некорректным. Но с программной т.з. можно сделать допущение, если оно не противоречит какой-то серьезной концепции. В данном случае, кажется не сложным дать возможность вводить такие заказы и поступления на их основании (допустим мы используем софт для кол-го учета).

**Comment by Linda4ka** [comment]
Написала в 173

**Comment by TeodorUn** [comment]
до обновления вроде можно было делать заказ с нулевой стоимостю.
практическое применение есть. так как цены в данный момент меняются часто, мы формируем заказ, отправляем его, получаем цены на данную партию и толко тогда подверждаем заказ и сумму.

Спасибо за ответ.

**Comment by Nullarity** [comment]
@TeodorUn Эта задача войдет в 17 релиз, ориентировочно 19 июля выпуск, пойдет?

**Comment by Nullarity** [comment]
Вошло в 5.0.16.2
