### ISSUE TITLE
Позволять проводить заказы поставщикам с нулевой стоимостью

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#174]
Основано на #171

**Comment by Linda4ka** [comment]
@Nullarity , простите что вмешиваюсь, но я не считаю это ошибкой. Если следовать логике как может быть заказ поставщику без суммы. Как провести оплату, как оприходовать, полученный товар? Такой заказ, без сумм, может быть только если заказ происходит между своими складами, и то вопрос! Если я неправа скажите!

**Comment by Nullarity** [comment]
> простите что вмешиваюсь

Не прощу, мы здесь все как раз для того, чтобы "вмешиваться" ;-)
По всей строгости вы правы, но нельзя пользователю запрещать ввод заказа если он допустим еще не знает цен, а только собирает заказ. При этом, он хочет его видеть проведенным (чтобы в отчетах видеть сводку), что имеет практический смысл. Я не опираюсь тут на практически опыт, только домыслы, но мне кажется такое допущение не идет в сильный разрез с системой.

**Comment by Linda4ka** [comment]
тот факт, что клиент может не знать цен и делать заказ на товар или услугу, звучит странно. А может пользователь просто неправильно заполнил форму заказа, а мы уже пытаемся изобрести велосипед))))

**Comment by Nullarity** [comment]
У меня с заказами не было такого опыта, но вот был такой: заказывают продукты в производственную столовую, упаковочный лист попадает кладовщику и он вводит поступление там на месте, а накладная (с ценами) идет переводчику на перевод, и только потом попадает в бухию (в другом городе). Так вот кладовщик проводит поступление с 0 ценами (и сейчас в к5 это позволено), а потом этот документ уже дополняет ценами бухгалтер. Тут есть много "но" конечно, напрашивается ордерная складная система, но пока как есть.

**Comment by Linda4ka** [comment]
Ну у нас так учет не ведется, никогда с таким не сталкивалась и даже не слышала чтобы такие ситуации случались. Тут я тоже ничего не могу сказать. Но считаю что торопиться не стоит. Может лучше как-то этот вопрос изучить, чтоб не создавать лишние проблемы при дальнейшей работе. Решать конечно вам!
