### ISSUE TITLE
Вопрос по заказу поставщикам без суммы.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#179]
@Nullarity, добрый день. Загрузила обновление, начала тестировать и у меня вопрос по заказу поставщику:
![image](https://user-images.githubusercontent.com/84187165/125042269-51679a00-e0a2-11eb-8ee7-8d3fb61b791d.png)
В заказе от 31.05.2021 был заказ, оплата и отгрузка, поэтому проставленные галочки понятны, а вот заказ от 09.07.2021 - там только заказ услуг, без суммы. Почему галочки об оплате и отгрузке проставились автоматически? Фактически был только заказ, а получается что и заказ, и оплата, и отгрузка. Непонятно!

**Comment by Nullarity** [comment]
К сожалению, при нулевой сумме заказа я не знаю как рассчитывать процент оплаты и отгрузки. Предложите свой вариант расчета пожалуйста.

**Comment by Linda4ka** [comment]
Может его стоит вовсе убрать, чтоб не было путаницы? Ведь при этом нет ни оплаты, ни отгрузки.

**Comment by Nullarity** [comment]
Да, можно и так. А если будет отгрузка предположим (что-то типа внутреннего перемещения), отсутствие галочки будет не будет конфузить?

**Comment by Linda4ka** [comment]
Ну вообще-то внутреннее перемещение здесь быть не должно, мне так кажется. Оно должно быть на вкладке Склад. Обычно внутреннее перемещение относится к складам.

**Comment by Nullarity** [comment]
Вы не ответили на мой вопрос. Если нужны сценарии, когда товар может придти без цены, скажите, я напишу.

**Comment by Linda4ka** [comment]
Только при внутреннем перемещении внутри структуры фирмы. Ну или если кто-то в благотворительных целях делает подарки. Больше никак.

**Comment by Nullarity** [comment]
Что бы принять решение по проблеме, ответьте пожалуйста на мой вопрос.

**Comment by Nullarity** [comment]
В общем чтобы не было вопросов, будем в таких ситуациях ничего не выводить в этих колонках, при любых комбинация ввода связанных в таких случаях, документов.
