### ISSUE TITLE
Не работает иерархия в Подборе товаров

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#18]
Не работает иерархия в Подборе товаров. 
![image](https://user-images.githubusercontent.com/82500510/115225822-34f93880-a117-11eb-8574-d01f6d53a942.png)

**Comment by SvetlanaRes** [comment]
В списке подбора сделайте правый клик мыши и из выпавшего контекстного меню выберите "Иерархический список" 

![1](https://user-images.githubusercontent.com/82224240/115269748-486ec880-a144-11eb-8a02-79306d081541.jpg)

**Comment by TeodorUn** [comment]
> В списке подбора сделайте правый клик мыши и из выпавшего контекстного меню выберите "Иерархический список"
> 
> ![1](https://user-images.githubusercontent.com/82224240/115269748-486ec880-a144-11eb-8a02-79306d081541.jpg)

Спасибо большое
