### ISSUE TITLE
Путевые листы???

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#182]
Добрый день! Сижу читаю на cont.help информацию по путевым листам - вроде бы все понятно, но как дошла до заполнения самого путевого листа, поняла что ничего не поняла.
1. Как правильно заполняется часть, отмеченная синим
![image](https://user-images.githubusercontent.com/84187165/125897961-4c76fd68-07bb-456c-a720-e1304239ba80.png)
2. Почему автоматически не заполнилась инвентаризация в документе, хотя, если я правильно поняла, после включения она должна заполняться
![image](https://user-images.githubusercontent.com/84187165/125898117-5eed2f91-7a98-401c-a6ef-29acf2ea7292.png)
! Списание Бензина было произведено
3. Почему не могу создать путевой лист на основании Списания?
Объясните мне, а то либо я чего-то не понимаю, либо делаю совсем не то что нужно. Спасибо!

**Comment by Linda4ka** [comment]
И где можно найти отчеты, указанные в описании Путевых листов:Работа автотранспорта,Работа автотранспорта по видам работ,Сводная ведомость по учету топлива?
Я их найти не могу. Может смотрю не туда?!

**Comment by Nullarity** [comment]
> Как правильно заполняется часть, отмеченная синим

это поправки к работе машин и оборудования в зависимости от климатических условий, у меня под рукой нет инструкций к заполнению, но специалисты, занимающиеся расчетом нормативов будут знать что туда вводить.

На оставшиеся вопросы не могу ответить, перефразируйте их пожалуйста с описанием сценария и что в этом сценарии не удается выполнить с помощью программы.

**Comment by Nullarity** [comment]
> И где можно найти отчеты, указанные в описании Путевых листов:Работа автотранспорта,Работа автотранспорта по видам работ,Сводная ведомость по учету топлива?
> Я их найти не могу. Может смотрю не туда?!

Вы туда смотрите, этих отчетов действительно нет, буду разбираться, спасибо!

**Comment by Linda4ka** [comment]
Инвентаризация топлива при включении должна заполняться автоматически? Если да, то она автоматически у меня не заполнилась.А внести данные вручную тоже не получилось. Как должно это работать и как правильно заполнять?

**Comment by Nullarity** [comment]
У вас задан вид топлива и объем бака для марки автомобиля?

**Comment by Linda4ka** [comment]
А где их задавать? Я просмотрела, но в справочники автомобили, при создании нового нет этих данных и в ОС тоже нет. Может я не там смотрю? Подскажите!

**Comment by Linda4ka** [comment]
Все, я нашла куда тыкнуть!!! Но скажу я вам, очень это все не очень. Сложно, запутано и долго!

**Comment by Linda4ka** [comment]
Нельзя ли всю эту информацию перенести в ОС?

**Comment by Nullarity** [comment]
Уточните пожалуйста, что не очень, что сложно и что запутанно. В справке к путевым листам практически первым пунктом сказано про автомобили, в твою очередь, в программе нельзя создать автомобиль без выбора его марки.
Внести информацию о расходе топлива или гаражный номер в справочник ОС и переделать после этого всю подсистему, наверное можно, но хотелось бы вначале понять зачем.

**Comment by Linda4ka** [comment]
Честно говоря, мне в голову не пришло, что при создании марки автомобиля в обязательном порядке необходимо  указывать объем бака, чтобы программа смогла двигаться дальше. Просто всегда говорилось, что в программе нет ничего обязательного, а оказывается что есть. Значит необходимо сделать так, чтоб без заполнения этих данных сохранить документ Марка автомобиля, было бы невозможно. И переделывать ничего не нужно!)))

**Comment by Nullarity** [comment]
Это ошибка, поле должно быть обязательным для заполнения, спасибо!
