### ISSUE TITLE
Проблема с вычислением остатка на складе при резервации товаров

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#188]
Товар 
![image](https://user-images.githubusercontent.com/82500510/126606338-13007166-f090-40d9-859a-0c01a1dd88f8.png)

Его характеристики
![image](https://user-images.githubusercontent.com/82500510/126606426-09f76c90-da9e-4230-b648-b57c5c4a9800.png)
![image](https://user-images.githubusercontent.com/82500510/126606459-28b0f275-d8ff-497c-b5c1-e111cbff870e.png)

**Comment by TeodorUn** [comment]
Update
Ошибка касается даже тех товаров что не были  резервированы
Товар
![image](https://user-images.githubusercontent.com/82500510/126607223-06fa62aa-602c-4071-8708-825ea16f25a5.png)
Характеристики
![image](https://user-images.githubusercontent.com/82500510/126607309-2b4cabf9-7457-400b-a063-a4323ca2f2d7.png)

**Comment by Nullarity** [comment]
Здравствуйте, спасибо за информацию!
Проблема решена в выпущенной сегодня версии 5.0.16.3.
