### ISSUE TITLE
Ошибка при поступлении товаров

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#189]
![image](https://user-images.githubusercontent.com/82500510/126618764-cc7167e7-680f-4143-a3ba-005f9bc1b5b8.png)
![image](https://user-images.githubusercontent.com/82500510/126618874-fd9f4bd6-cefa-47aa-b628-3a7f079bdb46.png)
![image](https://user-images.githubusercontent.com/82500510/126619112-d0418b6c-d5b9-4c19-85dc-0ca69a320465.png)
Получается я не могу получить другой товар кроме того что был в заказе если был оформлен ЗАКАЗ Поставшику.

**Comment by Linda4ka** [comment]
Добрый день! Извините, что вмешиваюсь, но это логично. Если вы делаете приход на основании Заказа Поставщику, то естественно вы что заказали, то и должны получить. Некорректно сделав Заказ на одно, получить и оприходовать другое на основании Заказа.

**Comment by Nullarity** [comment]
> Получается я не могу получить другой товар кроме того что был в заказе если был оформлен ЗАКАЗ Поставшику.

Совершенно верно, обычно в этом и заключается суть взаимоотношений по заказам и контроль их исполнения. Если поставщик заменяет товар с предварительным с вашей стороны согласованием, тогда имеет смысл сделать такую замену в самом заказе.
