### ISSUE TITLE
> Исправительный релиз опубликован. После обновления, установите пожалуйста для вашего пользователя право просмотра/редактирования свойств (при следующем создании пользователя с право просмотра контрагентов, данное право будет назначаться автоматически)

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#19]
> Исправительный релиз опубликован. После обновления, установите пожалуйста для вашего пользователя право просмотра/редактирования свойств (при следующем создании пользователя с право просмотра контрагентов, данное право будет назначаться автоматически)

поставил  права просмотра/редактирования свойств
![image](https://user-images.githubusercontent.com/82500510/115669525-0666a200-a351-11eb-9460-c22b6645a1e3.png)

другая ошибка появилась
![image](https://user-images.githubusercontent.com/82500510/115669615-2302da00-a351-11eb-9426-9fe1d2bd9598.png)

_Originally posted by @TeodorUn in https://github.com/Contabilizare/c5/issues/7#issuecomment-824590687_

**Comment by Nullarity** [comment]
Подскажите пожалуйста, вы под каким профилем устанавливаете права этому пользователю, под пользователем с правами администратора?

**Comment by Nullarity** [comment]
нужна ваша помощь в воспроизведении проблемы, у меня не получилось.

**Comment by TeodorUn** [comment]
Все настройки делаю используя Системный администратор.

**Comment by TeodorUn** [comment]
даже если включить абсолютно все флажки и выключить только "Администратор" и "Системный администратор" то появляется данная ошибка.

**Comment by Nullarity** [comment]
Удалось воспроизвести, спасибо! Исправительную версию опубликуем в ближайшее время.

**Comment by Nullarity** [comment]
@TeodorUn проверьте пожалуйста на 5.0.14.6. Не забудь пользователю добавить права редактирования свойств, если еще не добавили.

**Comment by TeodorUn** [comment]
уже работает, спасибо
