### ISSUE TITLE
Создание Таможенной декларации

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#197]
![image](https://user-images.githubusercontent.com/84187165/129878863-84e359b4-7051-4513-92c6-0f34c4b0da91.png)
Для чего предназначено заполнение данного поля и рядом поля Договор? Без их заполнения невозможно записать документ - ваши пояснения!
Как поняла я : в поле Таможня заполняется Таможенный орган, оформивший декларацию по импорту, а в поле Договор - договор с данной таможней. Если я мыслю правильно, то для нас это дело бессмысленное, т.к. мы не заключаем договор с таможенным органом. В этом случае смысл заполнения данных полей теряется вовсе.
Если я поняла неправильно - жду пояснений.

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/129880445-767bdfe6-41b9-44ed-aed3-d2625f1b1df8.png)
Что должно заполняться в данных полях? Я не совсем поняла их предназначение.

**Comment by Nullarity** [comment]
Создание контрагента для таможни (как и любого другого) сопровождается автоматическим созданием договора (без какого-либо участия пользователя). Учитывая, что взаиморасчеты с таможней ведутся на счетах с аналитикой по контрагентам и договорам, указание договора требуется в обязательном порядке.

На вкладке Дополнительно нужно указать бухгалтерский счет учета таможни. Поля Оплата и срок нужны для детализации расчетов и определения старения долга. Эти поля не обязательны для заполнения.

**Comment by Linda4ka** [comment]
Получается, что в поле Таможня, мы в обязательном порядке заполняем , ну например Vama Chisinau, если товар был растаможен на кишиневской таможне, или Vama Leusani, если он прошел через пост Леушены. Я правильно поняла?

**Comment by Nullarity** [comment]
Да, совершенно верно. Либо, можете создать одну таможню, а пункты завести в систему договорами.

**Comment by Linda4ka** [comment]
Спасибо, понятно!
