### ISSUE TITLE
Не формируется Отчет Заказы поставщикам

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#198]
![image](https://user-images.githubusercontent.com/84187165/129881983-01b8a079-2f6e-47b3-9f5a-2170c5b2b0b8.png)
Почему не формируется?

**Comment by Nullarity** [comment]
Не знаю.

**Comment by SvetlanaRes** [comment]
@Linda4ka , возможно заказ поставщику был полностью оприходован и полностью оплачен. Я обратила внимание, что в отчете отображаются заказы не закрытым заказам (по поступлению тмц и/или по оплате).

@Nullarity , верно?

**Comment by Nullarity** [comment]
Отчет Заказы поставщикам (и ряд аналогичных) выводят информацию о текущих заказах. Если заказ оплачен и отгружен, в этом отчете он выводиться не должен.

**Comment by Nullarity** [comment]
> А если он только оплачен и не отгружен, или наоборот, отгружен и не оплачен, то будет попадать в отчет, т.к. получается что он не завершен?

да, должен

**Comment by Linda4ka** [comment]
Спасибо, понятно!
