### ISSUE TITLE
Утверждение заказов покупателей

### ISSUE THREAD

**Issue by SvetlanaRes** [Contabilizare/c5#2]
![WhatsApp Image 2021-04-09 at 10 57 47](https://user-images.githubusercontent.com/82224240/114196984-93295d00-995a-11eb-990f-d6caf4f43ab0.jpeg)

Я так понимаю, что если он выключен, то заказы не нуждаются в утверждении. У меня не меняется ничего.

**Comment by Nullarity** [comment]
работает оно так (выдержка из документации https://cont.help/d/SalesOrder/):

> В системе существует две опции, которые задают необходимость отправки заказа на утверждение руководителю подразделения (п.1). Первая опция задается на уровне покупателя, на вкладке Покупатель, флаг Утверждать заказы покупателей. Вторая опция задается в профиле пользователя, см. Настройки / Пользователи / Дополнительно / Утверждать заказы покупателей. Если флаг установлен для пользователя, все заказы в системе, введенные от этого пользователя будут поступать на утверждение руководителю подразделения. Если флаг не установлен, на утверждение будут поступать заказы покупателей, у которых задан флаг утверждения на уровне покупателя. Если флаги не установлены, этап утверждения будет пропущен и заказ поступит на этап Отгрузка (для товаров) или Реализация (для услуг). Полностью пропустить бизнес-процесс нельзя.

Другими словами, нужно выключить два флага: у пользователя и у клиента. В этом случае, заказ будет попадать сразу на этап выписки накладной.
