### ISSUE TITLE
Отгрузка из Заказа покупателя

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#201]
Добрый день! Решила сделать поэтапное заполнение Заказ покупателя/Утверждение/Отгрузка и т.д, но столкнулась с проблемой. Прочитала информацию на сайте и вроде делаю все как надо, но ничего не получается. Я делаю Заказ покупателя и отправляю его на утверждение. После захожу в документ и нажимаю Завершить утверждение, в надежде что после этого в строке состояние появится Отгрузка, но вместо этого сразу же появляется состояние Реализация..  Получается сразу необходимо делать реализацию и закрывать заказ. Сделать отдельно Отгрузка совсем невозможно. В чем может быть причина, что я делаю не так или непоследовательно?

**Comment by Nullarity** [comment]
В карточке подразделения, в рамках которого оформляется заказ, установите флаг Использовать отгрузки (заказ после этого придется переоформить).
