### ISSUE TITLE
Ошибка при попытке формирования Личной карточки сотрудника

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#203]
![image](https://user-images.githubusercontent.com/84187165/130066837-b0005565-37f4-4b9d-94f8-bdee179efbfd.png)
Текст ошибки:{(73, 95)}: Поле не найдено "Taxes.Period"
from ( select Employees.Employee as Employee, Taxes.Ref as Ref, Taxes.Ref.Date as Date, Taxes.<<?>>Period as Months, Taxes.Deductions as Deductions,
{CommonModule.SQL.Module(44)}:	result = ? ( Data = undefined, q.ExecuteBatch (), Data );
{CommonModule.SQL.Module(83)}:	SQL.Unload ( Env );
{Report.PersonalCard.ObjectModule(401)}:	SQL.Perform ( Env );
{Report.PersonalCard.ObjectModule(84)}:	getTables ();
{Report.PersonalCard.ObjectModule(63)}:	getData ();
{Report.PersonalCard.ObjectModule(39)}:	print ();
{CommonModule.Reporter.Module(899)}:		Report.AfterOutput ();
{CommonModule.Reporter.Module(852)}:	ok = putReport ( Report );
{Report.Common.Form.Form.Form(232)}:	if ( not Reporter.ComposeResult ( report ) ) then
{Report.Common.Form.Form.Form(336)}:	if ( makeReport ( Quickly ) ) then
{CommonModule.ReporterForm.Module(124)}:		Form.BuildReport ( true );
{Report.Common.Form.Form.Form(1019)}:	ReporterForm.OnChange ( ThisObject,

**Comment by Nullarity** [comment]
Спасибо!
