### ISSUE TITLE
правила ввода количество

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#21]
Добрый день.
Не возможно ввести кол-во в дробном виде (3,5 в примере). всегда округляется даже если у товара точность 2.
![image](https://user-images.githubusercontent.com/82500510/116091124-35f90f80-a6ad-11eb-95c8-5b4d9d748292.png)
то же самое во всех формах

**Comment by Nullarity** [comment]
Добрый!
Настройка точности количества выполняется в настройках программы, меню Настройка / Приложение / Товары / Точность

**Comment by TeodorUn** [comment]
Спасибо

**Comment by TeodorUn** [comment]
Update:

После смены данной настройки на 2, единицы стали делитися на дроби при том что в настройках самого товара точиность 0. 
![image](https://user-images.githubusercontent.com/82500510/116399876-10e1d980-a832-11eb-9531-a2b50fae6450.png)
Получается что "Настройка / Приложение / Товары / Точность" влият не только на колонку "количество" но и на "единиц".

**Comment by Nullarity** [comment]
Подскажите пожалуйста, в каких единицах вы приходуете черепицу?

**Comment by TeodorUn** [comment]
в штуках
![image](https://user-images.githubusercontent.com/82500510/116421355-6e345580-a847-11eb-9ddb-514164a526e2.png)

**Comment by Nullarity** [comment]
Я правильно понимаю, что для удобства складского хранения товаров (в данном случае, черепицы), вам удобнее использовать штуки, потому что легче проводить инвентаризацию, без взвешивания и замеров. Но для целей продажи, вам нужно проводить конвертацию м2 в штуки? Если это так, то верно ли и то, что при такой конвертации, правила математического округления не применимы, потому что дробная всегда должна округляться до большего целого? Например, в вашем примере, 140.30 должно быть округлено до 141, а не 140?
Если это не так, дайте пожалуйста чуть больше информации. Дело в том, что поле Точность в карточке товара не предназначено для пересчетов упаковок (это реквизит для производственного блока)
