### ISSUE TITLE
Ошибка в расчете больничных

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#216]
Просмотрела отчет по расчету больничных и ясно почему не показывало сумму:
![image](https://user-images.githubusercontent.com/84187165/132311476-127f6a18-d831-4ab9-a3f8-d1509394c274.png)
Коэффицент выплаты должен быть 0,75 , а в программе 0, поэтому при расчете сумма, умноженная на 0 дает 0

**Comment by Nullarity** [comment]
Подскажите пожалуйста, у вас в документе Больничный, заполнено поле "Поправка на стаж, %" ?

**Comment by Linda4ka** [comment]
Общими усилиями разобрались в чем проблема. Оказалось, что проблема в формулировке, которая сбивает с толку и не дает сделать правильные действия. Формулировки Поправка на стаж уже давно нет. Сейчас есть % выплаты и он составляет 75%. Измените, пожалуйста формулировку, чтоб не возникало вопросов. В этом же поле цыфру 75 можно сделать неактивной.
 
![image](https://user-images.githubusercontent.com/84187165/134122725-e5ac351b-5b0a-4636-aa2f-1a3065dba2e2.png)
Просто данный % не зависит от стажа, а регламентирован законом.

**Comment by Nullarity** [comment]
Подскажите пожалуйста, как называется этот процент? (на рум и рус языках пожалуйста).

**Comment by Linda4ka** [comment]
Коэффицент расчета больничного за счет работодателя
Coeficient de calcul concediul medical din contul angajatorului
