### ISSUE TITLE
Заполнение путевых листов

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#219]
Почему при заполнении путевых листов, печатная форма не заполняется исходными данными?
![image](https://user-images.githubusercontent.com/84187165/133080861-dadf7f3d-caa0-4ed5-87b9-5e149299b9f5.png)
![image](https://user-images.githubusercontent.com/84187165/133081192-fee5d903-7169-48f8-9ce1-ef8dbe7507aa.png)
![image](https://user-images.githubusercontent.com/84187165/133081271-f861adf2-1bf0-47f0-a23c-bd1a84d38c65.png)
![image](https://user-images.githubusercontent.com/84187165/133081333-1b78c741-d103-4acf-83f9-3bf6adb26fce.png)
Что я заполняю не так? Может я чего-то не вижу или не понимаю?

**Comment by Nullarity** [comment]
Подскажите пожалуйста, что является исходными данными для ввода документа Путевой лист в систему?

**Comment by Linda4ka** [comment]
[Путевые листы.docx](https://github.com/Contabilizare/c5/files/7183184/default.docx)

**Comment by Nullarity** [comment]
Тогда почему вы ожидаете печать показаний спидометра, если это входные для путевого листа (в программе) данные?

**Comment by Linda4ka** [comment]
Получается, что печатная форма, в нашем случае, не имеет никакого смысла. Если при вводе данных она полностью не заполняется при выводе на  печать, зачем она там?! Бланки строгой отчетности "Путевые листы", которые закупает любое предпиятие, могут просто заполняться водителем вручную, а данные просто вноситься в программу без печатной формы.

**Comment by Nullarity** [comment]
> Получается, что печатная форма, в нашем случае, не имеет никакого смысла

Вы правы, единственно что она имеет смысл в случае, когда заказываются не сами бланки, а диапазон. Однако механизм диапазонов в полной мере именно для путевых листов, пока не реализован.

**Comment by Linda4ka** [comment]
Получается, что если данная форма предназначена для диапазона, она тем более должна заполняться полностью всеми данными, которые вносяться. Поэтому, стоит предусмотреть заполнение всей полей путевого листа и вывод заполненной формы на печать. У нас есть клиенты, которые преобретают диапазон и распечатывают уже готовый путевой лист.

**Comment by Nullarity** [comment]
> Получается, что если данная форма предназначена для диапазона, она тем более должна заполняться полностью всеми данными, которые вносяться

Почему?

**Comment by Linda4ka** [comment]
Потому как это форма строгой отчетности, распечатывается и хранится в бухгалтерии. Поэтому данные, заполняемые в путевом листе, должны быть заполнены как  того требует инструкция по заполнению. Оборотная сторона должна быть заполнена тоже, согласно имеющимся колонкам. Иначе в ней просто нет смысла. В 4.0, для клиентов, которые заказывают диапазон, была разработана точная форма путевого листа с возможностью его полного заполнения.

**Comment by Nullarity** [comment]
К сожалению, непонятно. Вот сценарий: из программы печатается бланк (болванка), выдается водителю, он в течении вахты вносит туда данные, затем отдает в бухгалтерию, бухгалтер вводит данные в систему.
С какой целью проводить печать путевого листа еще раз с уже заполненными данными?

**Comment by Linda4ka** [comment]
Уточню у одних клиентов и отпишусь в понедельник!
