### ISSUE TITLE
Комплектация на закладке Склад

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#222]
![image](https://user-images.githubusercontent.com/84187165/134130493-2bf8d348-4ad6-4953-9ec5-69ce023fcbc2.png)
![image](https://user-images.githubusercontent.com/84187165/134130603-b3e2d8af-5a79-4544-9246-4dd80a4a852b.png)
Но при этом остатки на складе есть
![image](https://user-images.githubusercontent.com/84187165/134130816-0b00e56f-2b39-45e9-9bf6-a105e5ac0257.png)
Что  не так? Выпуск товара сделала. По отчету по товарам на складах все имеется в наличии, а выдает что не хватает

**Comment by Nullarity** [comment]
а что по партиям? Отчет Себестоимость.

**Comment by Linda4ka** [comment]
В отчете по себистоимости ничего не показано, т.к. себистоимость 0. А при проведении товара, имеющим себистоимость в комплектации  выдает ошибку со следующим текстом:
Ошибка при выполнении обработчика - 'Posting'
по причине:
Поле объекта не обнаружено (SetAccount)
{Document.Assembling.ManagerModule(397)}:		p.AccountDr = row.SetAccount;
{Document.Assembling.ManagerModule(230)}:	commitCost ( Env, cost );
{Document.Assembling.ManagerModule(27)}:		if ( not makeValues ( Env ) ) then
{Document.Assembling.ObjectModule(35)}:	Cancel = not Documents.Assembling.Post ( env );
![image](https://user-images.githubusercontent.com/84187165/134298123-6305c17f-8281-422c-b9d6-e59de62e2faf.png)

**Comment by Nullarity** [comment]
Да, есть такая проблема, буду исправлять.

**Comment by Linda4ka** [comment]
Спасибо!

**Comment by Nullarity** [comment]
@Linda4ka тут две проблемы, первая - это ошибка в документе Комплектация, которая уже исправлена в грядущем 5.0.18.2. Вторая проблема, это себестоимость выпуска, во этим пока нет времени заняться.

**Comment by Linda4ka** [comment]
Если я правильно поняла, то на данный момент, после обновления релизом 5.0.18.2, будет возможность составлять и проводить документ Комплектация только по наменклатуре, имеющей себестоимость?! Или нет?

**Comment by Nullarity** [comment]
да
