### ISSUE TITLE
Внутреннее совместительство

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#232]
Добрый день! Сегодня решила добавить документы по сотрудникам касаемо внутреннего совместительства. Честно говоря, в данном конкретном случае, неудобно и необходима лишняя куча документов. Что имеется в виду: 
1. Создание сотрудника для приема на внутреннее совместительство. Если взять, что у нас имеются предприятия с числом сотрудников 175-200 человек, и большинство из них ежемесячно принимаются на внутреннее совместительство, это изначально будет катастрофой. Никто не захочет плодить сотрудников, тем более, что есть вероятность ошибиться при приеме на внутреннее совместительство, выбрав не того.
2. Сделав табель по сотруднику, увидела, что при наличии у сотрудника отпуска, отражение происходит только по основному месту работы, а по совместительству полный рабочий месяц. Получается, что необходимо писать 2 заявления на отпуск  для правильного отражения в табеле. До больничных не дошла, но подозреваю что ситуация мало чем будет отличаться от отпуска.
3. Процесс получается трудный и неудобный.
Продумайте, пожалуйста, механизм, при котором была бы возможность принимать на внутреннее совместительство  уже имеющегося сотрудника. Во избежание путаницы, ошибок и последующих возмущений клиентов.
Мне, как человеку, занимающемуся зарплатой и кадрами, все это очень не понравилось, т.к процесс получается затратным по времени и требующим большого количества затрачиваемой энергии. Если получится облегчить данный блок-будет замечательно! Спасибо!

**Comment by Nullarity** [comment]
> сотрудников 175-200 человек, и большинство из них ежемесячно принимаются на внутреннее совместительство

Тут стоит отметить, что сценарий не частотный. Из определения "Совместительство – это выполнение работником другой регулярной оплачиваемой работы на условиях трудового договора в свободное от основной работы время" следует, что таких работников не должно быть большинство. Если это так, то для данного предприятия нужно делать доработки. В типовую конфигурацию автоматизация данного процесса для таких случаев включена на данный момент не будет (это не исключает возможных улучшений в данном вопросе для компаний, где все-таки внутреннее совместительство не у большинства сотрудников).

> ошибиться при приеме на внутреннее совместительство, выбрав не того

нужно будет сделать программу умнее, может даже как-то по особому выводить таких сотрудников.

> Сделав табель по сотруднику, увидела, что при наличии у сотрудника отпуска, отражение происходит только по основному месту работы, а по совместительству полный рабочий месяц

Взял на заметку.

> Продумайте, пожалуйста, механизм, при котором была бы возможность принимать на внутреннее совместительство уже имеющегося сотрудника

В силу ограничений такого подхода, и было принято решение разделять сотрудников, как это и должно быть, потому что понятие "сотрудник" определяется трудовыми отношениями, а не физическим лицом (в программе, которую вы использовали, такого разделение видимо не было).

**Comment by Linda4ka** [comment]
Тогда давайте проработаем хотя бы следующее: если у сотрудника основное место работы и совместительство, при отпуске и больничном учитывалось что это один и тот же человек, чтобы при заполнении табеля исключить несоответствия и не плодить заявления на отпуск и больничные листы.

**Comment by Nullarity** [comment]
> Тогда давайте проработаем хотя бы следующее: если у сотрудника основное место работы и совместительство, при отпуске и больничном учитывалось что это один и тот же человек, чтобы при заполнении табеля исключить несоответствия и не плодить заявления на отпуск и больничные листы.

да, это недоработка, программа должна так работать, как вы пишите в данных ситуациях.

**Comment by Linda4ka** [comment]
Еще один момент: Предусмотрите, пожалуйста, чтобы при формировании расчетных листков в конце месяца, по сотруднику, у которого основное место работы и внутреннее совместительство, формировались расчетные листки сразу и по основному месту работу и по внутреннему совместительству. Сейчас формируется отдельно по основному и необходимо отдельно формировать по внутреннему. И чтобы после увольнения с внутреннего совместительства происходило формирование только по основному месту работы.

**Comment by Nullarity** [comment]
> формировались расчетные листки сразу и по основному месту работу и по внутреннему совместительству

Если при формировании расчетного листка будет установлен фильтр по подразделению, в этом случае выводить информацию только по подразделению? (по совместительству, сотрудник может числится в другом подразделении).

**Comment by Linda4ka** [comment]
А если только по сотруднику, независимо от подразделения? Есть такая возможность?

**Comment by Nullarity** [comment]
> А если только по сотруднику, независимо от подразделения? Есть такая возможность?

Я думаю что да. Можно сделать в таком случае, чтобы программа выводила два расчетных листка. Но вот если установлен фильтр по подразделению, а сотрудник работает в разных, в этом случае будет выведен только один расчетный листок.

**Comment by Linda4ka** [comment]
Значит будем объяснять клиентам что фильтрами, в данном случае, лучше не пользоваться. Да и на практике, чаще всего, выводят расчетные листки по сотрудникам, независимо от подразделений, общим списком по предприятию.
