### ISSUE TITLE
Форма печати для налоговой накладной не соответствует актуальной 28.08.2017

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#250]
![image](https://user-images.githubusercontent.com/82500510/136943141-da2b0898-a81e-4ec1-9427-ecc3ec0cada7.png)
https://servicii.fisc.md/DownloadFormular.aspx?tl=467

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/137077266-a476a1c6-ae59-4bc7-b12b-2724a63c6275.png)

**Comment by Linda4ka** [comment]
Правильно, я скинула как должно быть, но в 5.0 старая форма.

**Comment by Nullarity** [comment]
> Правильно, я скинула как должно быть, но в 5.0 старая форма.

@Linda4ka, изменения касаются только выделенных пунктов?

**Comment by Linda4ka** [comment]
Добрый день! Пересмотрю всю форму и дам знать!
