### ISSUE TITLE
Новая ошибка при реализации

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#253]
![image](https://user-images.githubusercontent.com/82500510/137144950-eab2ff7a-95df-4283-8bd4-9bb1fd052c82.png)

Пробовал сделать оплату перед реализацией. Теперь ошибка выглядит вот так 
![image](https://user-images.githubusercontent.com/82500510/137146499-ef5715eb-7829-417c-ae2c-c305f7440e96.png)

**Comment by TeodorUn** [comment]
кажется проблема в резервированых товаров
до утверждения заказа выгледет так
![image](https://user-images.githubusercontent.com/82500510/137151792-f76035ef-09ad-4f81-9a7f-5534de3072ac.png)
после утверждение - вот так
![image](https://user-images.githubusercontent.com/82500510/137151966-f7f777ad-5041-4f93-b366-784b55975b99.png)

будто их уже реализовали

**Comment by Nullarity** [comment]
Нет, видимо проблема в другом. То, что оно показывает как реализованное, конечно не хорошо, будем исправлять, но на проведение реализации это негативно не сказывается, ошибку как у вас на картинке я воспроизвести не смог (( Все-таки если будет возможность или предоставить удаленный доступ, или описать устойчивый сценарий, при котором она проявляется, вы бы очень помогли в устранении этой проблемы.
