### ISSUE TITLE
В демо базе убрать из названия праздников 2021

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#265]
Это не совсем правильно, см. https://cont.help/faqsalary/#_19

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/139629185-22730740-d000-4da3-9288-b9b0cc450213.png)
1.Убирать ничего не надо,т.к. ошибки никакой нет. На каждый год создается своя папка с праздниками, т.к. дни недели в каждом году разные.
2. Указывается только день конкретного города, а не подразделений и т.д. Для кишиневцев, в программе будет указано день города Кишинева, для жителей Ватры, указывается их день города, но не территориального подразделения.
3. В списке праздников не требуется указания всех дней города по республике, а только того города где находится предприятие физически. Или я неправильно поняла суть проблемы?

**Comment by Nullarity** [comment]
Видимо, вы не понимаете как работает программа по части праздников. Убедительная просьба, вначале внимательно прочесть справку. Если после этого останутся вопросы, попробуйте в вашей демо-базе, по своей методике, начислить зарплату за октябрь 2021 и 2022 года, по двум сотрудникам, один из которых работает в Кишиневе (и будет отдыхать в день города), а другой в Бельцах, и будет работать. Поделитесь здесь результатами.

**Comment by Linda4ka** [comment]
Ну в данном случае работник, работающий в Кишиневе отдыхает в день города 14.10., а если подразделение компании расположено в Бельцах и там работают сотрудники из Кишинева или Бельчане, они будут работать в этот день, т.к по сути к ним это не имеет никакого отношения. Вы очень усложнили сейчас задачу.

**Comment by Nullarity** [comment]
Очень прошу, для конструктивности дальнейшей дискуссии, используя ваши же тезисы и методику, провести в программе очень простую ситуацию:
1. На предприятии работает два сотрудника, один в Кишиневе, второй в Бельцах, работают по классической пятидневке.
2. Начислите им пожалуйста зарплату за октябрь 2021 и 2022

Скажите, что вам для этого пришлось сделать в программе по части графиков и праздников, чтобы зарплата была рассчитана правильно. Только после этого мы сможем двигаться дальше.

**Comment by Linda4ka** [comment]
По пункту 1. А кто сказал что такое возможно?

**Comment by Linda4ka** [comment]
Даже если в Кишиневе головной офис, то в Бельцах будет дочернее предприятие со своей бухгалтерией

**Comment by Nullarity** [comment]
Простите, вы не работали раньше с территориально распределенными подразделениями? Речь не о дочерних предприятиях и не о филиалах.

**Comment by Linda4ka** [comment]
Прощаю, не работала! Но, если это территориальные подразделения, то судя по всему на этих самых территориальных подразделениях работают работники не из Кишинева, а жители тех территорий, на которых они находятся. В любом случае по ним ведется бухгалтерия на местах и сдается в осную бухгалтерию.
Для примера: когда в Кишиневе 14 октября был День города, Министерство здравоохранения не работало, а вот все территориальные подразделения в других городах работали.

**Comment by Linda4ka** [comment]
Ну не ведется бухгалтерия из Кишинева по подразделения по всей республике, в каждом свой учет.В Кишинев стекаются данные со всех подразделений.

**Comment by Nullarity** [comment]
> В любом случае по ним ведется бухгалтерия на местах и сдается в осную бухгалтерию.

Нет, это не так. Начисление ЗП, ровно как и другие операции осуществляются центрально бухгалтерией, по всей компании в целом.

**Comment by Nullarity** [comment]
> Ну не ведется бухгалтерия из Кишинева по подразделения по всей республике

расскажите это компании, прошедшей неоднократный аудит

**Comment by Linda4ka** [comment]
А мы делаем это под конкретную фирму?

**Comment by Nullarity** [comment]
нет

**Comment by Nullarity** [comment]
Учитывая, что вы не сталкивались с такого рода предприятиями, давайте упростим сценарий:
1. Начислите пожалуйста зарплату за октябрь 2021 и 2022 одному сотруднику.
2. Скажите, что вам для этого пришлось сделать в программе по части графиков и праздников, чтобы зарплата была рассчитана правильно.

Проделайте это пожалуйста, это поможем нам начать обсуждение как минимум с какой-то определенной точки.

**Comment by Linda4ka** [comment]
Хорошо, я завтра утром сделаю и сообщу о результате

**Comment by Linda4ka** [comment]
Ну, я сделала. И за ноябрь, по двум сотрудникам, работающих в разных территориальных подразделениях и в январе, по тем же сотрудникам. Создала праздники на 2022 год, перезаполнила в приеме на работу пятидневку, поменяла там с праздников с 2021 на 2022( по каждому подразделению) и посчитала зарплату. У меня все посчиталось правильно, проверила вручную. Проблем не возникло.

**Comment by Nullarity** [comment]
Вам пришлось:

1. Создать два разных графика. И вам придется делать так каждый раз для каждого подразделения, а также каждый новый год менять привязку к праздникам.
2. Создать две записи в справочнике праздников. И вам придется делать так каждый раз для каждого нового подразделения и каждого нового года.

В программе делать правильно так:

1. Создать один график и привязать его к одному справочнику праздников
2. Создать одну запись в справочнике праздников, и в тех случаях, когда праздник приходится только на одно территориальное подразделение, в этом же справочнике, в таблице с днями, указывать это подразделение, и программа поймет эту ситуацию.

Но вы можете продолжать свой путь, программа это позволяет. Я просто хочу, чтобы в демо базе было правильно.

**Comment by Linda4ka** [comment]
Но, в данном конкретном случае, правильных варианта 2. Для просмотра пользователями и на их усмотрение, я сделаю вариант №2, и дам возможность пользователю самому решать каким вариантом пользоваться. Думаю, это будет куда более правильным решением!

**Comment by Linda4ka** [comment]
Тем более, что вашим вариантом будут пользоваться не очень большое кол-во пользователей!

**Comment by Nullarity** [comment]
К сожалению, вы так и не поняли как работает программа. Если бы вы сделали как я попросил, по упрощенному сценарию с одним сотрудником (и без всяких территориальных подразделений), вы бы увидели разницу в кол-ве совершаемых операций при правильном подходе и вашем.

**Comment by Linda4ka** [comment]
Спасибо за откровенность

**Comment by Nullarity** [comment]
Я задаю вопросы - вы на них не отвечаете, я прошу что-то сделать, вы делаете другое, что-то свое. В такой ситуации, говорить о том, кому что будет понятней, просто неуместно, а времени пробираться через эти дебри непонятных мне трудностей, нет. Текущее проектное решение было сделано под действием конечных пользователей, а не потому что мне вдруг захотелось, поэтому как минимум некоторым пользователям это кажется вполне очевидным.

**Comment by Linda4ka** [comment]
Я затрачиваю уйму сил и энергии чтобы как можно тщательнее сделать те или  задачи, после каждого обновления ищу ошибки и пытаюсь все это как-то привести в порядок, но если некоторым клиентам что-то кажется очевидным, специально для них я все переделаю!!!

**Comment by Nullarity** [comment]
> Я затрачиваю уйму сил и энергии чтобы как можно тщательнее сделать те или задачи

Пока вы не начнете отвечать на мои вопросы, и делать то, что я прошу по теме дискуссии, мы так и будем тратить время впустую.

> специально для них я все переделаю!!!

я попросил убрать из наименования справочника, одно слово 2021. Это не кажется так много.

**Comment by SvetlanaRes** [comment]
> По пункту 1. А кто сказал что такое возможно в рамках одной фирмы, находящейся в Кишиневе?

Так работают предприятия в Молдове. И торговые, и производственные. Офис в Кишиневе и несколько территориальных подразделений. Рег.отчетность единая, и бухгалтерия тоже.

**Comment by SvetlanaRes** [comment]
> Даже если в Кишиневе головной офис, то в Бельцах будет дочернее предприятие со своей бухгалтерией

в данном контексте могут быть и территориальные подразделения, не обязательно дочерние с отдельным бух.учетом

**Comment by SvetlanaRes** [comment]
> Ну не ведется бухгалтерия из Кишинева по подразделения по всей республике, в каждом свой учет.В Кишинев стекаются данные со всех подразделений.

ведется! и ЗП начисляется в Кишиневе, по каждому подразделению в отдельности. Рег.отетность единая.

**Comment by SvetlanaRes** [comment]
> Вам пришлось:
> 
> 1. Создать два разных графика. И вам придется делать так каждый раз для каждого подразделения, а также каждый новый год менять привязку к праздникам.
> 2. Создать две записи в справочнике праздников. И вам придется делать так каждый раз для каждого нового подразделения и каждого нового года.
> 
> В программе делать правильно так:
> 
> 1. Создать один график и привязать его к одному справочнику праздников
> 2. Создать одну запись в справочнике праздников, и в тех случаях, когда праздник приходится только на одно территориальное подразделение, в этом же справочнике, в таблице с днями, указывать это подразделение, и программа поймет эту ситуацию.
> 
> Но вы можете продолжать свой путь, программа это позволяет. Я просто хочу, чтобы в демо базе было правильно.

@Linda4ka, а пробовали сделать "правильный" вариант? С этим вариантом понятны шаги?

**Comment by SvetlanaRes** [comment]
> Очень прошу, для конструктивности дальнейшей дискуссии, используя ваши же тезисы и методику, провести в программе очень простую ситуацию:
> 
> 1. На предприятии работает два сотрудника, один в Кишиневе, второй в Бельцах, работают по классической пятидневке.
> 2. Начислите им пожалуйста зарплату за октябрь 2021 и 2022
> 
> Скажите, что вам для этого пришлось сделать в программе по части графиков и праздников, чтобы зарплата была рассчитана правильно. Только после этого мы сможем двигаться дальше.

@Linda4ka, смоделируйте, пожалуйста, данную ситуацию с учетом подхода, заложенного/продуманного в программе.
