### ISSUE TITLE
Не выводить отрицательный суммы к выплате в документе Выплата ЗП

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#266]

**Comment by Linda4ka** [comment]
Можно уточнение по данному вопросу?

**Comment by Nullarity** [comment]
Эта проблема уже устранена. Иногда возникали ситуации, когда в документ Выплата ЗП попадали отрицательный суммы к выплате (например, сделали начисление/выплату, а затем отменили начисление и перезаполнили выплату).

**Comment by Linda4ka** [comment]
А, понятно!
