### ISSUE TITLE
IPC21

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#275]
Есть некоторые недочеты в заполнении отчета:
![image](https://user-images.githubusercontent.com/84187165/139647665-92d06faa-200c-48d0-a617-1eabc1f45a4a.png)
1. Необходимо исправить в Регламентных отчетах IPC 18 на IPC 21 и удалить один ненужный IPC 18
2. При внутреннем или внешнем совместительстве, при заполнении отчета, период данного совместительства, должен заполняться с кодом 123. Я попробовала в физ.лицах на закладке Категория застрахованных лиц, проставить с 01.08,2021(когда было принятие на внутреннее совместительства) проставить код 123 и в отчете код поменялся со 101 на 123, а период внутреннего совместительства остался не заполненным Это ошибка. 
3. Сумма зарплаты и сумма дополнительных выплат по одному сотруднику в отчете не должны разделяться, все должно идти одной суммой в колонке Фонд оплаты труда и прочие вознаграждения.
4. У меня оформлен больничный с 01.10.2021 по 30.10.2021 полностью за счет БГСС, а в отчет IPC 21 данный больничный с периодом не попал вообще, хотя должен попасть период с кодом 15312

**Comment by Nullarity** [comment]
> Необходимо исправить в Регламентных отчетах IPC 18 на IPC 21 и удалить один ненужный IPC 18

Спасибо.

> При внутреннем или внешнем совместительстве, при заполнении отчета, период данного совместительства, должен заполняться с кодом 123. Я попробовала в физ.лицах на закладке Категория застрахованных лиц, проставить с 01.08,2021(когда было принятие на внутреннее совместительства) проставить код 123 и в отчете код поменялся со 101 на 123, а период внутреннего совместительства остался не заполненным Это ошибка.

Уточните, какой должен быть период?

> Сумма зарплаты и сумма дополнительных выплат по одному сотруднику в отчете не должны разделяться, все должно идти одной суммой в колонке Фонд оплаты труда и прочие вознаграждения.

Спасибо посмотрю, но стоит отметить, что если выплаты отличаются по периоду, они будут идти разными строками.

> У меня оформлен больничный с 01.10.2021 по 30.10.2021 полностью за счет БГСС, а в отчет IPC 21 данный больничный с периодом не попал вообще, хотя должен попасть период с кодом 15312

Был ли предварительно рассчитан документ Начисление ЗП, попал ли туда больничный?

**Comment by Linda4ka** [comment]
При больничном, в котором сотрудник находился весь месяц за счет БГСС, табель не формируется, в документ Гачисление ЗП попадают только сотрудники, отработавшие в этом месяце. Дальше куда двигаться не знаю.

**Comment by Nullarity** [comment]
К сожалению, мне не удается воспроизвести проблему. Сотрудник попадает в табель и в Начисление ЗП (Приложите свою базу сюда пожалуйста, чтобы понять почему у вас не так).

В программе, начисление ЗП это операция по отражению всех расчетов со сотруднику за указанный период, а не только вознаграждения отличные от ноля. Таким образом, наличие в базе больничного (не важно за какой период) еще не означает, что теперь он автоматически должен попадать в ипц. Тот факт, что у вас получился целый месяц (а не половина, например), не означает, что теперь по таким сотрудникам начисление можно не делать.

**Comment by Linda4ka** [comment]
По периоду: Начиная с принятия на внутреннее или внешнее совместительство до момента увольнения с данного совместительства. Это может быть и один день и целый месяц.

**Comment by Nullarity** [comment]
> По периоду: Начиная с принятия на внутреннее или внешнее совместительство до момента увольнения с данного совместительства. Это может быть и один день и целый месяц.

Опишите пожалуйста сценарий полностью, что вы сделали (с датами и деталями) и что не получилось.

**Comment by Linda4ka** [comment]
По больничному: Табель сделала, начисление тоже, но период обязательно должен был попасть в IPC 21, т.к на основании этих данных БГСС будет делать выплаты. Если есть больничный, но в отчете неправильно отмечен период и не совпадает с больничным листом, человеку могут отказать в выплате. Поэтому очень важно чтобы каждый больничный правильно попадал в отчет.

**Comment by Nullarity** [comment]
К сожалению, проблему понять не удается. Опишите пожалуйста ситуацию в виде последовательности действий, с указанием дат и сумм, а также ожидаемых результатов и полученных. Спасибо.

**Comment by Linda4ka** [comment]
Ситуация следующая: У сотрудника с 1.10 по 30.10 больничный полностью за счет БГСС. Мы его регистрируем, делаем табель. Начислений нет, т.к. сумму по данному больничному выплатит БГСС, но в отчет IPC 21 за октябрь этот больничный,т.е. период с 1.10 по 30.10 должен попасть с кодом 15312 без сумм.

**Comment by Linda4ka** [comment]
А сейчас не попадает ничего

**Comment by Nullarity** [comment]
Я писал:

> Был ли предварительно рассчитан документ Начисление ЗП, попал ли туда больничный?

Потом я писал:

> В программе, начисление ЗП это операция по отражению всех расчетов со сотруднику за указанный период, а не только вознаграждения отличные от ноля

Кроме того, что я не получил ни одного ответа по этим комментариям, я не понимаю, как еще выразить мысль, что 
для того, чтобы больничный (и не важно, за месяц или пол месяца, или один день) попадал в отчет, необходимо зарегистрировать в системе расчет зарплаты. Эту функцию выполняет документ Начисление ЗП. Введите его пожалуйста. Рассчитайте и проведите. После этого, в отчете появится запись.

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/139692079-20ed32bf-d572-4ae6-9bd0-5149903266bb.png)
![image](https://user-images.githubusercontent.com/84187165/139692412-96760d12-4e19-4e35-a619-d3242760b63d.png)
Напишите, где я не права

**Comment by Nullarity** [comment]
вы делаете начисление в октябре больничного в ноябре?

**Comment by Linda4ka** [comment]
Спасибо за подсказку, иногда за целый день не видишь очевидного. Получилось, заполнилось правильно!
