### ISSUE TITLE
Часто задаваемые вопросы: Почему не считаются отпускные?

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#279]
![image](https://user-images.githubusercontent.com/84187165/140276119-120786c3-9b1f-4a2b-bd64-2d19de561afb.png)
Выделенный абзац с 75 процентами вообще-то относится к расчету больничных, а не отпускных. У нас больничный за счет работодателя выплачивается в размере 75 %, а отпускные полной рассчитанной суммой. Проверьте пожалуйста нет ли ошибки.

**Comment by Nullarity** [comment]
Спасибо, поправлю.
