### ISSUE TITLE
Часто задаваемые вопросы: Почему не считается больничный?

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#280]
![image](https://user-images.githubusercontent.com/84187165/140277137-1e5768a6-4411-4285-b23d-849397c5f514.png)
Исправьте, пожалуйста, базой для расчета больничных считается: оклад, премия, отпускные, но никак не больничный. Он в базу для расчета не входит,т.к. по больничным нет удержания налогов.

**Comment by Nullarity** [comment]
Здесь нет ошибки, База расчета - это база расчета компенсации, а не на лога, и если больничный в базу не задать, компенсация будет считаться неправильно. В справке не указано, что в базу расчета налогов, нужно добавлять соцфонд.

**Comment by Linda4ka** [comment]
Вы не поняли, я не про расчет налога. Базой для расчета суммы выплаты по больничному. Сумма выплаты больничного выходит из оклада, отпускных и премий. По тому что вы написали следует, что для расчета суммы больничного  должны включаться суммы , выплаченные по предыдущим больничным, если они есть, оклад, премии и отпускные

**Comment by Nullarity** [comment]
Понял, спасибо, исправлю.

**Comment by Linda4ka** [comment]
Ежемесячная сумма возмещения за больничный лист из бюджета работодателя составит 75% от средней заработной платы работника. Согласно Постановлению Правительства №426 от 26.04.2004 в среднюю заработную плату включается: зарплата, надбавки, выплаты за совмещение,премии, доплаты за работу в ночные и праздники 
НЕ ВКЛЮЧАЮТСЯ: Выходные пособия, пособия по безработице и другие пособия независимо от источника выплат. Компенсация за неиспользованный отпуск
Больничный-это пособие по временной нетрудоспособности.

**Comment by Linda4ka** [comment]
Можете дополнить что включается в расчет
