### ISSUE TITLE
Проблема после обновления

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#281]
В Приложении проставила значение 75, оформила больничный на сотрудника. Сделала табель и начисление зарплаты чтобы убедиться в правильности расчетов,но при попытке распечатать расчет больничного вышла ошибка
![image](https://user-images.githubusercontent.com/84187165/140282876-4fc26988-d631-4e66-b160-816e00ba06c2.png)
Текст ошибки:{(15, 53)}: Не задано значение параметра "Date"
left join InformationRegister.Settings.SliceLast ( <<?>>&Date,
{CommonModule.SQL.Module(44)}:	result = ? ( Data = undefined, q.ExecuteBatch (), Data );
{CommonModule.SQL.Module(83)}:	SQL.Unload ( Env );
{Document.Payroll.ManagerModule(215)}:	SQL.Perform ( Env );
{Document.Payroll.ManagerModule(195)}:	getSicknessPrintData ( Params, Env );
{Document.Payroll.ManagerModule(157)}:		printSickness ( Params, Env );
{CommonModule.PrintSrv.Module(81)}:	return manager.Print ( Params, env );
{CommonModule.PrintSrv.Module(13)}:		error = not printObject ( Params, object, Language );
{CommonForm.Print.Form(12)}:	result = PrintSrv.Print ( Parameters.Params, Parameters.Language );
{CommonModule.Print.Module(26)}:	OpenForm ( "CommonForm.Print", p, , true );
{CommonModule.Print.Module(6)}:		printForm ( Params );
{Document.Payroll.Command.Sickness.CommandModule(9)}:	Print.Print ( p );

по причине:
{(15, 53)}: Не задано значение параметра "Date"
Что не так?

**Comment by Nullarity** [comment]
Спасибо, ошибка уже исправления, войдет в грядущее обновление.
