### ISSUE TITLE
Удаление помеченных объектов

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#286]
При попытке удалить объекты, помеченные на удаление, сохраненные в Документах, ничего не получается. Как это возможно сделать?
![image](https://user-images.githubusercontent.com/84187165/140725065-56fff93a-f62b-427c-b353-be16aa02e63f.png)

**Comment by Nullarity** [comment]
просьба уточнить, после каких именно действий появляется окно с ошибкой.

**Comment by Linda4ka** [comment]
После нажатия кнопки Удалить

**Comment by Nullarity** [comment]
Ясно. А скиньте мне пожалуйста сюда эту базу, надо разбираться.

**Comment by Linda4ka** [comment]
скинула

**Comment by Nullarity** [comment]
Спасибо, проблему увидел, постараюсь исправить в готовящемся релизе.
