### ISSUE TITLE
Удаление из списка

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#287]
![image](https://user-images.githubusercontent.com/84187165/140725331-1ebd4571-65b4-4938-9070-a3701d21bcea.png)
Отмеченные красным объекты уже удалены из базы, но они остаются в общем списке. Как это исправить?

**Comment by Nullarity** [comment]
К сожалению пока никак, это ошибка в платформе.

**Comment by Linda4ka** [comment]
Понятно. Но это как-то будет решено?

**Comment by Nullarity** [comment]
Ошибка пока находится у них на рассмотрении, к сожалению большей информацией по ней не обладаю (

**Comment by Linda4ka** [comment]
Ок, спасибо!
