### ISSUE TITLE
Прошу объяснения по работе документа Ввод остатков по зарплате.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#289]
Сделала документ Ввод остатков по зарплате, ввела сумму остатка и освобождение. Далее сделала по сотруднику документ Выплата зарплаты, но при расчете почему-то оказалось, что освобождение, указанное в вводе остатков, не берется во внимание. Почему?

**Comment by Nullarity** [comment]
Я повторил сценарий, у меня берется. Вероятно, проблема в каких-то деталях. Приложите пожалуйста картинки операций, а также ваш ожидаемый результат расчетов.

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/141058918-dcdbdcc5-af91-4731-828f-b91b00931b51.png)
![image](https://user-images.githubusercontent.com/84187165/141059298-b943bdba-ef96-48c7-96e5-efa82593da89.png)
По идее, подоходный налог должен был быть 840 лей,т.к. при вводе остатков есть освобождение 2100. Но в данном случае программа действует как при расчете зарплаты за первый месяц при принятии на работу и не берет в расчет освобождение, высчитывая подоходный налог с суммы 10000-900(9%0=9100*12%=1092. Может я что-то сделала непоследовательно?

**Comment by Nullarity** [comment]
> при вводе остатков есть освобождение 2100

Давайте уточним, в данном случае 2100 - это не освобождения, которые есть у сотрудника, а сумма уже примененных освобождений с начала года. Вы также трактуете?

**Comment by Linda4ka** [comment]
Извините за поздний ответ, но честно говоря, я подумала что имеется ввиду, при вводе остатков необходимо уточнить сумму освобождения, которая будет вычитаться при расчете суммы введенного остатка. Но получается, что при вводе остатка данная колонка либо вообще не заполняется, либо заполняется суммой освобождения, которое сотрудник уже использовал? Я правильно поняла?

**Comment by Nullarity** [comment]
Да. При наведении курсора на заголовок Освобождения, выдается краткая подсказка, что вводится в данное поле.
