### ISSUE TITLE
Нужно обновление 5.0.14.5

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#296]
Надо срочно! Как можно его найти и где????

**Comment by Nullarity** [comment]
вот.
[1Cv8.cf.zip](https://github.com/Contabilizare/c5/files/7512949/1Cv8.cf.zip)

**Comment by Linda4ka** [comment]
Не прошло, давайте еще 14.3 и 14.4

**Comment by Nullarity** [comment]
уточните, что вы делаете? таким образом мне до 20 релиза скидывать обновления?

**Comment by Linda4ka** [comment]
нет, только 14.3,14.4 и 14.6, все остальное у меня есть)))

**Comment by Linda4ka** [comment]
Просто я загрузила в новую чистую базу, базу выгруженную в июне. Там релиз 5.0.14.1, а на 5.0.15.1 и дальше обновить не дает

**Comment by Nullarity** [comment]
вот.
[5.0.14.3.zip](https://github.com/Contabilizare/c5/files/7513030/5.0.14.3.zip)
[5.0.14.4.zip](https://github.com/Contabilizare/c5/files/7513034/5.0.14.4.zip)
[5.0.14.6.zip](https://github.com/Contabilizare/c5/files/7513042/5.0.14.6.zip)

**Comment by Linda4ka** [comment]
Спасибо!

**Comment by Linda4ka** [comment]
При обновлении на релиз 16.1 выдало ошибку. Что делать ?
![image](https://user-images.githubusercontent.com/84187165/141129743-1b68398c-0a0b-4c09-a354-5b07540234c7.png)

**Comment by Nullarity** [comment]
Вовремя обновлять.

Войдите в настройки запуска информационной базы, и в поле дополнительных параметров запуска, введите:
/C -mode skipupdate

Запустите инфобазу, процесс запуска обновления при этом не должен запуститься. Войдите в настройки программы и на вкладке Бухгалтерия, внизу, установите представление счетов в виде кодов. Сохраните настройки, закройте программу, уберите из дополнительных параметров запуска то. что вводили (/C -mode skipupdate) и запустите приложение.

**Comment by Linda4ka** [comment]
> Войдите в настройки запуска информационной базы, и в поле дополнительных параметров запуска, введите: /C -mode skipupdate
> 
Сделала, при попытке войти в базу выдало непредвиденную ошибку. Прикрепляю отчет.Жду!
[Ошибка_20211111135711.zip](https://github.com/Contabilizare/c5/files/7520230/_20211111135711.zip)

**Comment by Nullarity** [comment]
возьмите параметр в кавычки, т.е. укажите вот так: /C "-mode skipupdate"

**Comment by Linda4ka** [comment]
Попробую, напишу!

**Comment by Linda4ka** [comment]
Сделала как написали, после обновила на релиз 16.1 и снова выдало ошибку.

![image](https://user-images.githubusercontent.com/84187165/141309822-d86f6b62-1e38-4dc1-86d4-4e5c680766c4.png)

**Comment by Linda4ka** [comment]
Судя по всему дело не в том. Изначально в настройках/бухгалтерия/ счета по коду.

**Comment by Nullarity** [comment]
ясно, тогда боюсь нужно кому-то уже на месте поработать с отладчиком, выяснить в чем проблема.

**Comment by Linda4ka** [comment]
Ладно, передам @SvetlanaRes .

**Comment by SvetlanaRes** [comment]
Понятно. Надо разбираться...
