### ISSUE TITLE
Предложение показывать остатки по всем складам

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#300]
При анализе складских остатков можно увидеть только что есть на одном складе. Чтобы получить на данный момент полную картину, нужно переформировать отчет по складу  и  в ручную сумировать каждую позицию по каждому складу. Было бы удобней получить отчет по всем складам по отдельности ( если не выбирать склад в заголовке) и колонку с общим количеством по позициям.
![image](https://user-images.githubusercontent.com/82500510/141465962-feb3d189-b868-402a-af59-84ef2d270416.png)
Также было бы удобно увидеть тут же и заказаные товары которые еще не были доставлены (как и резерв), да бы не заказать их еще раз.

Спасибо

**Comment by Nullarity** [comment]
Такая возможность есть, см. https://cont.help/faqwarehouse/
