### ISSUE TITLE
Как можно поменять формы печати для заказов, комерческих предложений и продаж?

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#342]
После отключение расширений не могу найти макеты в кофигураторе. Подскажите пожалуйста как менять форму.

**Comment by Nullarity** [comment]
За это отвечает обработка Print, https://cont.help/customization/#_9

**Comment by TeodorUn** [comment]
Спасибо. 
Можно ли создать также Footer для каждой из форм?

**Comment by TeodorUn** [comment]
Как открыть доступ  на редактирование макетов?

**Comment by Nullarity** [comment]
> Спасибо. Можно ли создать также Footer для каждой из форм?

уточните или перефразируйте пожалуйста вопрос.
