### ISSUE TITLE
Сколько будет дней отпуска при уходе в отпуск с 01.01.2022 по 05.01.2022?

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#358]
При расчете отпускных за этот период, сколько бухгалтеру нужно учесть календарных дней отпуска? Считаем, что 01.01.2022 официальный выходной (и это суббота). Очень желательно со ссылкой на законодательство.
Спасибо!

**Comment by Linda4ka** [comment]
Добрый день! В данном случае бухгалтер учитывает в расчет 4 дня, т.к согласно законодательства праздничные дни не учитываются ни количественно ни в оплате. Т.е. фактически сотрудник находясь в отпуске с 01.01.2022 по 05.01.2022 получит оплату за 4 календарных дня. В данном случае то что 01.01.2022 это суббота, в расчет не берется. В случае, если бы 01.01.2022 не был бы официальным праздничным днем, а просто субботой, то сотрудник получил бы расчет за 5 календарных дней.

**Comment by grumagargler** [comment]
Спасибо, а есть ссылка на законодательство?

**Comment by grumagargler** [comment]
Подскажите еще пожалуйста, при расчете дневного расчетного показателя отпускных:
![image](https://user-images.githubusercontent.com/15623029/147100501-dc1718d1-c80f-4690-8991-725fd43ba205.png)
Правильно, что в кол-во праздничных дней, должны войти и те праздники, что выпали на выходные дни?
