### ISSUE TITLE
Изменения в наименовании банков 

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#363]
Добрый день! В связи с изменением в наименовании некоторых банков, необходимо внести изменения в справочник Банки.
BC "Mobiasbanca - Groupe Societe Generale" S.A. Chisinau теперь BC Mobiasbanca OTP Group SA
BC "Eximbank" S.A. Gruppo Veneto Banca Chisinau теперь BC Eximbank SA Grupul Intesa Sanpaolo

**Comment by Nullarity** [comment]
Спасибо!
