### ISSUE TITLE
Прием на работу, не привычная последовательность в меню

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#37]
Просьба рассмотреть возможность переноса справочника Физ.лица на закладку Сотрудники, в раздел Кадры и установить этот справочник перед документом  Приемы на работу. Так точно будет понятно в какой последовательности необходимо вводить данные для заполнения. В нынешнем виде очень неудобно и не совсем понятно..

**Comment by Nullarity** [comment]
Подскажите пожалуйста, с какой проблемой вы столкнулись, потому что справочник сотрудники автоматически синхронизируется с физлицами, и отдельно вводить информацию в этот справочник надобности нет (при вводе сотрудника, физлицо создается автоматом).
Обычно, в меню объекты располагаются по частотности использования, а не последовательности ввода данных. Опишите пожалуйста ваш сценарий, что хотелось сделать и что вызвало трудности.

**Comment by Linda4ka** [comment]
Зайдя на закладку Сотрудники, как ни странно, но первым делом нажимаешь ни на Сотрудника, а на Прием на работу. Зайдя в документ, ты начинаешь по цепочке создавать и создавать, забывая зачем вообще зашел. Либо тогда документ Сотрудники поставьте перед документом Прием на работу, либо Физ.лица. Если уж я, зная программу пошла неправильным путем, то человек впервые ее увидевший точно будет не в восторге. А бухгалтера люди ранимые и нервные,,,,

**Comment by grumagargler** [comment]
И всё таки, что вы хотели сделать и что не получилось, что было не очевидно и непонятно? Если вам требовалось принять сотрудника на работу, то вы все правильно сделали, открыли приказы о приеме и начали по ходу дела создавать нужные элементы, все правильно. Видимо в этом процессе что-то пошло не так? Я тоже очень переживаю за нервную систему бухгалтеров, поэтому тут очень важен сценарий работы, что хотелось и что не получилось.

**Comment by Nullarity** [comment]
И всё таки, что вы хотели сделать и что не получилось, что было не очевидно и непонятно? Если вам требовалось принять сотрудника на работу, то вы все правильно сделали, открыли приказы о приеме и начали по ходу дела создавать нужные элементы, все правильно. Видимо в этом процессе что-то пошло не так? Я тоже очень переживаю за нервную систему бухгалтеров, поэтому тут очень важен сценарий работы, что хотелось и что не получилось.

**Comment by Linda4ka** [comment]
Получилось все, но если делать через Прием на работу, цепочка получается очень длинная и не удобная. Проще делать пошагово: - физические лица
                 - создание сотрудника
                 -  прием на работу, разными документами. А если все эти документы будут идти по порядку и на одной закладке - это вообще будет отлично. Не работа, а удовольствие. Это с точки зрения бухгалтера.Если мы хотим продвинуть продукт на рынок, не должно быть длинных цепочек, все должно быть предельно просто.

**Comment by SvetlanaRes** [comment]
На самом деле вопрос/предложение в том, чтобы справочник Сотрудники был расположен над Прием на работу )
![image](https://user-images.githubusercontent.com/82224240/118993784-7a1abf80-b98e-11eb-850d-fec5147023d8.png)

**Comment by Nullarity** [comment]
но ведь цепочка Сотрудники / Заработная плата практически равносилен Сотрудники / Приемы на работу. Откройте пожалуйста журнал Заработная плата, посмотрите, от-туда можно ввести и прием на работу и другие документы.

**Comment by SvetlanaRes** [comment]
Вопрос только в визуализации - отображении последовательности Сотрудник, Прием на работу и т.п. в интерфейсе
