### ISSUE TITLE
банковская выписка при перечислении зп на карту

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#370]
при проведении выписки по выплате заработной платы необходима расшифровка по сотрудникам (в связи с тем что выплата зачастую производится частями)

**Comment by Nullarity** [comment]
А можете чуть подробней? Выплата ЗП сама делает проводки по банку (и попадает в журнал банк).

**Comment by vizirina** [comment]
В 4.0 в документе Банковская операция: перечисление з/п есть возможность расшифровки
 общей перечисленной суммы по сотрудникам

**Comment by vizirina** [comment]
есть необходимость запретить непосредственное удаление документов по вводу остатков

**Comment by SvetlanaRes** [comment]
В течение месяца есть необходимость выплачивать/выдавать сотрудникам некоторые суммы.
В системе есть вид операции Аванс по ЗП, но по каким-то причинам при загрузки выписки данный вид выбрать нет возможности.
На самом деле, нашли вариант - вручную в банковской операции добавлять аналитику по сотрудникам.

**Comment by Nullarity** [comment]
Движения по банку делает сам документ Выплата ЗП или Авансы по ЗП.
При загрузке выписки, нужно снять галочку напротив суммы выплаты ЗП, чтобы не продублировать сумму.

**Comment by SvetlanaRes** [comment]
@Nullarity благодарю за подсказку, попробуем...
