### ISSUE TITLE
Загрузка-выгрузка накладных в е-фактура

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#375]
Выписаны две накладные, файл выгрузки загрузился в е-фактура без проблем, подписали электронно. При загрузке файла из е-фактура выдает ошибку
![1642765331453](https://user-images.githubusercontent.com/84189282/150521942-4234a345-3fcd-4683-b89a-2786047dd1f8.jpeg)
(файл выгрузки из е-ф отправлен по е-майлу)

**Comment by Nullarity** [comment]
система пытается показать ошибку какуе-то и не может (ошибкой является то, что не удается показать сообщение об ошибке). Можете на месте в отладке посмотреть что за ошибка должна быть выведена, или выслать мне базу для диагностики?

**Comment by vizirina** [comment]
Комментарий программиста: Чтение файла выписки и его обработка реализованы в фоновом задании. При этом сам файл передается через временное хранилище и в фоновом задании пытается его прочитать:
Модуль объекта обработки LoadInvoices, строка 33
xml.SetString ( GetStringFromBinaryData ( GetFromTempStorage ( Parameters.Address ) ) );
Но в фоновом задании файл из временного хранилища сеанса, в котором запустили это фоновое задание, не читается. GetFromTempStorage ( Parameters.Address ) выдает undefined.
Соответственно GetStringFromBinaryData ( GetFromTempStorage ( Parameters.Address ) )  выдает ошибку и не доходит до момента, где по этому адресу во временное хранилище фоновым заданием должна была выгрузиться таблица:
PutToTempStorage ( Invoices.Unload (), Parameters.Address );
В итоге в форме обработки в процедуре loadTable мы получаем изначальный бинарный файл выписки в
table = GetFromTempStorage ( Address );
а не таблицу, которая должна была быть туда помещена при нормальном завершении фонового задания. Как вариант - передавать в само фоновое задание бинарный файл не через временное хранилище, а параметром.

**Comment by vizirina** [comment]
Просит уточнить, что делать?

**Comment by Nullarity** [comment]
Попросите пожалуйста программиста включить режим тестирования, находится в меню / Настройки / Система / Разработчик / Тестирование. После этого, нужно перезапустить программу и попробовать повторить операцию загрузки файла, с остановкой в процедуре showMessages (из картинки выше) и посмотреть, какая ошибка возникла при загрузке.

**Comment by RebelVMR** [comment]
Здравствуйте. Там ошибка не из-за того, что не получается вывести сообщение об ошибке. В форме обработки LoadInvoices в строке 99 (Object.Invoices.Load ( table )) пытается загрузить в табличную часть бинарный файл (и выдает ошибку о несоответствии типов). Т.е изначальный xml файл выписки, а не результат обработки этого файла в фоновом задании. Я постарался описать как смог то, что увидел. В комментарии выше

**Comment by Nullarity** [comment]
А есть возможность выслать мне базу и файл?

**Comment by vizirina** [comment]
Здравствуйте, Дмитрий. Мы со Светланой сегодня обсудили эту проблему и  решили в понедельник еще раз провести процедуру выгрузки/загрузки, возможно ошибка где-то на этапе выписки НН. Уже по результатам отпишусь. Хороших выходных

**Comment by Nullarity** [comment]
@RebelVMR вероятно обнаружил ошибку, мне бы исправить, но хотелось бы не вслепую, под рукой нет именно файлов для загрузки, чтобы проверить. В общем если не получится, высылайте, я исправлю.

**Comment by vizirina** [comment]
Здравствуйте, Дмитрий. У нас не получилось с е-фактурой, та же ошибка. Отправили Вам на е-мейл файлы загрузки/выгрузки и ссылку на базу. Удачи. Спасибо

**Comment by Nullarity** [comment]
@vizirina @RebelVMR  прикладываю исправленную обработку, по возможности, замените существующую внутри конфигурации, и проверьте загрузку. Я загрузку проверял, ошибок нет, но и документы для обновления номеров небыли обнаружены. Уточните пожалуйста, откуда делалась выгрузка и какого документа? Если есть возможность посмотреть на месте через отладку, почему не отработала загрузка, и если там моя ошибка, то сообщить мне, было бы здорово.
Заранее спасибо!
[LoadInvoices.epf.zip](https://github.com/Contabilizare/c5/files/8075866/LoadInvoices.epf.zip)

**Comment by Nullarity** [comment]
> Здравствуйте. Там ошибка не из-за того, что не получается вывести сообщение об ошибке. В форме обработки LoadInvoices в строке 99 (Object.Invoices.Load ( table )) пытается загрузить в табличную часть бинарный файл (и выдает ошибку о несоответствии типов). Т.е изначальный xml файл выписки, а не результат обработки этого файла в фоновом задании. Я постарался описать как смог то, что увидел. В комментарии выше

вы правы, ошибка в получении файла по адресу временного хранилища, спасибо!
Ошибку исправил, см. вложение в предыдущем сообщении.

**Comment by vizirina** [comment]
Сегодня осуществили загрузку-выгрузку накладных в е-фактура, единственный момент - при формировании накладной из док-та Реализация программа автоматически генерирует номер, следующий за предыдущей выписанной фактурой, как правило эти номера уже существуют в базе и программа не дает записать документ, с пометкой что номер неактуален

**Comment by Nullarity** [comment]
@vizirina помогите пожалуйста разобраться, вы писали:

> при формировании накладной из док-та Реализация программа автоматически генерирует номер, следующий за предыдущей выписанной фактурой

Я правильно понимаю, что новая НН сразу содержит какой-то номер в этом поле?
![image](https://user-images.githubusercontent.com/28710693/156000229-55975b4c-3079-4262-8aaf-72576b25b1a1.png)

Если так, это очень странно. У вас задан диапазон, указано что это электронные накладные?
![image](https://user-images.githubusercontent.com/28710693/156000460-003920b2-8b86-42bb-b841-734a13e4d852.png)

**Comment by vizirina** [comment]
Отправила на е-мейл скрин, чтобы было наглядно формирование накладной. Диапазон задан, указано, что е-фактура. При попытке записать документ появлялось такое сообщение. Сохранить док получалось только если убирала  серию. Сегодня уже все отрабатывает, не понимаю что произошло
