### ISSUE TITLE
Настройка журнала НН

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#377]
Как настроить список в журнале НН, чтобы покупатель отображался в колонке, а не только в качестве отбора/группировки?

**Comment by Nullarity** [comment]
Такой возможности к сожалению пока нет. Подскажите пожалуйста жизненный сценарий, при котором у вас возникла такая потребность (в частности, чем для этой же задачи неудобен список Реализации, там отдельной пиктограмкой отображается статус НН)?
Спасибо!

**Comment by vizirina** [comment]
Спасибо за подсказку, разобрались - "чем для этой же задачи неудобен список Реализации" - на данном этапе достаточно

**Comment by Nullarity** [comment]
Если проблемка решилась, закрывайте ее пожалуйста, а то у нас их много, чтобы путаться ;-)
