### ISSUE TITLE
Подлежит ли сокращению предпраздничный день, если праздник выпадает на субботу?

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#378]
(график - пятидневка)

**Comment by Linda4ka** [comment]
Добрый день! Да, подлежит. Не подлежит в том случае, если праздник попадает на воскресенье. Во всех остальных случаях Да!

**Comment by SvetlanaRes** [comment]
Но, по-моему, еще зависит от рабочих часов. Для сотрудников с графиком работы от 4 и менее часов - нет предпраздничных дней, т.е. для них на 1 час не уменьшается предпраздничный день.
@Linda4ka так?

**Comment by Nullarity** [comment]
@SvetlanaRes вроде бы предпраздничный день касается всех сотрудников (ведь праздник для всех).

**Comment by Linda4ka** [comment]
Сокращенный предпраздничный день касается лишь сотрудников с 8-ми часовым рабочим графиком. Если у работника 7-ми часовой и ниже их это не касается. Разве что по усмотрению руководства, но это неофициально.

**Comment by Nullarity** [comment]
> Сокращенный предпраздничный день касается лишь сотрудников с 8-ми часовым рабочим графиком. Если у работника 7-ми часовой и ниже их это не касается. Разве что по усмотрению руководства, но это неофициально.

А можете предоставить ссылку на источник этого определения? Не идет ли в данном случае речь о другом характере работы, о сдельной или пропорциональной форме оплаты труда, т.е. тогда, когда уменьшение рабочего времени на час таким сотрудникам, уменьшит их заработную плату. Другими словами, должно быть основание, почему сотрудникам с 8 часовым рабочим днем, идет сохранение заработной платы при сокращенном предпраздничном дне, а сотрудникам с 4 или 7 часовым рабочим днем - нет, при все той же системе оплаты труда, месячный оклад.

Спасибо.

**Comment by Linda4ka** [comment]
Трудовой кодекс РМ с последними изменениями CM 154/2003
Статья 102. Продолжительность работы накануне нерабочих  праздничных дней

(1) Продолжительность рабочего дня (смены), непосредственно предшествующего нерабочему праздничному дню, уменьшается не менее чем на один час для всех работников, кроме тех, кому были установлены сокращенная продолжительность рабочего времени согласно статье 96 или неполное рабочее время согласно статье 97.

(2) В случае, когда рабочий день, предшествующий нерабочему праздничному дню, переносится на другой день, сохраняется та же сокращенная продолжительность рабочего дня.
(3) Конкретная сокращенная продолжительность рабочего дня, непосредственно предшествующего нерабочему праздничному дню, предусмотренная в части (1), устанавливается коллективным трудовым договором, правилами внутреннего распорядка предприятия или приказом (распоряжением, решением, постановлением) работодателя, изданным после предварительной консультации с представителями работников.

(4) На непрерывно действующих предприятиях и на некоторых непрерывных работах, где продолжительность рабочего дня (смены), непосредственно предшествующего нерабочему праздничному дню, не может быть сокращена, час/часы работы, которые невозможно сократить, считаются сверхурочной работой.


Статья 96. Сокращенная продолжительность рабочего

                    времени

(1) Для отдельных категорий работников в зависимости от возраста, состояния здоровья, условий работы и других обстоятельств в соответствии с действующим законодательством и индивидуальным трудовым договором устанавливается сокращенная продолжительность рабочего времени.

(2) Сокращенная недельная продолжительность рабочего времени составляет:
a) 24 часа – для работников в возрасте от пятнадцати до шестнадцати лет;
b) 35 часов – для работников в возрасте от шестнадцати до восемнадцати лет;
c) 35 часов – для работников, занятых на работах с вредными условиями труда, согласно перечню, утвержденному Правительством.
(3) Для отдельных категорий работников, труд которых требует повышенных интеллектуальных и психо-эмоциональных усилий, продолжительность рабочего времени устанавливается Правительством и не может превышать 35 часов в неделю.
(4) Для лиц с тяжелым и выраженным ограничением возможностей (не имеющих права на большие льготы) устанавливается сокращенная продолжительность рабочего времени – 30 часов в неделю без ущемления права на оплату труда и других прав, предусмотренных действующим законодательством.

Статья 97. Неполное рабочее время (частичная занятость)

(1) Работодатель может принимать на работу работников на условиях неполного рабочего дня или неполной рабочей недели (с частичной занятостью) с указанием конкретной продолжительности неполного рабочего времени в индивидуальном трудовом договоре в соответствии с положениями пункта l) части (1) статьи 49.
(2) С согласия обеих сторон неполное рабочее время может устанавливаться и после заключения индивидуального трудового договора. По просьбе беременной женщины, работника, имеющего детей в возрасте до десяти лет или детей с ограниченными возможностями (в том числе находящихся под его опекой), или работника, осуществляющего уход за больным членом семьи в соответствии с медицинским заключением, работодатель обязан установить для них неполный рабочий день или неполную рабочую неделю.
(3) Оплата труда на условиях частичной занятости производится пропорционально отработанному времени или в зависимости от объема выполненных работ.

**Comment by Linda4ka** [comment]
Исходя из статей 96 и 97, все у кого продолжительность рабочего времени меньше 8 часов в день/40 часов  в неделю, не подпадают под сокращение рабочего времени в предпраздничный день. И согласно 102 статье в предпраздничный день время работы может быть сокращено минимум на 1 час, т.е.  руководство предприятия может сократить это время еще больше.

**Comment by Nullarity** [comment]
Спасибо!
