### ISSUE TITLE
Налоги по зарплате

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#39]
При первоначальной загрузке, на закладке Сотрудники, в разделе Зарплата - Налоги, при открытии обнаруживаются неправильные ставки по налогам с зарплаты. Данные только на 2018 год. Новых данных, на 2021 год нет. Необходимо чтобы при первоначальной загрузке программы данные были актуальны на момент начала работы.

**Comment by grumagargler** [comment]
Вы не могли бы предоставить эти данные?

**Comment by Linda4ka** [comment]
Удержания с работника 2021
 - Медицинское страхование - 9 % 
 - Подоходный налог - 12%
Удержания за счет работодателя 2021
 - Социальный фонд - 23%

**Comment by Nullarity** [comment]
Подскажите пожалуйста, вы писали:

> Социальный фонд - 23%

точно 23, не 24?

Спасибо!

**Comment by SvetlanaRes** [comment]
> точно 23, не 24?

24%. Наверное, опечатка...
