### ISSUE TITLE
Обновить классификатор освобождений

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#40]
При первоначальной загрузке программы, на закладке Сотрудники, в разделе Зарплата - Освобождения, обнаруживаются неправильные суммы освобождений. Нет изменений, вступивших в силу с 01.01.2021 года. Необходимо, чтобы при первоначальном запуске программы, данные были актуальны на момент начала работы.

**Comment by grumagargler** [comment]
Вы не могли бы предоставить эти данные?

**Comment by Linda4ka** [comment]
С 01.01.2021 действуют следующие виды  и суммы освобождений: Личное (P) 25200 лей/2100 лей вместо 24000 лей
Личное повышенное(M) 30000 лей/2500 лей
Освобождение на супруга/супругу повышенное(Sm) 18900 лей/1575 лей
На иждивенца(N) 4500 лей/ 375 лей вместо 3000 лей
На иждивенца инвалида с детства (H) 18900 лей/ 1575 лей вместо 18000 лей
Освобождение на супругу/супруга (S) - упразднено. Суммы указаны за год/месяц.
