### ISSUE TITLE
Субсчета

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#407]
Добрый день! Для более корректной работы бухгалтерии, просим добавить в следующем обновлении следующие субсчета: 
224,41 Прочие текущие авансы выданные внутри страны(леевый счет) Alte avansuri acordate curente in tara   A
224,42 Прочие текущие авансы выданные за рубежом (валютный) Alte avansuri acordate curente in strainatate A Валютный
537,11 Текущие целевые финансирование и поступление в стране Finantari si incasari cu distinatie speciala curente din tara P
537,21 Текущие целевые финансирование и поступления из-за рубежа Finantari si incasari cu destinatie speciala curente din strainatate  P Валютный
731,1 Расходы по подоходному налогу  cheltuieli privind impozitul pe venit A
731,2 Расходы по налогу на доход от операционной деятельности  Cheltuieli privind impozitul pe venit din activitatea operationala A
731,3 Прочие расходы по подоходному налогу  Alte cheltuieli privind impozit pe venit A
811,1 Прямые материальные затраты  Cheltuieli materiale curente A
811,2 Прямы затраты на оплату труда  Cheltuieli directe privind retribuirea muncii
811,3 Отчисления на социальное страхование  Cheltuieli directe privind asigurarile sociale si medicale A
811,4 Косвенные производственные затраты  Cheltuieli inderecte de productie
812,1 Затраты на материалы Cheltuieli materiale privind activitatile auxiliare
812,2 Затраты на оплату труда Cheltuieli cu retribuirea muncii privind activitatile auxiliare
812,3 Отчисления на соц страхование  Cheltuieli cu asigurarile sociale si medicale privind activitatile auxiliare
812,4 Косвенные производственные затраты  Cheltuieli indirecte privind activitatile auxiliare
Данные субсчета хоть и отсутствуют в плане счетов, но являются кране необходимыми для работы каждого бухгалтера. Позже добавлю еще несколько субсчетов.

**Comment by Nullarity** [comment]
Спасибо! Но для того, чтобы это стало возможным, укажите пожалуйста перевод на румынский, а также необходимые аналитические признаки (субконто). В связи с тем, что операция дополнения плана счетов связана с обновлением начальной и демо баз, желательно предоставить максимально полный список необходимых счетов.

**Comment by Linda4ka** [comment]
Ок! Сегодня, в течение дня, я сделаю что необходимо.

**Comment by Linda4ka** [comment]
Добрый день! В данном письме прикладываю список всех субсчетов в удобоваримом формате для добавления в 5.0
[Новый1.xls](https://github.com/Contabilizare/c5/files/8096366/1.xls)

**Comment by Linda4ka** [comment]
Спасибо @SvetlanaRes за подсказку)))

**Comment by Linda4ka** [comment]
Да, есть определенный момент неточности. 311 Уставный капитал 311,1 Уставной фонд 311,11 Уставной фонд в валюте. Скажу чтобы  исправили в плане счетов. Спасибо! А по 224 это я упустила. В плане правильно. Просто вносила наименование вручную.

**Comment by Nullarity** [comment]
В интернетах пишут что "уставнЫй" правильно, не знаете как правильно?

**Comment by Nullarity** [comment]
@Linda4ka еще вопрос, на картинке:
![image](https://user-images.githubusercontent.com/28710693/154716093-017a1314-200f-4fbc-ae35-c40aca620650.png)
счет 224.4 - это группа, внутри которой 224.41 и 224.42? Если да, тогда почему 311.1 и 311.2 не в группе, и насколько необходимо 2244 делать группой?
Спасибо!

**Comment by Linda4ka** [comment]
> В интернетах пишут что "уставнЫй" правильно, не знаете как правильно? 

Почиала в интернете, пишут что в финансовом случае все следует определять как Уставный!
