### ISSUE TITLE
Возврат Поставщику

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#410]
Есть ли возможность сделать возврат Поставщику без документа основания Поступление? ( в случае когда переход из одной программы в другую, как в нашем случае)

**Comment by Nullarity** [comment]
Да, введите, но не проводите, а только запишите поступление от поставщика, на основании которого потом сделайте  возврат.
Почему нельзя сделать проще, сделать доступной колонку "себестоимость"? Потому что в к5 документ возврата сейчас контролирует исходное поступление по кол-ву, составу и использованных в нем заявок и заказов поставщикам. Не хотелось бы отключать все эти функции для частного случая. Кроме этого, нередко остатки вводятся с детализаций по документам (в случае загрузки данных из старой базы при переходах) и этот документ поступления, который я попросил ввести, уже нередко есть в непроведенном виде, и по нему может быть остаток, который благополучно закроется вводом на основании.

**Comment by Linda4ka** [comment]
Отменили проведение Поступление и попробовали сделать Возврат. Не получилось, т.к программа не увидела документ Основание

**Comment by Nullarity** [comment]
Не могу воспроизвести, покажите пожалуйста картинку с ошибкой.

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/155082524-0203be83-c1bb-4a61-84d0-c16c89acbf8f.png)
![image](https://user-images.githubusercontent.com/84187165/155082614-44d4b431-ec6f-4989-b1ee-1d6620f482d9.png)
Тот самый вариант когда документ Поступление товара не проведен. При формировании Возврата документ Основание не виден.
![image](https://user-images.githubusercontent.com/84187165/155083076-4c1c9c02-e582-4fc6-be37-d5cd0c0c0ac5.png)
![image](https://user-images.githubusercontent.com/84187165/155083211-cd42fc8b-d670-4d58-80cc-931425044689.png)
И вариант когда Поступление товара проведен. Сделать возврат не составляет никакого труда.

**Comment by Nullarity** [comment]
Спасибо. Я имел в виду другой сценарий: После того, как вы записали Поступление, не закрывая его, сверлу на панели есть меню Создать на основании. Через это меню можно ввести возврат. Либо, через такое же меню можно ввести возврат из списка поступлений.

**Comment by vizirina** [comment]
Даже при таком сценарии документ Поступление должен быть проведенным, иначе при выборе команды Добавить из поступления программа не видит документ-основание

**Comment by Nullarity** [comment]
@SvetlanaRes помоги пожалуйста разобраться, я пишу про ввод на основании, а тут опять "Добавить из поступления" ((

**Comment by Nullarity** [comment]
@vizirina прилагаю ролик

https://user-images.githubusercontent.com/28710693/155150402-f5acb35c-984f-4b2a-8b88-e6d931d088b1.mp4

**Comment by SvetlanaRes** [comment]
@Nullarity делаем также. У нас пустой документ. В поступлении есть номенклатурные позиции, в возврате пустая таб.часть.

**Comment by Nullarity** [comment]
а вы случайно уже не вернули его?

**Comment by Nullarity** [comment]
@SvetlanaRes при вводе, возврат смотрит, сколько позиций осталось вернуть, и если допустим вы уже делали до этого возврат, то могло получиться так, что по документу поступления возвращать уже нечего. Если это не так, значит что-то непредвиденное, вышлите базу (или скажите какой товар вернуть в той базе, что у меня уже есть).
