### ISSUE TITLE
Декларация по НДС

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#414]
Здравствуйте, @Nullarity . Вчера столкнулись с проблемой по декларации по НДС - устаревшая форма (в связи с этим отправлем Вам xml-файл актуального образца на е-мейл). Второе - подскажите, есть ли возможность выгрузки данной декларации из 5.0 для загрузки в фиск?

**Comment by Nullarity** [comment]
Спасибо!
Над этой формой прямо сейчас идет работа, помню, что скоро ее сдавать.

**Comment by Nullarity** [comment]
@vizirina
> декларации по НДС - устаревшая форма

отправьте заодно и mxl пожалуйста.

**Comment by Nullarity** [comment]
70% готовности

**Comment by vizirina** [comment]
В Декларации по НДС приложение №2 заполняется только 36 строк (за январь должно быть 138), соответственно общая стоимость продаж и сумма по НДС расчитывается только по этим позициям.
