### ISSUE TITLE
Загрузка банковской выписки

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#416]
Здравствуйте @Nullarity . Просьба проверить следующую ситуацию: при проведении банковской выписки, если есть операции по 531 счету - выплата ЗП, каким-то образом цепляет одну из операций Оплата покупателя - в счет учета покупателя указывает 5311. Хотя при загрузке все операции ложатся по счетам изначально правильно. (скрин от бухгалтера отправила на е-мейл)

**Comment by Nullarity** [comment]
К сожалению на присланной картинке очень сложно что-то рассмотреть, но в целом ситуация очень странная. Операцию по зп удаляете (или снимаете галочку) в банковской выписке при загрузке?

**Comment by vizirina** [comment]
Добрый день, по этому вопросу разобрались с программистом.

**Comment by vizirina** [comment]
Здравствуйте. Поторопилась закрыть тему, сегодня ситуация повторилась (отправила Вам скрины). Чтобы прояснить ситуацию: операций по начислению ЗП в базе не производится. Чисто загрузка файла банковской выписки, при которой приходы первоначально ложатся корректно по счетам (1). Затем в расходах при выборе счетов (2 и 3), если есть движение по 5311, то в приходах одна выписка перебрасывается на этот счет (4)

**Comment by Nullarity** [comment]
Спасибо за подробное описание, это помогло найти ошибку. Исправление войдет в грядущий релиз. Ошибка заключается в том (для информации, как ее обойти пока не выйдет релиз), что при изменении вида операции на вкладке Расходы, программа ошибочно устанавливает счет по умолчанию для данной операции, но не для таблицы Расходы, а для текущей строки таблицы Приходы.

**Comment by vizirina** [comment]
Супер. Спасибо.
