### ISSUE TITLE
Проблема обновления

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#417]
Попытка обновить демо базу с 22 релиза на 23 выдала следующее:
![image](https://user-images.githubusercontent.com/84187165/155694460-d93716e2-cfe2-4487-9b66-191d77741585.png)
![image](https://user-images.githubusercontent.com/84187165/155694553-c3a498df-77c7-497e-a864-90eff27a0f89.png)
В чем проблема?

**Comment by Nullarity** [comment]
Сложно сказать, возможно как-то криво загрузился файл обновления. Попробуйте просто загрузить прилагаемый файл с релизом (меню / Конфигурация / Загрузить конфигурацию из файла)
[1Cv8.cf.zip](https://github.com/Contabilizare/c5/files/8142096/1Cv8.cf.zip)

**Comment by vizirina** [comment]
Не удалось также обновить рабочую базу с 22 на 24 релиз, такая же ошибка. Очень нужно протестить декларацию по НДС

**Comment by Nullarity** [comment]
Нельзя обновиться с 22 на 24 сразу. Делайте последовательно. Загрузите приложенный файл, потом сможете стандартно обновиться на 24.

**Comment by vizirina** [comment]
Это понятно. Так и попытались, При обновлении с 22 на 23 появилось сообщение что файл не содержит обновлений для данной конфигурации

**Comment by Nullarity** [comment]
Я писал:

> Попробуйте просто загрузить прилагаемый файл с релизом (меню / Конфигурация / Загрузить конфигурацию из файла).

что-то не получилось сделать?

**Comment by Nullarity** [comment]
@vizirina, пожалуйста, отвечайте на мои вопросы или закрывайте тему. Спасибо.

**Comment by vizirina** [comment]
Извините, я не сижу на переписке, у меня есть мои непосредственные обязанности. Отвечаю по мере возможности.

**Comment by vizirina** [comment]
Базу обновили, спасибо

**Comment by Nullarity** [comment]
@vizirina Мне кажется что общение по программным вопросам с разработчиком, тоже входит в эти обязанности. Если это не так, тогда прошу извинить. Качество моей поддержки также будет скорректировано, мне тоже есть чем заниматься.

**Comment by SvetlanaRes** [comment]
> @vizirina Мне кажется что общение по программным вопросам с разработчиком, тоже входит в эти обязанности. Если это не так, тогда прошу извинить. Качество моей поддержки также будет скорректировано, мне тоже есть чем заниматься.

@Nullarity Вы правы! Произошло недопонимание...
