### ISSUE TITLE
Разукомплектация

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#42]
При создании документа Разукомплектация и дальнейшего его сохранения программа выдает непредвиденную ошибку.
Текст ошибки следующий:
Ошибка при выполнении обработчика - 'Posting'
по причине:
Преобразование значения к типу Число не может быть выполнено
{Document.Disassembling.ManagerModule(379)}:	Collections.Distribute ( data.Quantity * data.Capacity, Table, "Quantity", "ProductQuantity" );
{Document.Disassembling.ManagerModule(207)}:	commitCost ( Env, items );
{Document.Disassembling.ManagerModule(28)}:		if ( not makeValues ( Env ) ) then
{Document.Disassembling.ObjectModule(35)}:	Cancel = not Documents.Disassembling.Post ( env );
Что это такое и в чем причина. Если причина в неправильном заполнении документа, прошу пояснить.Спасибо!

**Comment by Nullarity** [comment]
не-не, что бы вы не делали, таких ошибок быть не должно, будем разбираться, спасибо!

**Comment by Linda4ka** [comment]
Смоделировала ситуацию с введенным флагом Учитывать и без него. Без взведенного флага документ проводится, с введенным флагом выдает ошибку. Если это чем-то поможет, буду рада.

**Comment by Nullarity** [comment]
о супер, спасибо, конечно помогло!

**Comment by Nullarity** [comment]
Покажите пожалуйста вашу разборку, которая дает ошибку, скриншотом, я не уверен, что в точности воспроизвел ситуацию.

**Comment by Nullarity** [comment]
@Linda4ka отзовитесь, нужна ваша помощь
