### ISSUE TITLE
Декларация по НДС

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#422]
В Декларации по НДС приложение №2 заполняется только 36 строк (за январь должно быть 138), соответственно общая стоимость продаж и сумма по НДС расчитывается только по этим позициям.

**Comment by Nullarity** [comment]
Уточните пожалуйста, отчет был сформирован путем переоформления уже существовавшего в базе, или путем добавления нового? Так как отчет TVA12 был модифицирован в новом релизе, для использования новой версии, нужно добавить новый отчет в базу, старый отчет (в связи с тем, что там могут быть уже введены пользовательские данные) не обновляется автоматически. Если старый вам не нужен, можете просто пометить его на удаление.

**Comment by vizirina** [comment]
Старый пометили на удаление, сформировали новый. Почему -то включил в Приложение №2 дополнительно 13 НН от 28.02

**Comment by Nullarity** [comment]
Попробуйте одну такую неправильную накладную поднять, это именно НН?

**Comment by Nullarity** [comment]
если нет времени сверять и вы уверены что в программе ошибка, вышлите базу, я сверю.

**Comment by Nullarity** [comment]
Спасибо, исправление придет со след. релизом, а тем временем, не могли бы проверить поправки, для этого нужно:
1. Открыть рег.отчеты
2. Встать на декларацию по ндс
3. Нажать F7
4. На вкладке Модуль, заменить текст на модуля на содержимое прикрепленного файла
5. Нажать на Сохранить и сформировать и посмотреть на результат

Спасибо!
[TVA12.txt](https://github.com/Contabilizare/c5/files/8162218/TVA12.txt)

**Comment by Nullarity** [comment]
Я ответил на письмо.

> Касаемо результата - можно уточнить, какие поправки должны внестись? Цифры, если что, не изменились

эти, вы писали:

> в декларации стр.1 и 2 попадает только сумма по накладным и НДС с них. Не попала сумма полученных авансов+НДС

**Comment by vizirina** [comment]
[VAT.txt](https://github.com/Contabilizare/c5/files/8212650/VAT.txt)
Здравствуйте. Это текстовый файл с полным текстом кода.
Изменения в ячейке B29. (11.1). В запросе вместо того, что было поставили
	|// @Advances
	|select Sum(General.Amount) as Amount
	|from AccountingRegister.General as General
	|where 
	|	General.Period Between &DateStart AND &DateEnd
	|	AND General.AccountDr in hierarchy ( &Account2252 )
	|	AND General.Company = &Company
	|	AND General.Amount > 0
	|;
Тут параметром выбрали счет, так как в нашей базе нет того, который был до этого.
Этот параметр используется и для ячеек A21 и B21.
В запросе: 
	|// @AdvancesTaken
	|select General.AmountTurnoverCr - General.AmountTurnoverDr as Amount
	|from AccountingRegister.General.Turnovers ( &DateStart, &DateEnd, , Account in hierarchy ( value ( ChartOfAccounts.General._523 ) ), , Company = &Company, , ) as General
	|;
	|// @VATTaken
	|select General.AmountTurnoverDr as Amount
	|from AccountingRegister.General.Turnovers ( &DateStart, &DateEnd, , Account = &Account2252, , Company = &Company, , ) as General
	|";
В заполнении: 
	table = vats.Copy ( new Structure ( "Type, Operation", Enums.VAT.Standart, 0 ) );
	FieldsValues [ "A21" ] = table.Total ( "Amount" ) + Env.AdvancesTaken.Amount - Env.VATTaken.Amount;
	FieldsValues [ "B21" ] = table.Total ( "VAT" ) + Env.VATTaken.Amount;
	
И для ячейки B37 (21) изменение в том, что попадает только не отрицательная сумма.
Procedure B37 ()

	result = get ( "B34" ) - get ( "B28" ) - get ( "B38" );
	result = ? ( result < 0, 0, result );

EndProcedure
Возможно лучше реализовать по-другому, но старались быстрее выполнить. За основу в заполнении сверялись с заполнением в 4-ке.

**Comment by Nullarity** [comment]
Спасибо!
