### ISSUE TITLE
Загрузка курсов валют

### ISSUE THREAD

**Issue by SvetlanaRes** [Contabilizare/c5#428]
Есть ли возможность автоматической загрузки курсов валют?

**Comment by Nullarity** [comment]
Имеется ввиду это или что-то другое?

![image](https://user-images.githubusercontent.com/28710693/156964367-8b87e101-917a-401d-a9f2-edfe41d1dbaa.png)

**Comment by SvetlanaRes** [comment]
@Nullarity благодарю! Странно, что не заметила ))
Все работает! Спасибо!
