### ISSUE TITLE
Номенклатура

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#43]
Можно ли в документ Номенклатура, в область где указано Услуга,Продукция,Бланк добавит еще и окошко Основное сырье и материалы. Это необходимо для следующего: иногда один вид номенклатуры может быть использован и как Продукция и как Материал.(Например :Животноводство. Они используют куры, мясо свиньи, кролики и т.д. и как продукцию и для процесса разукомплектации как материал, для последующей продажи по частям. Именно для правильного учета, при создании Номенклатуры, они смогли бы сразу отмечать что это Продукция  или  Материал. Если будет необходимо более точный пример, сообщите. Спасибо!

**Comment by Nullarity** [comment]
Методика тут такая, в справочник Номенклатура мы заводим уникальные сущности с точки зрения объектов реального мира. То есть курица - она хоть товар, хоть материал - все равно курица (в противном случае, в справочник пришлось занести две курицы и как-то их потом различать). А уже как мы учитываем сущность - зависит от бизнес-процессов. Сегодня мы ее продаем, завтра используем в производстве, с т.з. номенклатуры, это будет одна позиция (если физически это тот же объект). Принадлежность номенклатуры к тому или иному разделу учета определяется счетом учета на уровне документов. Например, можно ввести Поступление и для одной строки в таблице, указать для курицы 2171 счет, для другой - 2111 (как пример).

**Comment by Linda4ka** [comment]
Ок, если так, тогда возможно отпадает в этом необходимость. Мы просто делим приход по счетам учета. Спасибо!
P.S.
А тогда для чего необходимы данные окошки (Услуга, Продукция,Бланк), чтоб до конца понять структуру документа и стоит ли на это пристально обращать внимание?!

**Comment by Nullarity** [comment]
> А тогда для чего необходимы данные окошки

хороший вопрос, я понял что тут конфузит. Эти галочки работают по принципу "дополнительной информации". Например, галка услуга определяет что актив не физический, и его нельзя будет выбрать в таблицу  Товары документа поступления и других, также, при нажатии на услугу, с формы справочника скрываются некоторые не релевантные для услуг поля (упаковка например).
Продукция - примерно также, при установке флага, форма изменяется, и становятся доступными актуальные для продукции поля (при этом учитывать этот элемент как материал - остается).
Тоже самое с бланками, при установке галочки - там появляются свои дополнительные реквизиты.

**Comment by Linda4ka** [comment]
Если я правильно поняла, то это чисто информативные данные?

**Comment by Nullarity** [comment]
Ну почти. Они как-бы являются надстройкой над объектом, чтобы с ним было легче работать в программе. Например, при поступлении товаров, список выбора товаров не будет содержать услуг, при выпуске продукции (документ пока с стадии разработки) список выпускаемой продукции будет ограничен только номенклатурой, у которой установлена галка Продукция, в документе поступления, создать диапазон номером можно будет только если для номенклатуры установлен флаг Бланк и так далее.

**Comment by Linda4ka** [comment]
Ладно, поработаем и посмотрим. Может не все так страшно! Спасибо!
