### ISSUE TITLE
Изменение даты в журнале Заработная плата

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#444]
![image](https://user-images.githubusercontent.com/84187165/159015017-60379266-c277-4ab7-b4c9-8a400c3d6026.png)
Как сделать так чтобы в колонке Дата, дата документа отображалась как 31.01.2022, а не как сейчас?

**Comment by Nullarity** [comment]
Пока никак. Поделитесь пожалуйста практическим опытом, текущий вид больше непривычен или неудобен? Текущее представление выполнено из соображений, что зарплатные документы чаще анализируются с месяца, потом даты, в отличие например расходных накладных. Если это не удобно, подскажите пожалуйста решаемую задачу (а не просто действие), которую стало неудобно выполнять с текущим представлением даты операции.
Спасибо!

**Comment by Linda4ka** [comment]
Спасибо, решили вопрос самостоятельно!
