### ISSUE TITLE
Расходы будущих периодов

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#447]
Как сделать так, чтобы при внесении товара на закладку Услуги, в списке предопределенных счетов появился 26110

**Comment by Nullarity** [comment]
Вы можете войти в меню Бухгалтерия / Счета в документах / Товары, и там добавить запись для конкретного элемента или группы, примерно так:
![image](https://user-images.githubusercontent.com/28710693/159405219-2d7536de-8ab2-436e-bbce-768f57e68995.png)
после этого, при выборе такой услуги в поступлении, счет будет установлен автоматически. Возможность выбора счета вручную, добавлю в след. релиз.

**Comment by Linda4ka** [comment]
Спасибо, сделали!
