### ISSUE TITLE
Права доступа

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#449]
Подскажите пожалуйста, есть ли возможность ограничить пользователям доступ к редактированию документов за предыдущий период (который закрыт и отчеты сданы)?

**Comment by Nullarity** [comment]
День добрый! Да, это делается в меню Настройки / Права к документам. Документации под рукой нет, я ее готовлю. В грядущем релизе в этом механизме также будут улучшения.

**Comment by vizirina** [comment]
Доброе утро. Пробовали через  Настройки / Права к документам - не работает

**Comment by Nullarity** [comment]
https://cont.help/users/#_7

**Comment by vizirina** [comment]
Не работает. На почту отправлены скрины с файлами из закрытого периода, которые демонстрируют что система позволяет менять статус дока, перепроводить и т.п. (на примерах Реализация, Накладная, Оплата покупателя)

**Comment by Nullarity** [comment]
Спасибо за предоставленную информацию, но к сожалению, мне не удается воспроизвести. Уточните пожалуйста, у вас случайно в справочнике пользователей, ваш профиль не создан дважды? Я просто смотрю что в заголовке программы один пользователь, а создание прав доступа, делается для другого пользователя (имя фамилия поменяны местами).
И еще, вы не могли бы проверить работу механизма на последней версии программы.
Спасибо!

**Comment by Nullarity** [comment]
@vizirina удалось проверить?

**Comment by vizirina** [comment]
> @vizirina удалось проверить?

Пока нет. Еще не обновляли базу. Отпишусь по результатам сразу

**Comment by vizirina** [comment]
Вчера обновили базу. Сделала запрет на себя на определенный период - сработало. Спасибо. Вопрос закрываю
