### ISSUE TITLE
Дублирование  часов в предпраздничный день в табеле

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#465]
Столкнулись со следующей проблемой: на предприятии существует 2 графика работ: 1) - 8-ми часовой, для которого предусмотрен сокращенный предпраздничный день с 7 часами и 2) - 2х-часовой график. При создании праздничного дня 08,03,2022 и дальнейшем заполнении табеля, в предпраздничный день (07.03) - программа дублирует рабочие часы, т.е. вместо 7 проставляется 14 часов. А если создать еще один график, то часы утраиваются.
[скрин по графику.docx](https://github.com/Contabilizare/c5/files/8488755/default.docx)

**Comment by Nullarity** [comment]
Спасибо за информацию и пояснения, исправление войдет в грядущий релиз.
Есть ремарка на счет самой ошибки. Дело не отсутствии группировки, а в отсутствии одного условия соединения, вот так должен выглядеть правильный запрос:
```
// HolidaysRawData
select HolidaysList.Reference as Reference, HolidaysList.Day as Day,
    case when PreholidaysInHolidays.Day is null and Preholidays.Minutes > 0 then Preholidays.Day end as Preholiday,
	HolidaysList.Division as Division, Schedules.Schedule as Schedule
into HolidaysRawData
from InformationRegister.Holidays as HolidaysList
	//
	// Schedules
	//
	join InformationRegister.Schedules as Schedules
	on Schedules.Day = HolidaysList.Day
	and Schedules.Schedule.Holidays = HolidaysList.Reference
	//
	// Preholidays
	//
	join InformationRegister.Schedules as Preholidays
	on Preholidays.Day = dateadd ( HolidaysList.Day, day, -1 )
	and Preholidays.Schedule.Holidays = HolidaysList.Reference
	and Preholidays.Schedule = Schedules.Schedule // вот здесь не хватало условия
    //
    // PreholidaysInHolidays
    //
    left join InformationRegister.Holidays as PreholidaysInHolidays
    on PreholidaysInHolidays.Day = Preholidays.Day
	and PreholidaysInHolidays.Reference = Preholidays.Schedule.Holidays
where HolidaysList.Day between &DateStart and dateadd ( &DateEnd, day, 1 )
```

**Comment by Linda4ka** [comment]
Спасибо за ответ и пояснение. Ждем обновления!

**Comment by Nullarity** [comment]
Проверьте пожалуйста в 5.0.25.1

**Comment by Nullarity** [comment]
@Linda4ka удалось проверить?

**Comment by Linda4ka** [comment]
Добрый день! Была на больничном, проверить не смогла. Как проверю сообщу.

**Comment by Linda4ka** [comment]
Перестали проставляться 7 перед праздничным днем, хотя праздники заполнены.

**Comment by Nullarity** [comment]
провертьте пожалуйста, стоит ли у вас эта галочка в графике?
![image](https://user-images.githubusercontent.com/28710693/171428489-b69d97fe-89ad-4632-95df-d001b323f12b.png)

**Comment by Linda4ka** [comment]
Спасибо за информацию. Проверила, галочка не проставлена. Проставила, заполнила табель. Вопрос снят!
