### ISSUE TITLE
Ошибка в использовании параметра для вывода сообщений "подсистемы" Progress

### ISSUE THREAD

**Issue by slaxxals** [Contabilizare/c5#471]
* Ошибка в несоответствии имени передаваемого параметра `ShowMessage` в общую форму Progress, хотя сам параметр формы называется `ShowMessages`:

1. Параметр передается в форму Progress с ошибочным именем `ShowMessage`.
https://github.com/Contabilizare/c5/blob/7c86b97777c190219c93b5299ec8b368cf559507/c5/src/CommonModules/Progress/Module.bsl#L7
2. В форме Progress параметр называется `ShowMessages` https://github.com/Contabilizare/c5/blob/7c86b97777c190219c93b5299ec8b368cf559507/c5/src/CommonForms/Progress/Form.form#L669

* Ошибка в несоответствии типа передаваемого параметра в функцию Progress.Open, передается булево, требуется число. https://github.com/Contabilizare/c5/blob/7c86b97777c190219c93b5299ec8b368cf559507/c5/src/Catalogs/Tenants/Forms/New/Module.bsl#L34

**Comment by Nullarity** [comment]
Спасибо за информацию, будем разбираться!
