### ISSUE TITLE
Печатная форма накладной

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#472]
В печатной форме НН, полученной на сайте e-фактура по ранее загруженной туда накладной из нашей программы, есть проблемы:
 в печатную форму тянет юридический адрес контрагента в раздел Пункт разгрузки и Переадресовки, 
в наименовании товаров/ услуг отображает код номенклатуры, 
в 21 пункте (отметки) - генерирует непонятный код. 
(Экспериментировали с  ручным формированием фактуры - подобных вопросов не возникает. Файл отправила на е-мейл)

**Comment by Nullarity** [comment]
> При загрузке накладных в е-фактура в печатную форму тянет юридический адрес контрагента в раздел Пункт разгрузки и Переадресовки

Переформулируйте пожалуйста это предложение, мне не удается понять его смысл. Вы имели ввиду "В печатной форме НН, полученной на сайте e-фактура по ранее загруженной туда накладной из нашей программы, есть проблемы:..." ?

> в наименовании товаров/ услуг отображает код номенклатуры

Подскажите пожалуйста, это является каким-то нарушением или проблемой где-то в дальнейшем? Например, при продаже "Ботинки мужские" разных размеров, цветов и артикулов в одной накладной, наименованием будет "Ботинки мужские", а остальные данные - характеристиками и кодами, не являющиеся частью наименования изделия в терминах базы данных. Такие товары, было бы сложно приходовать покупателям, если бы все позиции назывались "Ботики мужские".

> в 21 пункте (отметки) - генерирует непонятный код.

Это внутренний код выгружаемого документа из нашей программы. Он нужен для того, чтобы при загрузке НН из ефактура, было возможным найти исходный документ в нашей базе и проставить ему присвоенный внешней системой номер. К сожалению я не знаю как это сделать иначе. Я проектировал этот алгоритм давно, возможно разработчики ефактура уже предусмотрели какое-то служебное для этого поле. Можете прозондировать? Вариант поиска по покупателю/сумме/дате не предлагать, это большое допущение.

А печатать накладную из программы неудобно?

**Comment by Nullarity** [comment]
>  контрагента в раздел Пункт разгрузки

Покажите пожалуйста картинку формы документа этой НН в базе, интересует значение указанное в поле Пункт разгрузки.

**Comment by Nullarity** [comment]
> в наименовании товаров/ услуг отображает код номенклатуры,

Более того, это они выводят код товара, мы со своей стороны выгружаем только наименование (с описанными выше характеристиками). Код товара, выгружается в ефактура в специально отведенное для этого поле в их файле. Если это проблема, возможно имеет смысл связаться с ними и спросить, почему они в наименовании, в печатной форме, выводят код + наименование.

**Comment by vizirina** [comment]
> > в наименовании товаров/ услуг отображает код номенклатуры,
> 
> Более того, это они выводят код товара, мы со своей стороны выгружаем только наименование (с описанными выше характеристиками). Код товара, выгружается в ефактура в специально отведенное для этого поле в их файле. Если это проблема, возможно имеет смысл связаться с ними и спросить, почему они в наименовании, в печатной форме, выводят код + наименование.

Позволю себе возразить - при создании накладной на сайте фиска вручную подобных проблем не возникает, ни с кодом ни с адресом. Вопрос про товарный код возник потому, что в 4.0 есть эта позиция, которая заполняется автоматически наряду с кодом номенклатуры и при ее очистке не отображается в фактуре.

**Comment by vizirina** [comment]
> > При загрузке накладных в е-фактура в печатную форму тянет юридический адрес контрагента в раздел Пункт разгрузки и Переадресовки
> 
> Переформулируйте пожалуйста это предложение, мне не удается понять его смысл. Вы имели ввиду "В печатной форме НН, полученной на сайте e-фактура по ранее загруженной туда накладной из нашей программы, есть проблемы:..." ?
> 
> > в наименовании товаров/ услуг отображает код номенклатуры
> 
> Подскажите пожалуйста, это является каким-то нарушением или проблемой где-то в дальнейшем? Например, при продаже "Ботинки мужские" разных размеров, цветов и артикулов в одной накладной, наименованием будет "Ботинки мужские", а остальные данные - характеристиками и кодами, не являющиеся частью наименования изделия в терминах базы данных. Такие товары, было бы сложно приходовать покупателям, если бы все позиции назывались "Ботики мужские".
> 
> > в 21 пункте (отметки) - генерирует непонятный код.
> 
> Это внутренний код выгружаемого документа из нашей программы. Он нужен для того, чтобы при загрузке НН из ефактура, было возможным найти исходный документ в нашей базе и проставить ему присвоенный внешней системой номер. К сожалению я не знаю как это сделать иначе. Я проектировал этот алгоритм давно, возможно разработчики ефактура уже предусмотрели какое-то служебное для этого поле. Можете прозондировать? Вариант поиска по покупателю/сумме/дате не предлагать, это большое допущение.
> 
> А печатать накладную из программы неудобно?

1. Переформулировала
2. Не думаю, что это это является нарушением, но из практики - были нарекания от клиентов
3. Касательно внутреннего кода тоже были вопросы от клиентов и даже просьба перевыписать накладную так, чтобы он не отображался 
4. Из программы печатать накладную нет смысла, потому что она без эл.подписей.

**Comment by vizirina** [comment]
> > контрагента в раздел Пункт разгрузки
> 
> Покажите пожалуйста картинку формы документа этой НН в базе, интересует значение указанное в поле Пункт разгрузки.

Скрины отправила на е-мейл

**Comment by Nullarity** [comment]
Я ознакомился. Первый скрин отличается от второго по тем, что во втором выбран адрес доставки. Адрес доставки в документе можно выбрать уде после того, как НН была создана. Поэтому я затрудняюсь точно подсказать, что происходило.
Я добавил в документацию описание принципа заполнения НН, ознакомьтесь пожалуйста, если поведение программы отличается от описания или сам дизайн программы по принципу заполнения вас не удовлетворяет, сообщите пожалуйста, будем улучшать. Ссылка на документацию: https://cont.help/d/InvoiceRecord

**Comment by vizirina** [comment]
Спасибо за полезную информацию, ознакомилась по указанной ссылке. Касательно адреса доставки выяснили опытным путем - если пункт разгрузки не соответствует, то можно изменить вручную или убрать совсем. Просто не очень удобно проверять и корректировать все накладные, когда их запланировано к выписке много (у нас бывает около ста и более за день).

**Comment by Nullarity** [comment]
@vizirina 
> Просто не очень удобно проверять и корректировать все накладные, когда их запланировано к выписке много (у нас бывает около ста и более за день).

Предложите пожалуйста свой сценарий, как сделать лучше.

**Comment by vizirina** [comment]
Честно говоря, пока затрудняюсь что-либо предложить. Практика покажет

**Comment by Nullarity** [comment]
Тогда может закроете эту тему, и потом создадите новую, если обнаружите другие неудобства/замечания?

**Comment by vizirina** [comment]
ок
