### ISSUE TITLE
Вопросы по начислению зарплаты

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#49]
Взялась рассчитать зарплату работнику за январь 2020 года. 1) % соц фонда с предприятия был указан неправильно, стоит 23%, а должно было быть 18%.
2) Зачем на закладке Расчеты показывать соц фонд, который уплачивает фирма. В данном случае удержаниями считаются только 6% и 4,5%( по состоянию на 2020 год) или 9% ( на сегодняшний день), а соц фонд 18%(по состоянию на 2020) и другие 4,5% мед, которые почему-то не фигурируют в этом списке, или 24%(на сегодняшний день), являются начислениями расходов предприятия. Поэтому,  надо сделать закладку Начисления, где будут указываться начисления, которые начисляются на зарплату.

**Comment by Nullarity** [comment]
> 1) % соц фонда с предприятия был указан неправильно, стоит 23%, а должно было быть 18%.

Это у нас войдет в блок по обновлению зп.


> 2) Зачем на закладке Расчеты показывать соц фонд, который уплачивает фирма

На этой вкладке показываются все расчеты выполненные по зарплате, а не только те, которые удерживаются у сотрудника. Так реализовано по двум причинам:
1. Для прозрачного отображения произведенных программой автоматических расчетов
2. Для возможности любой рассчитанный показатель отредактировать, или вовсе, ввести по новой. Например, в силу разного рода проблем (в том числе и программных), у заказчиков возникают ситуации, когда ЗП считает программа неверно, и если нет возможности откорректировать автоматически выполненные расчеты, пользователь считай "застрял", потому что начисление ЗП ключевой документ.

**Comment by Linda4ka** [comment]
2. Ну не все расчеты, 4,5%. оплачиваемые предприятием не фигурировали. Предлагаю сделать отдельно вкладку удержания, где будут указаны удержания с сотрудника и вкладку начисления, где будут видны начисления, которые уплачивает работодатель. Это будет информативно и круто.

**Comment by Nullarity** [comment]
Реализация данного пожелания идет в сильный разрез с текущей логикой работы программы и не представляется действительно необходимой в частотных сценариях.
