### ISSUE TITLE
В книге покупок не отображается серия входящего номера документа Поступление товаров

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#494]
Скины отправлены по емайлу

**Comment by Nullarity** [comment]
Покажите пожалуйста, что у вас на вкладке Дополнительно, у документа Поступление ТМЦ. Попробуйте перебить входящий номер, сохранить документ и сформировать отчет еще раз. Скажите, появится ли при этом серия?

**Comment by vizirina** [comment]
К сожалению нет. Отправила скрин

**Comment by Nullarity** [comment]
исправлено в 5.0.27.1
