### ISSUE TITLE
Как можно в программе организовать что-то на подобии Базы знаний?

### ISSUE THREAD

**Issue by SvetlanaRes** [Contabilizare/c5#50]
Как можно организовать базу знаний или часто задаваемые вопрос/ответы так, чтоб можно было комментировать или добавлять информацию?

**Comment by SvetlanaRes** [comment]
на сколько правильно использовать Проект/описание проекта и при необходимости комментировать - использовать обсуждение к проекту? или есть другие варианты?

**Comment by Nullarity** [comment]
база знаний - это справка cont.help, если есть что добавлять - пиши на почту, буду добавлять

**Comment by SvetlanaRes** [comment]
> база знаний - это справка cont.help, если есть что добавлять - пиши на почту, буду добавлять

вопрос в другом - компания хочет организовать у себя в базе свою базу знаний, например, по часто  задаваемым вопросам от клиентов, по вопросам внутриорганизационного характера, по специфики товаров/услуг, представляемых данной компанией. 
Вот и вопрос как это лучше сделать?

**Comment by Nullarity** [comment]
Понял. Для этого предназначена подсистема Документы.

**Comment by SvetlanaRes** [comment]
Хорошо. Спасибо. Посмотрю, когда будет реализовано.

**Comment by Nullarity** [comment]
Реализовано в 5.0.15.1 релизе
