### ISSUE TITLE
Входящий номер Таможенной декларации

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#509]
Сама таможенная декларация попадает в книгу покупок, но входящий номер не отражается.
![image](https://user-images.githubusercontent.com/84187165/171342831-1a4d87f4-dd1b-4281-92b8-dce1b78bc6d2.png)
![image](https://user-images.githubusercontent.com/84187165/171342870-d5d97fb1-1240-4ca5-8609-07fa23701634.png)

**Comment by Linda4ka** [comment]
Входящий номер попадает в книгу покупок только в том случае, когда копируешь данный номер на закладку Дополнительно.

**Comment by Nullarity** [comment]
Это у вас на последнем релизе такая ситуация? Мне не удается воспроизвести, таможенная декларация не должна вообще в таком виде попадать в этот отчет. Можете воспроизвести на демо базе и выслать ее?
Спасибо!

**Comment by Linda4ka** [comment]
Выслала на почту ссылку на dt.

**Comment by Nullarity** [comment]
спасибо, исправление войдет в 5.0.29.1
