### ISSUE TITLE
Неправильный расчет зарплаты

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#51]
Программа неправильно рассчитывает зарплату. Сотрудник поступил 01.01,2020, оклад 7000 лей. Освобождение вступает в силу с 01,02,2020. Соответственно расчет такой: Оклад 7000 лей - 4,5% - 315 лей мед страх
                                                                                                            6% - 420 лей соц фонд
                                                                                7000 - 315 
-                                                                                        - 420 =6265 *12% подоходный налог (т.к. освобождение с февраля считаем из всей суммы) = 751,8 лей. Итого: 7000 - 315 - 420 - 751,8 = 5513,2 к выдаче.
У нас сейчас ситуация такова: 7000 - 4,5%-315
                                                            6%-420
                                     7000-315-420-2000=4265*12%=511,8 ( подоходный налог)
                                      7000-315-420-511,8=5753,2 к выдаче.,что в нашем случае грубейшая ошибка, т.к. программа берет освобождение за январь,а не должна.
Полагаю, что та же ситуация будет и с 2021 годом.

**Comment by Nullarity** [comment]
Подскажите пожалуйста, что вы указали в качестве даты начала действия освобождений, дату приема на работу или дату фактического действия? Нужно указывать дату, начиная с которой освобождение будет действовать.
В к5 нет отдельного документа для регистрации события "Освобождения", потому что такого события по большому счету для компании нет. Освобождения считаются справочной информацией, и применяются при расчете налогов с даты регистрации в справочнике. Таким же образом, например при рождении ребенка, у нас нет документа "Родился ребенок", бухгалтер должен по своему усмотрению войти в освобождения сотрудника и зарегистрировать освобождения на иждивенца. Сделано так для упрощения, чтобы не "подразумевать" что личное освобождение действует по одному, а не личное по другому.

**Comment by Nullarity** [comment]
Предложение: при вводе данных об освобождении, на видном месте, подсказывать пользователю, что дата регистрации освобождения, это не дата приема на работу, а дата, начиная с которой освобождение должно учитываться в расчете ЗП

**Comment by Linda4ka** [comment]
Ну это каждый бухгалтер знает Я скину скрины и вы глянете.

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/119299487-a9b81900-bc67-11eb-9e71-84f8d9bfc4f3.png)
![image](https://user-images.githubusercontent.com/84187165/119299539-c3f1f700-bc67-11eb-86a7-83ff3a140365.png)
![image](https://user-images.githubusercontent.com/84187165/119299691-1a5f3580-bc68-11eb-96f4-4bd4ba5986ab.png)

**Comment by Linda4ka** [comment]
В графе подоходный налог, в документе Выплата зарплаты должна стоять сумма 751,80, а стоит 511,8(т.е. с учетом личного освобождения). Как я понимаю я все сделала правильно! Подскажите, если это не так!

**Comment by Linda4ka** [comment]
В расчетной ведомости четко видно, что берется освобождение, В вопросах выше (Личная карточка) видно, что при заполнении данных сотрудника мы все сделали правильно.
![image](https://user-images.githubusercontent.com/84187165/119304098-6f527a00-bc6f-11eb-87f2-0b8bac077cb8.png)

**Comment by Nullarity** [comment]
Подскажите пожалуйста, эта проблема еще актуальна?
