### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#510]
Хотела сформировать акт сверки без периода, убрала период из строки и появилась ошибка
![image](https://user-images.githubusercontent.com/84187165/171344834-4ec14e0b-fae8-4376-b355-abf2181c504a.png)

**Comment by Linda4ka** [comment]
Данная ошибка связана с периодом, она вылазит и при смене периода при формировании табеля.

**Comment by Linda4ka** [comment]
Для информации: все та же ошибка вылазит и при формировании всех отчетов в Бухгалтерии при попытке сменить период, счет, вид субконто 1 и субконто 1.

**Comment by Nullarity** [comment]
Желательно заголовок проблемы задавать более информативно.
Спасибо!
