### ISSUE TITLE
Табель

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#52]
Подскажите, а что нет функции автоматического заполнения табеля? Если нет, то это очень нехорошо, т. к. на предприятии, где большое количество работников вряд ли будут в восторге от ручного ввода по каждому сотруднику. Да и вообще, независимо от количества сотрудников не в восторге будут в любом случае. Если же эта функция есть, но я ее не вижу, подскажите где смотреть. Спасибо!

**Comment by Nullarity** [comment]
Тут имеет место чуть иная методология, вероятно не привычная, но с т.з. кол-ва совершаемых пользователем операций, и удобства, не уступающая реализованной ранее. Вы не читали это https://cont.help/d/Timesheet/ ? Если останутся нарекания, давайте обсуждать.

**Comment by Linda4ka** [comment]
Это все конечно хорошо, но согласно законодательству РМ, каждый работодатель обязан вести табель учета рабочего времени, на основании которого делается начисление зарплаты. Табель должен быть распечатан, подписан и храниться в отдельной папке, в течение всего года один экземпляр у бухгалтера, один у кадровика. В любой момент, пришедшая на предприятия проверка из Инспекции по труду или налоговой может потребовать предоставить табель для проверки, сама с этим сталкивалась. Поэтому в нашем случае нам просто необходимо ведение именно табеля за месяц, как сейчас в 4,0. Ничего личного, только законодательство и диктуемые нашими проверяющими органами правила.

**Comment by Nullarity** [comment]
Уточните пожалуйста, в описанном вами примере, что мешает вести учет согласно законодательства? Табель в программе есть, чтобы его получить, войдите в меню Сотрудники / Отчеты / Табель.

**Comment by SvetlanaRes** [comment]
Linda4ka, ничего не мешает распечатать Табель и подшить папку. Думаю вопрос только в форме отчета Табель. По законодательству он имеет вид по дням, а в программе сейчас видно только  итоговое количество отработанных дней/часов.

**Comment by Nullarity** [comment]
> в программе сейчас видно только итоговое количество отработанных дней/часов
Нет, это не должно быть так. В программе он тоже по дням.

p.s. законодетельство не регулирует форму, а имеет рекомендованную. Поправьте пожалуйста, если это не так.

**Comment by Nullarity** [comment]
@SvetlanaRes  проверь плиз, заполнен ли график

**Comment by Linda4ka** [comment]
Хорошо, я погоняю данные функции по работе и потом скажу впечатляет или нет)))))

**Comment by Nullarity** [comment]
Спасибо! Вернемся к вопросу тогда с новой силой в отдельном обсуждении.
