### ISSUE TITLE
Как рассчитывается и где посмотреть расчеты больничного?

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#54]
Попробовала создать документ Больничный, основные данные ввела - все нормально, перешла на закладку Документы и выдало непредвиденную ошибку.
![image](https://user-images.githubusercontent.com/84187165/119301277-dde10900-bc6a-11eb-9791-09b85f09a291.png)
1. Нужно ли вообще заполнять эту закладку
2. Где видны распределение и расчет по больничному?
Текст ошибки:
Ошибка доступа к файлу '\17d9a7fe-b288-4a5f-b563-735e1a39f9ba.aspx'
{CommonModule.CKEditorSrv.Module(313)}:	writer = new TextWriter ( getUploadingFile ( FolderID ) );
{CommonModule.CKEditorSrv.Module(302)}:	functions = getFunctions ( false, createScript ( FolderID ), ReadOnly, Uploading, Focus );
{Document.Document.Form.Form.Form(201)}:	CKEditorSrv.Init ( TextEditor, Object.FolderID, html, not CanChange, true );
{Document.Document.Form.Form.Form(239)}:		initEditor ();
{Document.Document.Form.List.Form(1138)}:	OpenForm ( "Document.Document.ObjectForm", new Structure ( "FillingValues", values ), Items.DocumentsList );
{Document.Document.Form.List.Form(1128)}:	openNew ();

по причине:
Ошибка доступа к файлу '\17d9a7fe-b288-4a5f-b563-735e1a39f9ba.aspx'

**Comment by Nullarity** [comment]
Документы, это подсистема для работы с внешними файлами, непосредственного влияния на какие-либо расчеты в программе не оказывает, вы можете временно проигнорировать этот механизм, полноценная его работа будет реализована в 5.0.15. В настоящий момент эта подсистема работает только в облачном режиме.

**Comment by Linda4ka** [comment]
Ok! А как можно увидеть распределение по больничным и отпускным и расчеты по ним же? Может я чего-то недоглядела?

**Comment by Linda4ka** [comment]
А, хорошо! Завтра постараюсь сделать и посмотрю как рассчитывается!

**Comment by Linda4ka** [comment]
Большая просьба!!! Дополните документ Больничный возможностью отображения номера,т.к это обязательно и окошко, где можно проставить галочку 100% за счет CNAS, т.к. бывают больничные, которые 100% выплачиваются из средств CNAS и мы должны учитывать такие больничные листы, но не рассчитывать. Это очень важные функции и они обязательно понадобятся.

**Comment by Nullarity** [comment]
Спасибо за замечания и предложения!
Однако, есть встречная просьба, введите пожалуйста эти два замечания отдельными записями в Issues, там нам всем потом будет удобней отслеживать состояние задачи и вести прицельную дискуссию.
Например так:
- Добавить в больничный поле для ввода номера больничного листа
- Реализовать возможность учета больничных 100% выплачиваемых из CNAS (а внутри опишите детали, что должно быть с т.з. расчетов)

Спасибо!

**Comment by Linda4ka** [comment]
Поняла, спасибо!
