### ISSUE TITLE
Проверка курса валют

### ISSUE THREAD

**Issue by vizirina** [Contabilizare/c5#544]
Не удается создать договор с поставщиком, т.к. программа требует заполнить поле "Курс валюты". Валюта региональная, поэтому данное поле отсутствует. Скрин отправлен на е-мейл

**Comment by Linda4ka** [comment]
При проверке на типовой вылазит та же самая ошибка!!!

**Comment by vizirina** [comment]
![Проверка курса валют](https://user-images.githubusercontent.com/84189282/176832668-ce4c8f09-dc53-4d04-88a7-2c463ce710a1.png)

**Comment by vizirina** [comment]
Добрый день. Обратите пожалуйста внимание на данную ошибку, не можем работать с доками Поступление
