### ISSUE TITLE
Оптимизация заполнения Начисление ЗП

### ISSUE THREAD

**Issue by SvetlanaRes** [Contabilizare/c5#549]
Здравствуйте!

Существует следующий сценарий: 
1) В течение месяца производятся выплаты аванса, причем как из оклада, так и премиальные выплаты (т.е. это разные виды начисления). 
2) В конце месяца формируется документ Начисление ЗП, который при нажатии на кнопку Заполнить заполняет - закладку Свод окладами, а закладку Авансы - информацией по выдаче аванса в разрезе вида начисления = оклад, а если были Авансы с другими видами начисления, то на этой закладке не заполняется.
Чтоб подтянулись на закладку и другие документы Авансы по ЗП, необходимо на закладке Дополнительные начисления по сотрудникам указать с необходимым видом начисления - хоть 1 лей.

Предлагаю!
1. При нажатии на кнопку Заполнить - заполнение закладки Авансы всеми доками выдачи аванса независимо от вида начисления, указанного в документе.
2. Из практики - в течения месяца есть премиальные выплаты, которые необходимо начислить как Дополнительное начисление. Очень облегчило работу, если бы на основании выданных Авансов по премиям (виду начисления не равному окладу) можно было бы заполнить закладку Дополнительные начисления (например, добавить кнопку Добавить или обновить Доп.начисления).

**Comment by Nullarity** [comment]
Спасибо за описание, задача понятна, принимается. По срокам пока не готов сказать.

**Comment by Nullarity** [comment]
@SvetlanaRes в вашем конкретном случае, какой способ расчета указан в виде дополнительного начислиния в документе выплаты авансов?
