### ISSUE TITLE
Отпускные.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#55]
Та же ситуация с отпускными. Закладка Основное заполнилась без проблем. Закладка Документы выдало ошибку.
![image](https://user-images.githubusercontent.com/84187165/119301909-e2f28800-bc6b-11eb-829f-f3d4ebfc312a.png)
Текст ошибки:
Ошибка доступа к файлу '\54422d79-cedf-4890-932f-388848c588d8.aspx'
{CommonModule.CKEditorSrv.Module(313)}:	writer = new TextWriter ( getUploadingFile ( FolderID ) );
{CommonModule.CKEditorSrv.Module(302)}:	functions = getFunctions ( false, createScript ( FolderID ), ReadOnly, Uploading, Focus );
{Document.Document.Form.Form.Form(201)}:	CKEditorSrv.Init ( TextEditor, Object.FolderID, html, not CanChange, true );
{Document.Document.Form.Form.Form(239)}:		initEditor ();
{Document.Document.Form.List.Form(1138)}:	OpenForm ( "Document.Document.ObjectForm", new Structure ( "FillingValues", values ), Items.DocumentsList );
{Document.Document.Form.List.Form(1128)}:	openNew ();

по причине:
Ошибка доступа к файлу '\54422d79-cedf-4890-932f-388848c588d8.aspx'
Вопросы те же самые что и по больничному!

**Comment by Nullarity** [comment]
Повтор ошибки
