### ISSUE TITLE
Закрытие авансов - подокументально или в конце месяца

### ISSUE THREAD

**Issue by SvetlanaRes** [Contabilizare/c5#553]
В системе предусмотрен гибкий механизм начисления и зачета авансов.
Но хотела бы обратить на некоторые моменты.
1) при создании нового договора автоматически проставляется два флага:
![image](https://user-images.githubusercontent.com/82224240/184897426-ee54fcb7-4307-45ad-92b1-d9233a3d070d.png)
Которые, на мой взгляд, взаимоисключают.
-Закрыть предоплату - в расходной накладной будут автоматически закрываться ранее полученные авансы.
- Отражать авансы от покупателя в конце месяца - закрытие авансов будет происходить в конце месяца посредством Регламентной операции/Закрытие полученных авансов.

2) Изначально в Приложении определяется принцип закрытия авансов:
![image](https://user-images.githubusercontent.com/82224240/184899586-08c9d466-3e24-430d-98ff-d1518fdb8d53.png)

Следовательно, предложение - При указании с Настройках приложения - Закрывать авансы в конце месяца - Да => В Договорах по умолчанию флаг "Отражать авансы от покупателя в конце месяца".

**Comment by Nullarity** [comment]
> 1. Которые, на мой взгляд, взаимоисключают.

Да, если флаг Отражать авансы от покупателя в конце месяца включен, тогда флаг Закрывать предоплату нужно скрывать.

> При указании с Настройках приложения - Закрывать авансы в конце месяца - Да => В Договорах по умолчанию флаг "Отражать авансы от покупателя в конце месяца".

Но сейчас так и должно работать, проверил на последнем релизе.

**Comment by Linda4ka** [comment]
@Nullarity, , если в типовой базе в Настройки/Приложение/Бухгалтерия на Закрывать авансы в конце месяца проставить Да, то в Контрагентах при создании Договора автоматически проставляются 2 галки: 1 на Закрывать предоплату и 1 на Отражать авансы от покупателя в конце месяца. А правильно чтобы была только 1 галка на Отражать авансы от покупателя в конце месяца.

**Comment by Nullarity** [comment]
При более детальном рассмотрении, текущее поведение соответствует дизайну: эти флаги независимые. Флаг Отражать авансы от покупателя в конце месяца, задает момент времени формирования проводок по авансам в финансовом учете. Флаг Закрыть предоплату, определяет для оперативного учета момент времени формирования записей по закрытию ранее выданных авансов, и работает как значение по умолчанию (на уровне каждой расходной накладной этот флаг можно включить/выключить).
Таким образом, если включены два флага (как на первой картинке), то проводки по авансам будут формироваться в конце месяца, но в оперативном учете, авансы будут закрываться и отражать текущий долг или аванс.
