### ISSUE TITLE
Отпуск за свой счет

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#56]
Повторилась ситуация и при заполнении Отпуск за свой счет.
![image](https://user-images.githubusercontent.com/84187165/119302476-d6bafa80-bc6c-11eb-89e4-12f3f6bdda28.png)
Текст ошибки;
Ошибка доступа к файлу '\61e10b59-30f7-4a16-b3b6-fdd9a8f8d20e.aspx'
{CommonModule.CKEditorSrv.Module(313)}:	writer = new TextWriter ( getUploadingFile ( FolderID ) );
{CommonModule.CKEditorSrv.Module(302)}:	functions = getFunctions ( false, createScript ( FolderID ), ReadOnly, Uploading, Focus );
{Document.Document.Form.Form.Form(201)}:	CKEditorSrv.Init ( TextEditor, Object.FolderID, html, not CanChange, true );
{Document.Document.Form.Form.Form(239)}:		initEditor ();
{Document.Document.Form.List.Form(1138)}:	OpenForm ( "Document.Document.ObjectForm", new Structure ( "FillingValues", values ), Items.DocumentsList );
{Document.Document.Form.List.Form(1128)}:	openNew ();

по причине:
Ошибка доступа к файлу '\61e10b59-30f7-4a16-b3b6-fdd9a8f8d20e.aspx'

**Comment by Nullarity** [comment]
Повтор ошибки
