### ISSUE TITLE
Контрагент (Создание)

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#60]
Документ очень удобный, понятный, но как дошла до вкладки Документы-опять ошибка.
![image](https://user-images.githubusercontent.com/84187165/119310958-26072800-bc79-11eb-90d0-1ce75fc4e528.png)
Текст ошибки:
Ошибка доступа к файлу '\15060475-e312-4769-b283-48e02601891f.aspx'
{CommonModule.CKEditorSrv.Module(313)}:	writer = new TextWriter ( getUploadingFile ( FolderID ) );
{CommonModule.CKEditorSrv.Module(302)}:	functions = getFunctions ( false, createScript ( FolderID ), ReadOnly, Uploading, Focus );
{Document.Document.Form.Form.Form(201)}:	CKEditorSrv.Init ( TextEditor, Object.FolderID, html, not CanChange, true );
{Document.Document.Form.Form.Form(239)}:		initEditor ();
{Document.Document.Form.List.Form(1138)}:	OpenForm ( "Document.Document.ObjectForm", new Structure ( "FillingValues", values ), Items.DocumentsList );
{Document.Document.Form.List.Form(1128)}:	openNew ();

по причине:
Ошибка доступа к файлу '\15060475-e312-4769-b283-48e0260189

**Comment by Nullarity** [comment]
Повтор ошибки
