### ISSUE TITLE
Полное списание МБП при вводе в эксплуатацию

### ISSUE THREAD

**Issue by AlinaCuragau** [Contabilizare/c5#604]
При вводе в эксплуатацию если стоимость МБП больше чем придел, программа не правильно создает проводки. Нужно чтобы списала всю стоимость с 214 счета. Т.е. с 213,2 переходит вся стоимость в 214 и оттуда на затраты. Сейчас же, списывается 50% от стоимости. Ниже прилагаю нормы закона.
51. Передача в эксплуатацию малоценных и быстроизнашивающихся предметов, стоимость единицы которых не превышает 1/6 лимита от размера, установленного законодательством, отражается в учете как увеличение текущих затрат/расходов, долгосрочных активов и т.д. и уменьшение запасов. Согласно учетным политикам эти предметы могут быть списаны по мере передачи в эксплуатацию путем начисления износа в порядке, установленном в п. 52-53 настоящего стандарта.
52. Малоценные и быстроизнашивающиеся предметы, стоимость единицы которых превышает 1/6 лимита от размера, установленного законодательством, списываются на текущие затраты/расходы, долгосрочные активы и т.д. путем начисления износа. Передача в эксплуатацию этих предметов отражается как внутренняя корреспонденция между субсчетами открытыми на счете учета малоценных и быстроизнашивающихся предметов.
53. Износ малоценных и быстроизнашивающихся предметов начисляется в размере 100% от стоимости объектов, за вычетом остаточной стоимости при их передаче в эксплуатацию. В зависимости от назначения использования этих предметов, начисленный износ отражается в учете как одновременное увеличение текущих затрат/расходов, долгосрочных активов и др. и износа малоценных и быстроизнашивающихся предметов. Oстаточная стоимость малоценных и быстроизнашивающихся предметов устанавливается каждым субъектом самостоятельно. Списание износа этих предметов осуществляется при их выбытии и отражается как одновременное уменьшение износа малоценных и быстроизнашивающихся предметов и запасов.

**Comment by Nullarity** [comment]
(большая просьба озаглавливать проблемы краткой, но емкой фразой).
> Сейчас же, списывается 50% от стоимости
Ва пробовали задать предел в значение стоимости (или большее) вводимого МБП? Программа в этом случае должна списать всё.

**Comment by AlinaCuragau** [comment]
если задать другой придел, нежели тот что по закону, тогда программа отрабатывает движения правильно.

**Comment by Nullarity** [comment]
> если задать другой придел, нежели тот что по закону, тогда программа отрабатывает движения не совсем правильно.

Вы правы, надо исправлять.

> Если же МБП больше чем придел, должно списываться 100% но с использованием 214 счета

обащался с одним бухгалтером, он говорит, что закон просто снял ограничение, мол хотите, списывайте всё (задаётся учетной политикой). Вы не можете еще раз этот нюанс разузнать, нам можно списать 100% или нам нужно списать 100%, чтобы не переделывать потом.
Спасибо!

**Comment by AlinaCuragau** [comment]
Исходя из пункта 53 из НБСУ "Запасы" предприятие имеет право (Не обязано) списать 100% стоимости объекта если превышает 1000 лей. И это списание проходит через 214 счет. Из практики, все бухгалтера так и делают (списывают всю стоимость и забывают о существование этих объектах) и не заморачиваются, а  если хотят оставляют объект в количестве висеть в балансе. А для измерительных объектах считают износ по мере использования, т.е. создают основные средства. 
Мое мнение что нужно исправить метод списания через 214 счет для тех объектов которые превышают придельную стоимость

**Comment by Nullarity** [comment]
Спасибо! Будем дорабатывать.

**Comment by AlinaCuragau** [comment]
Вам спасибо за работу
