### ISSUE TITLE
Как измененить дату ввода остатков?

### ISSUE THREAD

**Issue by AlinaCuragau** [Contabilizare/c5#606]
В документ ввод остатков не возможно поменять дату формирования проводок. Допустим мы создали документ 30.12 и провели его. потом решили изменить, в шапке поменяли дату на 31.12 снимаем с проведения, заходим в документ и видим нашу дату. Проводим и проверяет проводки а там старая дата, 30.12..

**Comment by Nullarity** [comment]
Дата ввода остатков меняется здесь:
![image](https://user-images.githubusercontent.com/28710693/209153832-66eed73b-141b-47d4-94c6-a7dd3306badc.png)

см.также: #293

**Comment by AlinaCuragau** [comment]
Этот момент я знаю, но только для ранее созданных документов дата не меняется после перепроведени
![14_12](https://user-images.githubusercontent.com/120193629/209172055-e65d2a86-c2a7-4109-920c-d23ec24c7a56.png)
![15_12](https://user-images.githubusercontent.com/120193629/209172067-ce5f71cf-0c82-4851-91ef-5575d618cd24.png)
е

**Comment by Nullarity** [comment]
проводка формируется на день ранее даты документа, обратите внимание на это подсказку:
![image](https://user-images.githubusercontent.com/28710693/209178334-1edd176b-1734-41d1-8da4-fcd83cd893ce.png)

**Comment by Nullarity** [comment]
В вашем примере, в документе указано 15.12, а программа сформировала проводку 14.12, это штатное поведение программы. Пользователь, вводит остатки "на" дату, например, на начало года, а программа уже сама внутри делает проводки днем ранее, чтобы получились ожидаемые данные.

**Comment by AlinaCuragau** [comment]
Разобралась, спасибо! Можно считать вопрос закрытым

**Comment by Nullarity** [comment]
отлично, закрывайте тему (вы ее автор)

**Comment by AlinaCuragau** [comment]
Вопрос решен.
