### ISSUE TITLE
Как вести правильно розничную торговлю?

### ISSUE THREAD

**Issue by AlinaCuragau** [Contabilizare/c5#608]
Нашла документ "Продажи в розницу" но не совсем понятен принцип действий данного документа.
1. Почему нельзя указывать только сумму? ведь в этом и кроется весь смысл розницы, происходит перемещение из единиц хранения в сумме хранения, и эту же сумму потом и продаем. А на данный момент получается что продаем тоже единицы товаров.
2. Нужно добавить в план счетов счет 217.21 "Товары в розничной торговле общими суммами"  что бы была возможность отследить продажи обычные и розничные. 
3.А в идеале нужно изменить механизм документа "Продажи в розницу"

**Comment by Nullarity** [comment]
В программе на данный момент не реализована розница общими суммами. Более поднобно о работе рознице здесь https://cont.help/d/Sale/

**Comment by AlinaCuragau** [comment]
спасибо, буду изучать другие аспекты тарговли.
