### ISSUE TITLE
Главное - Документы.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#61]
При попытке создать ДОКУМЕНТЫ на закладке Главное, моментально выходит ОШИБКА!
![image](https://user-images.githubusercontent.com/84187165/119311308-9615ae00-bc79-11eb-87c7-c22f17ed72f2.png)
Текст ошибки:
Ошибка доступа к файлу '\fe7db200-136e-43bf-9294-76fba1844749.aspx'
{CommonModule.CKEditorSrv.Module(313)}:	writer = new TextWriter ( getUploadingFile ( FolderID ) );
{CommonModule.CKEditorSrv.Module(302)}:	functions = getFunctions ( false, createScript ( FolderID ), ReadOnly, Uploading, Focus );
{Document.Document.Form.Form.Form(201)}:	CKEditorSrv.Init ( TextEditor, Object.FolderID, html, not CanChange, true );
{Document.Document.Form.Form.Form(239)}:		initEditor ();
{Document.Document.Form.List.Form(1138)}:	OpenForm ( "Document.Document.ObjectForm", new Structure ( "FillingValues", values ), Items.DocumentsList );
{Document.Document.Form.List.Form(1128)}:	openNew ();

по причине:
Ошибка доступа к файлу '\fe7db200-136e-43bf-9294-76fba1844749.aspx'

**Comment by Nullarity** [comment]
Повтор ошибки
