### ISSUE TITLE
"Разделение диапазона БСО" для чего разработан механизм?

### ISSUE THREAD

**Issue by AlinaCuragau** [Contabilizare/c5#612]
В блоке БСО, Операций и диапазоны есть возможность разделить диапазон. Для чего предусмотрен данный функционал? Я думала что с помощью него можно изменить ответственного или подразделение, но в этом документе нет возможность указать такие данные. Прочитала описание но не поняла.
Для чего предусмотрен данный механизм? Спасибо!

**Comment by Nullarity** [comment]
Допустим, нам нужно пачку накладных разделить между двумя складами (или отделами по выписке накладных). Для этого, разделяем диапазон и делаем стандартное перемещение ТМЦ.
Скажете, если непонятно и нужно доработать документацию.

**Comment by AlinaCuragau** [comment]
Спасибо, поняла. Привыкла работать по другому. Если надо было перемещать по частям и приходовала по частям.
Считаю вопрос исчерпан и закрываю его. Благодарю за ответ!
