### ISSUE TITLE
Есть возможность расчета ЗП сдельным методом?

### ISSUE THREAD

**Issue by AlinaCuragau** [Contabilizare/c5#616]
@Nullarity  Можно рассчитать ЗП исходя из количество в производство? 
Спасибо!

**Comment by Nullarity** [comment]
Наверное пока нет. Могу предложить часовой тариф в совокупности с задействованием табеля по проектам. А сам блок производства пока в программе отсутствует.

**Comment by AlinaCuragau** [comment]
Ок, спасибо поняла
