### ISSUE TITLE
План счетов.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#62]
План счетов неполный, даже можно сказать не совсем правильный, Нет некоторых счетов и субсчетов. Есть субсчета, которые уже не используются. Короче говоря, план счетов неактуален. Позже постараюсь скинуть как надо.

**Comment by Linda4ka** [comment]
![image](https://user-images.githubusercontent.com/84187165/119456754-a98d4b80-bd43-11eb-8a08-12ffa897b3b1.png)
![image](https://user-images.githubusercontent.com/84187165/119456818-b742d100-bd43-11eb-9276-5293e6947898.png)
![image](https://user-images.githubusercontent.com/84187165/119456864-c164cf80-bd43-11eb-97e2-ffdbc65bba42.png)
![image](https://user-images.githubusercontent.com/84187165/119456921-cf1a5500-bd43-11eb-909e-2e006e45d793.png)
![image](https://user-images.githubusercontent.com/84187165/119456977-db9ead80-bd43-11eb-8b44-25075548c730.png)
![image](https://user-images.githubusercontent.com/84187165/119457014-e48f7f00-bd43-11eb-88a2-5adfef6d816c.png)
![image](https://user-images.githubusercontent.com/84187165/119457051-ed805080-bd43-11eb-9676-4f8af8f6c6a9.png)
![image](https://user-images.githubusercontent.com/84187165/119457085-f7a24f00-bd43-11eb-939b-f763302888b7.png)
![image](https://user-images.githubusercontent.com/84187165/119457129-025ce400-bd44-11eb-8d99-969188cf6f9b.png)
![image](https://user-images.githubusercontent.com/84187165/119457156-0b4db580-bd44-11eb-98f0-f085e64e5cc8.png)
![image](https://user-images.githubusercontent.com/84187165/119457187-130d5a00-bd44-11eb-9d26-c27c3c39430c.png)
![image](https://user-images.githubusercontent.com/84187165/119457228-1f91b280-bd44-11eb-9a85-95d90f7406d1.png)

**Comment by Linda4ka** [comment]
Этот план сетов, действующий с 01.01.2020. Пока больше изменений нет!

**Comment by Nullarity** [comment]
Спасибо за информацию, однако для того, чтобы выполнить изменения в программе, нужен текстовый формат на двух языках. Спасибо!

**Comment by Linda4ka** [comment]
Постараемся сделать!

**Comment by Linda4ka** [comment]
Я скинула на почту

**Comment by Nullarity** [comment]
Принял, спасибо!

**Comment by Linda4ka** [comment]
https://drive.google.com/drive/folders/1GDxQ-37Bk19bV5IZgQo021echQ14IjnZ?usp=sharing
