### ISSUE TITLE
Есть возможность установить скидки и наценки номенклатуры ?

### ISSUE THREAD

**Issue by AlinaCuragau** [Contabilizare/c5#620]
@Nullarity  Есть возможность установить скидки и наценки номенклатуры для продаж с определенным видом цен или просто создать список товаров с наценкой или скидками? Спасибо!

**Comment by Nullarity** [comment]
Да, но развернутый ответ наверное уже будет лучше дать в рамках документации. Пока, из того, что мы успели написать, можно найти здесь https://cont.help/c/Prices/.
Конечно, ценообразованию в программе еще есть куда развиваться, но немало сценариев можно автоматизировать уже сейчас (переусложнять не хотелось).

**Comment by AlinaCuragau** [comment]
Спасибо за быстрый ответ. Согласна с Вами, белее детально будет усложнять процесс учета и контроль наценки.
