### ISSUE TITLE
Поступление товаров(Создание)

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#63]
При создании документа Поступление товара закладка Основное заполняется нормально, как доходим до закладки Документы.........
![image](https://user-images.githubusercontent.com/84187165/119319284-e80f0180-bc82-11eb-9caa-fa4d5813841b.png)
Текст ошибки:
Ошибка доступа к файлу '\720f9229-a5a0-474a-868b-141978f38fd9.aspx'
{CommonModule.CKEditorSrv.Module(313)}:	writer = new TextWriter ( getUploadingFile ( FolderID ) );
{CommonModule.CKEditorSrv.Module(302)}:	functions = getFunctions ( false, createScript ( FolderID ), ReadOnly, Uploading, Focus );
{Document.Document.Form.Form.Form(201)}:	CKEditorSrv.Init ( TextEditor, Object.FolderID, html, not CanChange, true );
{Document.Document.Form.Form.Form(239)}:		initEditor ();
{Document.Document.Form.List.Form(1138)}:	OpenForm ( "Document.Document.ObjectForm", new Structure ( "FillingValues", values ), Items.DocumentsList );
{Document.Document.Form.List.Form(1128)}:	openNew ();

по причине:
Ошибка доступа к файлу '\720f9229-a5a0-474a-868b-141978f38f

**Comment by Nullarity** [comment]
Повторение ошибки
