### ISSUE TITLE
Классификатор банков

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#67]
Необходима возможность самостоятельного добавления банка-нерезидента в классификатор банков. Невозможно оформить фирму-нерезидент со счетом в валюте. В списке только молдавские банки и нет возможности создания другого. Если есть - подскажите.

**Comment by Nullarity** [comment]
Такая возможность есть, для открытия классификатора в режиме редактирования, нужно войти в меню Справочники / Классификатор банков

**Comment by Linda4ka** [comment]
Все, поняла. Необходимо будет заранее записывать банк. Вопрос снят!
