### ISSUE TITLE
Поступление товара, склад берется из шапки или таблицы?

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#68]
Столкнулась с ситуацией, мне не совсем понятной. Сделала приход товара и в шапке проставила Производственный склад, в таблично же части не заметила и проставила Основной. Зная что в шапке проставлен Производственный, сделав отчет по товарам на складе  и была удивлена что он не попал на Производственный, а оказался на Основном. Вопрос: зачем тогда в шапке документа указывать склад, если товар попадает на склад из табличной части. И может стоит предусмотреть возможность Предупреждения или оповещения о смене склада?
![image](https://user-images.githubusercontent.com/84187165/119662710-5a761200-be3a-11eb-82d8-50008aa64cf2.png)
![image](https://user-images.githubusercontent.com/84187165/119662980-9f9a4400-be3a-11eb-84c8-7d7c7a61eb90.png)
![image](https://user-images.githubusercontent.com/84187165/119663339-f011a180-be3a-11eb-8d2d-70ecf336833d.png)
![image](https://user-images.githubusercontent.com/84187165/119663488-0ddf0680-be3b-11eb-98fb-995e8029f048.png)

**Comment by Nullarity** [comment]
Объясню как оно работает по дизайну, а потом может вместе что-то придумаем для улучшения.
Работает оно так (не только в приходе, но и других документах, где имеется возможность выбора склада в таблице): склад в таблице имеет приоритет над складом в шапке. Так сделано для того, чтобы у пользователя была возможность задать в таблице склад только для выбранных позиций, а остальные, для которых склад не указан, будут оприходованы на склад из шапки. На моей практике, предприятия, которым требуется в одном поступлении приходовать тмц на разные склады, предпочитают именно такой алгоритм работы. Таким предприятий не много, именно поэтому опция указания склада в таблицах, по умолчанию выключена.

**Comment by Linda4ka** [comment]
т.е. если я проставлю в шапке склад, я могу этого не делать в таблице?

**Comment by Linda4ka** [comment]
Или я могу не проставлять в шапке, а заполнить в таблице?

**Comment by Nullarity** [comment]
Можно не ставить в таблице. Например, мы приходуем 5 позиций, 4 из которых идут на Склад1,  и только одна на Склад2. В этом случае, в шапке нужно задать Склад1, а в таблице, оставить все строки пустыми, кроме одной, для которой указать Склад2.
Склад в шапке нельзя не задать. Это считается "приоритетный" склад, склад в шапке участвует в отборе списка документов, а также в контроле прав доступа по складам (можно пользователей разграничить по доступам к складам)

**Comment by Linda4ka** [comment]
Ок, поняла. Попробую, дам знать.
