### ISSUE TITLE
Что такое Лиды?

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#69]
Чта такое Лиды и для  чего используются? Важны ли они и обязательны ли для заполнения? На cont.help информацию не нашла. Спасибо!

**Comment by Nullarity** [comment]
Это часть подсистемы CRM, в программе оно пока реализовано на начальном уровне, но будем улучшать. Лиды - это что-то вроде потенциальных или как-то заинтересовавшихся продуктом/услугой клиентов.

**Comment by Linda4ka** [comment]
Спасибо за пояснения!
