### ISSUE TITLE
Права пользователя

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#7]
Добрый день. Можете подсказать какой флажок нужно включить чтобы можно было добавлять покупателей. Вроде все флажки включены а ошибка появляется.

![S10414-11132470](https://user-images.githubusercontent.com/82500510/114676966-80c07200-9d12-11eb-88d4-97879bed81cf.jpg)
![S10414-11133208](https://user-images.githubusercontent.com/82500510/114676970-81f19f00-9d12-11eb-9c52-ba3951997570.jpg)
![S10414-11133971](https://user-images.githubusercontent.com/82500510/114676977-8322cc00-9d12-11eb-8a49-510b7ca5274d.jpg)

**Comment by Nullarity** [comment]
да, просочилась ошибка, сейчас исправим, в течении часа будет исправительный релиз. В качестве временной меры, нужны права Администратора.
Спасибо!

**Comment by Nullarity** [comment]
Исправительный релиз опубликован. После обновления, установите пожалуйста для вашего пользователя право просмотра/редактирования свойств (при следующем создании пользователя с право просмотра контрагентов, данное право будет назначаться автоматически)

**Comment by TeodorUn** [comment]
> Исправительный релиз опубликован. После обновления, установите пожалуйста для вашего пользователя право просмотра/редактирования свойств (при следующем создании пользователя с право просмотра контрагентов, данное право будет назначаться автоматически)

поставил  права просмотра/редактирования свойств
![image](https://user-images.githubusercontent.com/82500510/115669525-0666a200-a351-11eb-9460-c22b6645a1e3.png)
