### ISSUE TITLE
ПОЯСНЕНИЕ!

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#70]
Извините за некоторые, может даже наивные вопросы, но я четко должна понимать как работает программа и знать ее настолько, чтобы можно было ответить на любой вопрос потенциального пользователя!

**Comment by Nullarity** [comment]
Тут у нас за вопрос не бьют в нос! Так что никаких "извините", чувствуйте себя свободно задавая любые вопросы.
