### ISSUE TITLE
Табель. Дополнение его информацией по больничным, отпускам и отклонениям.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#71]
В связи с недопонимаем в прошлом вопросе, формулирую данный следующим образом: необходимо, чтобы при оформлении отчета  Табель учета рабочего времени, информация по больничным, отпускам и отклонениям за месяц по сотруднику автоматически добавлялась в отчет, а не вводить ее вручную.Спасибо!

**Comment by Nullarity** [comment]
Да, по дизайну как вы пишите и должно работать, видимо есть какая-то проблема, давайте разбираться.
Я в мае принял сотрудника на работу, затем отправил его на больничный с 4 по 5 (документ Больничный). Сформировал табель:
![image](https://user-images.githubusercontent.com/28710693/119825762-4f1bf880-bec5-11eb-993f-fd642d62bc0a.png)

**Comment by Linda4ka** [comment]
Значится так!!! 1. с помощью Светланы я все-таки отрыла наиважнейшую вещь-Табель. Вот этот самый табель и есть та важнейшая составляющая зарплаты, которая должна обзываться Табель учета рабочего времени и должна находиться на самом видном месте СОТРУДНИКИ-ЗАРПЛАТА-ТАБЕЛЬ УЧЕТА РАБОЧЕГО ВРЕМЕНИ, перед Начислением з/п.
А вот тот Табель, который я тыкала и рыдала над ним, должен обзываться по-другому, т.к. использоваться он будет редко и не у всех.

**Comment by Nullarity** [comment]
Понятно теперь где был конфуз. Подкиньте пожалуйста идей, как его назвать тогда, желательно не более двух слов.

**Comment by Linda4ka** [comment]
Табель для тайма - подойдет? ( примерно так объяснила Светлана). а самый нужный придется обозвать Табель учета рабочего времени

**Comment by Nullarity** [comment]
Еще варианты:

- Табель по проектам
- Регистр времени (сотрудника)
- Время сотрудника

А вот табель предлагаю не переименовывать, потому что вы в него сразу кликали подразумевая табель учета рабочего времени, думаю так будет делать каждый.

**Comment by Linda4ka** [comment]
Лучше табель по проектам.

**Comment by Linda4ka** [comment]
Так вот его и надо переименовать чтоб просто так не лазили. Его можно оформить как табель по проектам. А вот тот Отчет-Табель можно переименовать Учет рабочего времени и вынести перед Начислением зарплаты.Точно все будет ясно и понятно.

**Comment by Nullarity** [comment]
Дело в том, что если отчет Табель переименовать в Учет рабочего времени, тогда возникнет опасность, что другие пользователи его не смогут найти, например те, кто пользуется поиском по функциям:
![image](https://user-images.githubusercontent.com/28710693/119841136-90b3a000-bed3-11eb-8d56-2f100955623b.png)
На картинке показано, как выглядит результат поиска табеля в настоящий момент. Если табель переименовать, в результате поиска останется только Табель по проектам, что опять приведет к той же ситуации, когда вы кликали в документ, не предназначенный для получения табеля в привычном понимании.

**Comment by SvetlanaRes** [comment]
> Еще варианты:
> 
> * Табель по проектам
> * Регистр времени (сотрудника)
> * Время сотрудника
> 
> А вот табель предлагаю не переименовывать, потому что вы в него сразу кликали подразумевая табель учета рабочего времени, думаю так будет делать каждый.

Предлагаю, отчет Табель - оставить Табелем)
А документ Табель, который касается подсистемы Время, переименовать Табель по проектам.

**Comment by Linda4ka** [comment]
Хорошо, сделаем так. Но только большая просьба, отчет Табель перенести перед Начислением зарплаты, чтобы все было понятно и четко. Спасибо
