### ISSUE TITLE
  На заметку по Табелю учета рабочего времени.                                         

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#75]
Сегодня обнаружила следующую закономерность: если в Настройках-Настройки Приложений-Сотрудники проставлен флаг Табель, то Табель учета рабочего времени не заполняется. Если флаг не проставлен, то заполняется. Почему так? Возможно необходимо убрать эту взаимосвязь.

**Comment by Nullarity** [comment]
Да, по замыслу так и должно быть. Есть ряд предприятий, где ведется **только** прямое табелирование, что означает, что каждый сотрудник отвечает за заполнение своего табеля. Таким образом, если сотрудник не ввел в систему свой Табель по проектам, зарплата ему начислена не будет, отчет Табель сформирован не будет.

**Comment by Linda4ka** [comment]
Ну у нас таких предприятий, насколько мне известно, нет, а если и есть их единицы. В Молдове табелирование сотрудников везде ведется либо ответственным лицом(начальники отделов, если предприятие большое либо одним ответственным)

**Comment by Nullarity** [comment]
Я лично знаю такую компанию. Остается вопрос, с какой целью вы вошли в настройки программы и включили эту опцию ведь по умолчанию она выключена и предназначена вот для таких редких случаев.

**Comment by Linda4ka** [comment]
Ну вот для такой компании пусть остается табель для тайма, а для 95 % остальных предприятий сделайте Табель учета рабочего времени ДОКУМЕНТОМ.

**Comment by Nullarity** [comment]
В 9 случаев из 10 по моей выборке (вне зависимости от программы), табелем как документом пользуются просто на автомате, потому что без него не начисляется зарплата. Этот документ открывают, авто-заполняют и закрывают. Потом, если вдруг есть проблема, его опять открывают, смотрят, а, нет (допустим) больничных, идут в меню, открывают больничный, корректируют или вводят новый, потом возвращаются в табель, перезаполняют, проверяют что боль села, и сохраняют табель. При этом, в некоторых программах реализовано по разному, где-то нужно и в табеле и отдельно документом отметить боль, где-то отпуск, где-то и то и другое. За годы это конечно доводится до автоматизма, но начинает работать как инграмма какая-то.

**Comment by Nullarity** [comment]
> Почитала cont.help. меня ведь туда отослали когда первый раз возник вопрос с табелем.

То есть вы включили эту галочку после прочтения документации? Спасибо, записал задачу на улучшение документации #78
