### ISSUE TITLE
Дополнительные функции в Табель учета рабочего времени.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#76]
Возможно ли дополнить Табель учета рабочего времени функцией Записать и Провести? Он должен отображаться хотя бы в СОТРУДНИКИ-ЗАРАБОТНАЯ ПЛАТА.

**Comment by Nullarity** [comment]
Сделать можно всё, нельзя сделано всего ;-)
Разверните пожалуйста мысль, а еще лучше - опишите сценарий. В текущей формулировке не понятна цель предлагаемых изменений, ведь Табель в программе это отчет, а не документ.

**Comment by Linda4ka** [comment]
Ну вот в этом и кроется маленькая проблема. Он должен стать документом, как табель для тайма. Ну и тогда проблема исчезнет.

**Comment by Nullarity** [comment]
А какая именно проблема исчезнет?

**Comment by Linda4ka** [comment]
Проблема в том, что Табель учета рабочего времени должен как документ отражаться в Заработной плате по каждому сотруднику. Для Молдовы основным будет Табель рабочего времени и он должен стать документом, а не отчетом.

**Comment by Nullarity** [comment]
@Linda4ka я действительно стараюсь понять проблему, но мне не удается. Я совершенно не умею мыслить категориями "должен как документ" или "отражаться в Заработной плате", даже если за этим стоит чей-то многолетний опыт. Чтобы ваши замечания достигли цели, необходимо оперировать измеряемыми сущностями. Например:
- количество совершаемых пользователем действий (кликов)
- отсылки к законодательству, где например жестко прописано, что в учетных программах на платформе 1с, табель должен быть реализован при помощи прикладного объекта Документ
- сценарии работы пользователя, в которых становится очевидно, что в программе не хватает определенной функции или она реализовано неудобно (неудобство определяется количеством совершаемых пользователем действий)

Я не исполнитель пожеланий, а архитектор системы, я проигрывал сценарии начисления заработной платы в основе которых лежала не функциональность (как в конт4), а удобство и скорость достижения цели, для самых типовых сценариев, отдавая себе отчет в том, что часть из этих улучшений может быть не привычной пользователям определенной выборки (ведь не вы ни я не обладаете объективной картиной, все мнения субъективны).

@SvetlanaRes помоги пожалуйста.

**Comment by SvetlanaRes** [comment]
> А какая именно проблема исчезнет?

Предполагаю, что эта "проблема" больше связана с некоторым наличием зафиксированных данных и уверенностью пользователя, что это те данные, которые он видел/использовал/и т.п. Для этого некоторые бухгалтера распечатывают/подшивают табеля. 
Предположим, по каким-то причинам график работы изменили/нарушили... и при формировании отчета отобразиться измененный вариант, а не тот, который фактически применялся при расчете ЗП в тот или иной период.
Для таких случае, а вернее во избегания недоразумений должна быть возможность сохранить отчет "в архив" - не исключаю, что это позволит сделать подсистема "Документы". 
Или есть другой вариант? чтоб в любой момент можно было восстановить из архива именно тот отчет, который был/видели/использовали ранее.

**Comment by Nullarity** [comment]
> Предположим, по каким-то причинам график работы изменили/нарушили... и при формировании отчета отобразиться измененный вариант, а не тот, который фактически применялся при расчете ЗП

но ведь ровно также может быть изменен оклад или освобождение, что напрямую исказит зарплату, а табель при этом останется незатронутым. Отсутствие табеля в виде документа, как раз и устраняет проблему искажения данных, нет табеля как документа - нет и сущности, которую можно было бы как-то изменить задним числом. Единственный способ повлиять на табель - это менять кадровые документы или справочники задним числом, но эти изменения меняют все, а не только фактически отработанное время. Да, для перестраховки, можно печатную форму сохранять, но лучше закрывать доступ к документам после начисления зарплаты.
