### ISSUE TITLE
Неверный расчёт скидки

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#8]
При формировании заказа покупателя из коммерческого предложения сама скидки не рассчитывает верно. Вместо суммы  "59.8" вписывается "10" то есть процент. Чтобы получить нужный результат нужно в ручную отредактировать скидку.
![image](https://user-images.githubusercontent.com/82500510/114842925-fd6e5180-9de1-11eb-9cb7-c4da0af833db.png)
![image](https://user-images.githubusercontent.com/82500510/114843114-2858a580-9de2-11eb-93a2-405caf6a7071.png)

После нажатия Записать перерасчитываются Суммы ниже с ошибками что в далнейшем перетекают во все документы.

![image](https://user-images.githubusercontent.com/82500510/114843862-eda33d00-9de2-11eb-9ed7-20933b28c504.png)

**Comment by TeodorUn** [comment]
Тоже самое наблюдается при подтверждение заказа и создании реализации из заказа покупателя.

**Comment by Nullarity** [comment]
Спасибо, сейчас проверяем...

**Comment by Nullarity** [comment]
Проблемы нашли и исправили, сегодня выпустим обновление
