### ISSUE TITLE
Ошибка при приеме на работу на внутреннее совместительство.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#85]
При попытке принять сотрудника на внутреннее совместительство, программа не разрешила провести документ
![image](https://user-images.githubusercontent.com/84187165/120197409-95f15180-c229-11eb-8fab-d9f32617c729.png)
![image](https://user-images.githubusercontent.com/84187165/120197694-ee285380-c229-11eb-9c1a-e484fed1f6ed.png)
Что я сделала не так?

**Comment by Nullarity** [comment]
День добрый, вам необходимо ввести второго сотрудника (так как при работе по совместительству, ему присваивается другой табельный номер). Физическое лицо при этом будет одно.

**Comment by Linda4ka** [comment]
А разве это правильно? Табельный номер уникален для каждого работника, разве может быть у одного работника разные табельные номера? Да и как-то неудобно. Можно ли сделать так чтобы внутреннее совместительство оформлялось без повторного создания сотрудника. У нас есть клиенты, у которых внутреннее совместительство каждый месяц, им необходимо будет создавать каждый раз сотрудника? Или я что-то недопонимаю?

**Comment by Nullarity** [comment]
Я думаю что правильно. При приеме сотрудника на работу, ему обязательно должен быть присвоен табельный номер. При приеме по совместительству, ситуация аналогична, ведь вам требуется отдельный трудовой договор. У совместителя может быть другая должность или подразделение (в больших организациях иногда используют префиксы у номеров). Да и не возникает путаницы, табельный номер насквозь идентифицирует сотрудника во всех кадровых документах, по нему отдельно видны начисления и табель. Также, отдельный сотрудник может быть ассоциирован с отдельным правом доступа пользователя в систему.
Если предприятие каждый месяц увольняет и принимает по совместительству работников, табельный номер допускается пере-использовать, создавать каждый раз сотрудника не потребуется. В любом случае, такой сценарий с ежемесячным увольнением и приемом на работу не кажется частотной, вероятно для такой компании потребуются индивидуальные доработки.

**Comment by Linda4ka** [comment]
Для внутреннего совместительства обычно не требуется другой трудовой договор,  это все регулируется приказом по фирме. Но если для совместительства хватит одного раза ввести сотрудника, то это можно пережить.
