### ISSUE TITLE
Учет рабочего времени при определенных сценариях

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#89]
Предлагаю рассмотреть ведение учета рабочего времени согласно следующих сценариев:
1.Сотрудник работает на основном месте работы по 8-ми часовому графику работы с определенным окладом.В конце месяца заполняем отчет Табель учета рабочего времени, далее Начисление  и Выплата зарплаты. Здесь вопросов не возникает, все четко, просто и понятно.
2. Когда сотрудник работает по проекту, Здесь, в конце месяца , мы заполняет документ Табель, далее начисление и выплата зарплаты. Тоже не возникает особых вопросов.
3. Когда сотрудник имеет почасовую оплату, когда 2, когда 3 часа в день, т.е. нет определенного временного графика. В данном случае как лучше действовать: использовать Табель(документ) ?
4.  И самое главное и интересное, когда наш сотрудник, работая у нас по основному месту получает и совместительство.
Попробовали воспроизвести данную ситуацию и столкнулись с рядом проблем в видении учета. Не совсем понятно как заполнять Табель(документ) и Табель(отчет). С нетерпением ждем ваше видение и объяснение по правильному учету и последовательности заполнения документации для правильного расчета зарплаты. Спасибо!

**Comment by SvetlanaRes** [comment]
@Nullarity, интересен п.3 - верно ли в данном случае использовать табель по проектам? т.е. в таком случае необходимо создать некоторого контрагента (наша же компания или неважно как назовем), создать проект типо "почасовая работа" и далее проставлять то, количество часов, которое необходимо. 
Так?

**Comment by Linda4ka** [comment]
Ну предположим, что можно и так, А как предлагаете вы? Я должна четко понимать как необходимо действовать и самое главное как действует программа!

**Comment by SvetlanaRes** [comment]
@Nullarity - самое интересное это сценарий 4. 
Предположим, сотрудник занимается некоторой административной работой (график - 4-х часовой) и участвует в проектной работе или даже выполняет дополнительную работу, которая оценивается в часах.
Как быть? Так чтобы и табеля корректно заполнялись и зарплата корректно рассчитывалась...

**Comment by Linda4ka** [comment]
Самое интересное это как при таком графике заполнить оба Табеля?

**Comment by Nullarity** [comment]
Спасибо! Давайте начнем с простого:
> Когда сотрудник имеет почасовую оплату, когда 2, когда 3 часа в день, т.е. нет определенного временного графика. В данном случае как лучше действовать: использовать Табель(документ) ?

По моим наблюдениям, при таких сценариях (когда график почасовой и не фиксированный), рабочее время заполняется самим сотрудником, ну или с его непосредственным участием. Не суть. В таком случае предполагается использовать документ Табель по проектам, где в качестве проекта создается определенный проект, либо, если таковой не имеет места, служебный, с названием "Почасовка" или на подобии. При этом в качестве контрагента выступает наша компания (которая уже существует в справочнике Контрагенты, и поставляется с начальной базой).
Стоит отдельно обратить внимание, что в этом случае, так как нет фиксированного графика, ни о каком автозаполнении речи быть не может, не говоря о природе фиксации такого типа рабочего времени.

**Comment by Linda4ka** [comment]
У меня не получилось - вообще никак)))

**Comment by Linda4ka** [comment]
Ну предположим что здесь я проиграла данную ситуацию именно так, вопросов нет! А вот 4 меня интересует гораздо больше!

**Comment by Nullarity** [comment]
в п4 по какому графику работает сотрудник?

**Comment by Linda4ka** [comment]
Основное место 8 часов и внутреннее совместительство, ну пускай 2 часа

**Comment by Nullarity** [comment]
Создайте график работы совместителя, 2 часа в день, примите его на работу, укажите этот график. Сформируйте отчет Табель, скажите что у вас получилось.

**Comment by Linda4ka** [comment]
Хорошо, завтра дам знать если все получилось!

**Comment by Nullarity** [comment]
Еще есть нюанс в случае использования Табель по проектам. Чтобы табель по проектам начал воздействовать на отчет Табель, он (Табель по проектам) должен быть утвержден, а не просто записан.

**Comment by Linda4ka** [comment]
Добрый день!Ну вариант с созданием дополнительного графика работ мы вчера со Светланой обговаривали. Это достаточно просто и заполнение Табеля(отчета) не вызывает вопросов. Он заполняется по сотруднику без каких-либо проблем.Начисление и выплата зарплаты тоже. Ну вот тогда у нас возникает 5, самый веселый и загадочный для исполнения сценарий, когда наш сотрудник при внутреннем совместительстве сегодня отработал 1 час, завтра 3 часа, а послезавтра 2 часа. В данном случае создание определенного графика невозможно и возникает потребность в заполнении обоих Табелей(документа) и (отчета). При моделировании данной ситуации в программе получилась полная каша. Если заполнить Табель(документ) и утвердить, для совместительства, а после попытаться заполнить Табель(отчет) для основного места работы получается следующее: Табель(отчет) заполняется Табелем(документом) и абсолютно не заполняется основным местом работы, он это просто не берет во внимание. Если попытаться заполнить Табель(отчет) по сотруднику, не имея определенного графика для совместительства, то это самое совместительство заполняется 8 и рассчитывается из расчета 8-ми часового рабочего дня.Правда в отчете возможно редактирование, но это ни на что не влияет. Если попробовать в Табеле (документ) на сотрудника сделать 2 документа один на совместительство, а один на основное место работы, а программа это позволяет, начинается веселье на стадии Начисления зарплаты. Программа видит  только один Табель(документ), созданный первым и абсолютно не берет во внимание и в расчеты второй, хотя период один.
Внимание, вопрос: Получается, что на данный момент использование двух Табелей(документа) и (отчета) одновременно невозможно? Как сделать это возможным?

**Comment by Nullarity** [comment]
> при внутреннем совместительстве сегодня отработал 1 час, завтра 3 часа, а послезавтра 2 часа. В данном случае создание определенного графика невозможно

Фактически отработанное время не связано с графиком работы сотрудника. Я не сталкивался со случаями, когда у сотрудника нет графика работы. Я правильно понимаю, что в вашем примере, такой сотрудник по совместительству имеет право не работать вообще (а если это продавец в магазине) или работать по 16 часов в сутки? Ведь графика у него никакого нет.

> В данном случае создание определенного графика невозможно и возникает потребность в заполнении обоих Табелей(документа) и (отчета). 

Мне кажется вы путаете понятия. При приеме сотрудника на работу, график работы должен быть определен, хоть стандартный, хоть гибкий, хоть сменный. без разницы. То, как фиксируется фактически отработанное время это другой процесс, который и имеет два способа расчета - прямой метод (время фиксируется в Табеле по проектам) или обратный (время фиксируется отклонениями).

> При моделировании данной ситуации в программе получилась полная каша

Мне не удалось воспроизвести ситуацию. Я принял сотрудника по совместительству, с часовым тарифом 250 лей, график ему установил "Совместители", где время работы поставил везде 0 (вот прям как ваш вырожденный случай). Ввел по нему табель, указал что он проработал только 1 час, сформировать отчет Табель, начислил зарплату:
![image](https://user-images.githubusercontent.com/28710693/120484169-ce577380-c380-11eb-8705-cc9af3a9dd36.png)
![image](https://user-images.githubusercontent.com/28710693/120484555-327a3780-c381-11eb-95e3-f77337477c4f.png)
![image](https://user-images.githubusercontent.com/28710693/120484429-11b1e200-c381-11eb-842d-5f1023b6727d.png)
![image](https://user-images.githubusercontent.com/28710693/120484090-bb44a380-c380-11eb-89cb-b8dac08ad4ae.png)

**Comment by Linda4ka** [comment]
т.е для данной ситуации нет необходимости проставлять время в графиках, там проставим 0? Я правильно поняла?

**Comment by Nullarity** [comment]
да

**Comment by Linda4ka** [comment]
Ладно, попробую, Дам знать что получилось и получилось ли.

**Comment by Linda4ka** [comment]
Получилось. Теперь я уже точно знаю как эти табели работают вдоль и поперек.Только не забудьте их переименовать, как мы определились. Спасибо за терпение!

**Comment by Linda4ka** [comment]
Но, если есть возможность, рассмотрите хотя бы вариант сохранения отчета Табель в архив. Это необходимо для того, чтобы избежать проблем следующего характера: кто-то куда-то залез и что-либо изменил. Такой вариант есть всегда, особенно когда несколько человек работают в программе. Так мы сможем избежать недоразумений. Если вдруг такая ситуация произойдет, то посмотреть как было и доказать, можно будет вытащив отчет табель из архива.

**Comment by Nullarity** [comment]
> Но, если есть возможность, рассмотрите хотя бы вариант сохранения отчета Табель в архив

А такая возможность есть, причем для всех отчетов, а не только для табеля. Но вот к сожалению, на текущий момент, она доступна только облачным пользователям:
![image](https://user-images.githubusercontent.com/28710693/120494175-986abd00-c389-11eb-9ddb-b5435fe1ee90.png)

В грядущем релизе, она появится для всех!

**Comment by Linda4ka** [comment]
Ну тогда хорошо. Посмотрим как это все пойдет нашим пользователям. Надеюсь, что их все устроит и не будет больших проблем с работой.

**Comment by Nullarity** [comment]
> Посмотрим как это все пойдет нашим пользователям

Предлагаю вообще не переживать на этот счет. Мы работаем в домене и создаем программы, которыми люди пользуются не от случая к случаю (как фейсбуком например), а профессионально, каждый день. И если отражение хозяйственной операции выполняется проще и экономит время, то вопрос вкусовщины отойдет на второй план после второй итерации (яркий пример, машины с коробкой автомат, все вначале критиковали, а теперь это стандарт). Но вот если оно будет работать плохо, неправильно и неудобно, на это будут причины и конкретные сценарии, и нет ничего, чтобы мешало бы нам исправлять ситуацию, при сохранении конструктивного разговора, конечно же.

**Comment by Linda4ka** [comment]
Я не водитель, мне пример с машиной вообще ни о чем))), а так ладно, поработаем и посмотрим!
