### ISSUE TITLE
Имя покупателя не отображается в ПКО

### ISSUE THREAD

**Issue by TeodorUn** [Contabilizare/c5#9]
При создании ПКО из документа оплаты имя покупателя (физическое лицо) не попадает в печатную форму.

![image](https://user-images.githubusercontent.com/82500510/114856267-948dd600-9def-11eb-85c0-850de474ed78.png)

**Comment by Nullarity** [comment]
да, тут ошибка. Пока не исправили, в качестве обхода, можно заполнить получателя в форме ввода данных в ПКО (непосредственно до формирования печатной формы)

**Comment by Nullarity** [comment]
Исправлено в 5.0.14.4
