### ISSUE TITLE
Товары подразделений - предназначение данного документа

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#91]
Хотелось бы понять для чего предназначен документ Товары подразделений, необходимость его заполнения и диапазон его использования. На что влияет и влияет ли вообще на что-либо?!

**Comment by Nullarity** [comment]
Это справочная информация и служит фильтром при заполнении документов на основании заказов. То есть при заполнении, будет принято во внимание подразделение и перечень материалов, которые используются этим подразделением. Ровно по такому же принципу работают товары поставщика.

**Comment by Linda4ka** [comment]
Понятно, спасибо!
