### ISSUE TITLE
Дублирование создания документов.

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#93]
Для чего необходимо, и необходимо ли вообще, производить дублирование Создания документов, как например документы Заказ покупателя и Коммерческое предложение, которые дублируются на закладках Главное и Продажи. Если я не ошибаюсь, то это одни и те же документы, тогда смысл их дублировать? Если они относятся к Продажам, может лучше их только там и оставить, чтоб не сбивать столку?
Этот вопрос касается и отчетов, дублирующихся на закладке Главное и Продажи: Заказы товаров-покупателей, Дебиторы, Прайс-лист и Состояние коммерческих предложений. Может их тоже лучше не дублировать, а оставить только в Продажах?

**Comment by Nullarity** [comment]
Меню главное - это частотные функции "под рукой". Тут конечно угодить всем случаям не получится, возможно есть смысл что-то еще добавить или удалить, но сам принцип таков, что функции в меню Главное выведены из других разделов, для быстрого к ним доступа.

**Comment by Linda4ka** [comment]
Не вижу смысла, но вам видней. Просто сбивает с толку

**Comment by Nullarity** [comment]
Что бы мне открыть Покупателей или Поставщиков или сделать Запись времени, без меню Главное, мне пришлось зайти в три разных раздела программа. Это не удобно.
По началу это возможно сбивает с толку, но давайте вернемся к вопросу через время.

**Comment by Linda4ka** [comment]
Хорошо!
