### ISSUE TITLE
Исправление грамматических ошибок

### ISSUE THREAD

**Issue by Linda4ka** [Contabilizare/c5#94]
Это конечно вопрос не первой важности, но  исправить стоит, если только это не связано с военными действиями)
![image](https://user-images.githubusercontent.com/84187165/120483857-2b701b00-c3bb-11eb-993d-a80ef4e6615d.png)
![image](https://user-images.githubusercontent.com/84187165/120485621-f5339b00-c3bc-11eb-85fd-d804a6755825.png)
![image](https://user-images.githubusercontent.com/84187165/120485736-11373c80-c3bd-11eb-809b-9e6b7fb57b14.png)

**Comment by Nullarity** [comment]
Здесь нет ошибки. В данном контексте, кампания - это мероприятие, а не субъект хозяйственной деятельности.

**Comment by Linda4ka** [comment]
Лучше назовите по-другому, наш народ умный, будут тыкать пальцем. Может стоит так и назвать Мероприятие?

**Comment by Nullarity** [comment]
Но ведь это устоявшиеся выражения, я даже не знаю на что их заменить:
Рекламная компания - это организация, оказывающая услуги по рекламе.
Рекламная кампания - это совокупность мероприятий для осуществления поставленных целей.

(рекламное) Мероприятие - мне не встречалось. Может предложите еще варианты?

**Comment by Linda4ka** [comment]
Рекламное предложение?

**Comment by Nullarity** [comment]
...фирма Contabilizare начинает обширную рекламную кампанию по продвижению своих продуктов на молдавском рынке...

"предложение" тут не подходит, а именно контекст выше и определяет пункты в меню.

**Comment by Nullarity** [comment]
Давайте не будет мучиться, из-за тех, что прогуливал уроки? ))

**Comment by Linda4ka** [comment]
Хорошо, давайте оставим как есть. Посмотрим, так сказать, на люд грамотный)))

**Comment by SvetlanaRes** [comment]
> Но ведь это устоявшиеся выражения, я даже не знаю на что их заменить:
> Рекламная компания - это организация, оказывающая услуги по рекламе.
> Рекламная кампания - это совокупность мероприятий для осуществления поставленных целей.

Не знала)))
Спасибо за ликбез))
