### ISSUE TITLE
Скидка за срочность платежа, нужна помощь

### ISSUE THREAD

**Issue by Nullarity** [Contabilizare/c5#95]
Коллеги, поделитесь пожалуйста опытом. Одной из интересных возможностей программы, является функция автоматического предоставления скидки, в случае когда клиент платит быстро. Это позволяет автоматизировать такие сценарии:
1. Выписываем счет на 100 лей, в котором пишем, что при оплате в течении 5 рабочих дней, можно заплатить сумму на 3% ниже указанной в счете.
2. Клиент платит быстро, получаем от него 97 лей
3. Мы проводим реализацию с предоставленной скидкой

Все хорошо.

Теперь вопрос: а что если клиент в течении недели платит дважды, и более того, мы проводим реализацию, между его оплатами в течении 5 дней; что обычно в таких случаях делают клиенты или что бы они предполагали делать?

Почему вообще тут вопрос? Потому что если клиент заплатил быстро только часть, готовы ли мы давать ему скидку? Ведь мы не знаем, вторую часть, он тоже оплатит быстро или уже потом, когда мы скидку не предоставляем.

Пишите если есть какие соображение на этот счет.

Спасибо!

**Comment by SvetlanaRes** [comment]
Поделюсь своим опытом:
1) условия считаются выполненными, и клиент может рассчитывать на скидку только при полной оплате/погашении задолженности в течение указанного срока.
2) дата выписки накладной/реализации не влияет на возможность воспользоваться скидкой.
3) при выполнения условия и предоставлении скидки - формируется реализация (пересчет) на сумму скидки с минусом (если реализация была до выполнения условий по оплатам).

P.S. Для такого "пересчета" делали документ/обработку, на основании которого формировалась реализация на скидку с минусом, даже попозиционно по номенклатуре, чтоб увидеть реальные доходы/прибыль по каждой номенклатуре.
